/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.daily_005fexpenses;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import daily_expenses.Daily_Expenses_ACT;
import attendance_master.Attendance_ACT;

public final class view_005fdaily_005fexpenses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/daily_expenses/../staticresources/includes/itswsstyles.jsp", Long.valueOf(1637404914000L));
    _jspx_dependants.put("/staticresources/includes/itswsscripts.jsp", Long.valueOf(1637404914000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("attendance_master.Attendance_ACT");
    _jspx_imports_classes.add("daily_expenses.Daily_Expenses_ACT");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\r\n");
      out.write("<title>Edit Daily Expenses</title>\r\n");
      out.write("<META NAME=\"ROBOTS\" CONTENT=\"NOINDEX, NOFOLLOW\"></META>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/images/favicon.png\" type=\"image/ico\"/>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/font-awesome.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.fancybox.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery-ui.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap-datetimepicker.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/error.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/daterangepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/select2.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/mdtimepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/theme.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.dataTables.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/buttons.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");

String token= (String)session.getAttribute("uavalidtokenno");
String url = request.getParameter("uid");
String[] a=url.split(".html");
String[] b=a[0].split("-");
String custid=b[1];
String[][] getExpensedata=Daily_Expenses_ACT.getallExpensesById(custid,token);

      out.write("\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-xs-12\">\r\n");
      out.write("<div class=\"menuDv  post-slider advert mb10\">\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/update-daily-expenses.html\" method=\"post\" name=\"add_expence\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Invoice No. :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-file\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"invoiceno\" id=\"Invoice No\" value=\"");
      out.print(getExpensedata[0][12] );
      out.write("\" class=\"form-control\" placeholder=\"Invoice No.*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"InvoiceNoerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Amount :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-money\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"Amount\" id=\"Amount\" class=\"form-control\" value=\"");
      out.print(getExpensedata[0][1] );
      out.write("\" placeholder=\"Amount*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"AmounterrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>GST Applicable :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-money\"></i></span>\r\n");
      out.write("<select name=\"gst\" id=\"GST\" class=\"form-control\" disabled=\"disabled\">\r\n");
      out.write("	<option value=\"");
      out.print(getExpensedata[0][19] );
      out.write('"');
      out.write('>');
      out.print(getExpensedata[0][19] );
      out.write("</option>	\r\n");
      out.write("</select>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"GSTerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\" id=\"GST_Box\" style=\"display: none;\">\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>GST Category :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-bookmark\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"gstcategory\" id=\"GST Category\" value=\"");
      out.print(getExpensedata[0][15] );
      out.write("\" class=\"form-control\" placeholder=\"GST Category*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"gstcategoryerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>GST Tax &nbsp;% :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-user\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"gsttax\" id=\"GST Tax\" value=\"");
      out.print(getExpensedata[0][16] );
      out.write("\" class=\"form-control\" placeholder=\"GST Tax*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"gsttaxerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>GST Value :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-money\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"gstvalue\" id=\"GST Value\" value=\"");
      out.print(getExpensedata[0][17] );
      out.write("\" class=\"form-control\" readonly placeholder=\"GST Value*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"gstvalueerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Place :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-map\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"place\" id=\"Place\" value=\"");
      out.print(getExpensedata[0][13] );
      out.write("\" class=\"form-control\" placeholder=\"Place*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"PlaceerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Service Code :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-file\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"servicecode\" id=\"Service Code\" value=\"");
      out.print(getExpensedata[0][14] );
      out.write("\" class=\"form-control\" placeholder=\"Service Code*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"ServiceCodeerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Paid To :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-user\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"Paid To\" id=\"Paid_To\" autocomplete=\"off\" value=\"");
      out.print(getExpensedata[0][2] );
      out.write("\" class=\"form-control\" placeholder=\"Paid To*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"PaidToerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Expense Category :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-bars\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"ExpensesCategory\" value=\"");
      out.print(getExpensedata[0][3] );
      out.write("\" id=\"Expenses Category\" class=\"form-control\" placeholder=\"Expenses Category*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"ExpensesCategoryerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Total Invoice Amount :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-money\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"totalinvoiceamount\" id=\"Total Invoice Amount\" value=\"");
      out.print(getExpensedata[0][18] );
      out.write("\" class=\"form-control\" readonly placeholder=\"Total Invoice Amount*\" >\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"totalinvoiceAmounterrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Description :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon sprite edit-top1\"></i></span>\r\n");
      out.write("<textarea name=\"Description\" id=\"Description\" placeholder=\"Description*\" class=\"form-control\" readonly>");
      out.print(getExpensedata[0][4] );
      out.write("</textarea>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"DescriptionerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Payment Mode :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-money\"></i></span>\r\n");
      out.write("<!-- <input type=\"text\" name=\"PaymentMode\" id=\"PaymentMode\" class=\"form-control\" placeholder=\"Payment Mode*\"  onblur=\"requiredFieldValidation('Payment Mode','PaymentModeerrorMSGdiv');\"> -->\r\n");
      out.write("<select name=\"PaymentMode\" id=\"PaymentMode\" class=\"form-control\" disabled=\"disabled\">\r\n");
      out.write("	<option value=\"");
      out.print(getExpensedata[0][5] );
      out.write('"');
      out.write('>');
      out.print(getExpensedata[0][5] );
      out.write("</option>\r\n");
      out.write("</select>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"PaymentModeerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Approved By :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-user\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"ApprovedBy\" id=\"ApprovedBy\" value=\"");
      out.print(getExpensedata[0][6] );
      out.write("\" class=\"form-control\" placeholder=\"Approved By*\" autocomplete=\"off\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"ApprovedByerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<label>Date of Payment :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("<div class=\"input-group\">\r\n");
      out.write("<span class=\"input-group-addon\"><i class=\"form-icon fa fa-calendar\"></i></span>\r\n");
      out.write("<input type=\"text\" name=\"PaidDate\" id=\"PaidDate\" value=\"");
      out.print(getExpensedata[0][7] );
      out.write("\" class=\"form-control\" placeholder=\"Paid Date*\" readonly>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"PaidDateerrorMSGdiv\" class=\"errormsg\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.fancybox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/nicEdit.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/globalscript.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/select2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/daterangepicker.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/mdtimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/fontawsome.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/theme.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jszip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/pdfmake.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/vfs_fonts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.html5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.print.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.colVis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready( function () {\r\n");
      out.write("	var role=\"");
      out.print(session.getAttribute("emproleid"));
      out.write("\";\r\n");
      out.write("	$(\".checked\").click(function(){\r\n");
      out.write("		 if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("			 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("	$(\"#CheckAll\").click(function(){\r\n");
      out.write("	$('.checked').prop('checked', this.checked);\r\n");
      out.write("	if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("		 	 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		    \r\n");
      out.write("	});\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write(" $(window).load(function() {\r\n");
      out.write("  $(\".processing_loader\").fadeOut();\r\n");
      out.write("}); \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function showLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeIn(); \r\n");
      out.write("} \r\n");
      out.write("function hideLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeOut();  \r\n");
      out.write("}  \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.timepicker').mdtimepicker();\r\n");
      out.write("function openClock(id){\r\n");
      out.write("$('#'+id).mdtimepicker();\r\n");
      out.write("}\r\n");
      out.write("function openCalendar(id){\r\n");
      out.write("	$(\"#\"+id).datepicker({changeMonth:true,changeYear:true,dateFormat:'yy-mm-dd'});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.has-clear input[type=\"text\"]').on('input propertychange', function() {\r\n");
      out.write("  var $this = $(this);\r\n");
      out.write("  var visible = Boolean($this.val());\r\n");
      out.write("  $this.siblings('.form-control-clear').toggleClass('hidden', !visible);\r\n");
      out.write("}).trigger('propertychange');\r\n");
      out.write("\r\n");
      out.write("$('.form-control-clear').click(function() {\r\n");
      out.write("  $(this).siblings('input[type=\"text\"]').val('')\r\n");
      out.write("    .trigger('propertychange').focus();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goBack() {\r\n");
      out.write("  window.history.back();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
