/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.workscheduler;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import workscheduler.WorkSchedulerACT;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class workschedulerfollowup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/workscheduler/../staticresources/includes/itswsstyles.jsp", Long.valueOf(1637404914000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("workscheduler.WorkSchedulerACT");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\r\n");
      out.write("<title>Work Scheduler Follow Up</title>\r\n");
      out.write("<META NAME=\"ROBOTS\" CONTENT=\"NOINDEX, NOFOLLOW\"></META>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/images/favicon.png\" type=\"image/ico\"/>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/font-awesome.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.fancybox.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery-ui.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap-datetimepicker.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/error.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/daterangepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/select2.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/mdtimepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/theme.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.dataTables.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/buttons.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String wsuid = request.getParameter("uid");

      out.write("\r\n");
      out.write("<div class=\"container min_width\">\r\n");
      out.write("<div class=\"row advert\">\r\n");
      out.write("  <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("            <div class=\"menuDv partner-slider8 mb10\">\r\n");
      out.write("                <div class=\"box-intro\">\r\n");
      out.write("                  <h2><span class=\"title\">Follow Up</span></h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                <form onsubmit=\"return false;\" method=\"post\" id=\"workschedulefollowup\">\r\n");
      out.write("                <input type=\"hidden\" name=\"wsuid\" id=\"wsuid\" value=\"");
      out.print(wsuid);
      out.write("\" />\r\n");
      out.write("                  <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                   <div class=\"clearfix\">\r\n");
      out.write("                    <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                        <label>Status :</label>\r\n");
      out.write("                        <select class=\"form-control\" id=\"fstatus\" name=\"fstatus\"><option value=\"Pending\">Pending</option><option value=\"Completed\">Completed</option></select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                        <label>Remarks :</label>\r\n");
      out.write("                        <textarea class=\"form-control\" id=\"fremarks\" name=\"fremarks\" rows=\"3\" placeholder=\"Enter Remarks\" required></textarea>\r\n");
      out.write("                        <div id=\"ErrorDiv\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                        <div class=\"mb10 advert clearfix text-center\">\r\n");
      out.write("                        <input type=\"submit\" value=\"Save\" class=\"bt-link bt-radius bt-loadmore\" onclick=\"savefollowup();\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("                 </form>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-8 col-sm-8 col-xs-12\">\r\n");
      out.write("            <div class=\"menuDv partner-slider8 mb10\">\r\n");
      out.write("                <div class=\"box-intro\">\r\n");
      out.write("                  <h2><span class=\"title\">Work Scheduler</span></h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                   <div class=\"clearfix\">\r\n");
      out.write("                    <div class=\"col-md-1 col-xs-1 box-intro-bg\">\r\n");
      out.write("                        <div class=\"box-intro-border\">\r\n");
      out.write("                        <p class=\"news-border\">SN</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-2 col-xs-2 box-intro-bg\">\r\n");
      out.write("                        <div class=\"box-intro-border\">\r\n");
      out.write("                        <p class=\"news-border\">Date</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                      <div class=\"col-md-2 col-xs-2 box-intro-bg\">\r\n");
      out.write("                        <div class=\"box-intro-border\">\r\n");
      out.write("                        <p class=\"news-border\">Status</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-7 col-xs-4 box-intro-bg\">\r\n");
      out.write("                        <div class=\"box-intro-border\">\r\n");
      out.write("                        <p>Remarks</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               <div id=\"target\">\r\n");
      out.write("                ");

                String[][] works = WorkSchedulerACT.getFollowUpById(wsuid);
                for(int i=0;i<works.length;i++) {
                 
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                   <div class=\"clearfix\">\r\n");
      out.write("                    <div class=\"col-md-1 col-xs-1 box-intro-background\">\r\n");
      out.write("                        <div class=\"link-style12\">\r\n");
      out.write("                        <p class=\"news-border\">");
      out.print(works[i][0] );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-2 col-xs-1 box-intro-background\">\r\n");
      out.write("                        <div class=\"link-style12\">\r\n");
      out.write("                        <p class=\"news-border\">");
      out.print(works[i][1] );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-2 col-xs-3 box-intro-background\">\r\n");
      out.write("                        <div class=\"link-style12\">\r\n");
      out.write("                        <p class=\"news-border\">");
      out.print(works[i][2] );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-7 col-xs-12 box-intro-background\">\r\n");
      out.write("                        <div class=\"link-style12\">\r\n");
      out.write("                        <p>");
      out.print(works[i][3] );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("           </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function savefollowup(){\r\n");
      out.write("    if($(\"textarea#fremarks\").val()==\"\") return false;\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        url: '");
      out.print(request.getContextPath());
      out.write("/saveworkschedulerfollowup.html',\r\n");
      out.write("        datatype : \"HTML\",\r\n");
      out.write("        data: {\r\n");
      out.write("            \"today\" : $(\"#today\").val(),\r\n");
      out.write("            \"fstatus\" : $(\"#fstatus\").val(),\r\n");
      out.write("            \"remarks\" : $(\"textarea#fremarks\").val(),\r\n");
      out.write("            \"wsuid\" : $(\"#wsuid\").val()\r\n");
      out.write("            },\r\n");
      out.write("        success: function(data){\r\n");
      out.write("            $(\"#workschedulefollowup\").trigger(\"reset\");\r\n");
      out.write("            $(\"#target\").load(\"");
      out.print(request.getContextPath());
      out.write("/workschedulerfollowup-1.html #target\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
