/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mseo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import admin.seo.SeoOnPage_ACT;
import admin.task.TaskMaster_ACT;
import admin.Login.LoginAction;

public final class new_002ddocument_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/mseo/../staticresources/includes/itswsscripts.jsp", Long.valueOf(1637404914000L));
    _jspx_dependants.put("/mseo/../../madministrator/checkvalid_user.jsp", Long.valueOf(1648627112000L));
    _jspx_dependants.put("/mseo/../staticresources/includes/itswsstyles.jsp", Long.valueOf(1637404914000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("admin.Login.LoginAction");
    _jspx_imports_classes.add("admin.seo.SeoOnPage_ACT");
    _jspx_imports_classes.add("admin.task.TaskMaster_ACT");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

response.addHeader("Pragma", "no-cache");
response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
response.addHeader("Cache-Control", "pre-check=0, post-check=0");
response.setDateHeader("Expires", 0);

String uavalidtokenno1111= (String)session.getAttribute("uavalidtokenno");
String uaIsValid1= (String)session.getAttribute("loginuID");

String sessionid = (String) session.getAttribute("sessionID");
String euaValidForAccess =  LoginAction.getPermissions(uaIsValid1, sessionid);
if(uaIsValid1== null || uaIsValid1.equals("") || uavalidtokenno1111== null || uavalidtokenno1111.equals("")||euaValidForAccess==null){	

      out.write('\r');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("/login.html");
        return;
      }
      out.write('\r');
      out.write('\n');
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\r\n");
      out.write("	<title></title>\r\n");
      out.write("	");
      out.write("<META NAME=\"ROBOTS\" CONTENT=\"NOINDEX, NOFOLLOW\"></META>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/images/favicon.png\" type=\"image/ico\"/>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/font-awesome.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.fancybox.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery-ui.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap-datetimepicker.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/error.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/daterangepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/select2.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/mdtimepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/theme.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.dataTables.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/buttons.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String prno=request.getParameter("pr097bjno");
String clname=request.getParameter("cl09tyname");
String token=(String)session.getAttribute("uavalidtokenno");
String emproleid=(String)session.getAttribute("emproleid");
String loginuaid=(String)session.getAttribute("loginuaid");
String folder[][]=SeoOnPage_ACT.getAllFolder(token,emproleid,loginuaid,"NA","sales","NA",0,0); 

      out.write(" \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                <div class=\"menuDv clearfix\">\r\n");
      out.write("                    <div class=\"box-intro\">\r\n");
      out.write("                      <h2><span class=\"title\">Upload Document</span></h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <div class=\"clearfix pad_box2\" id=\"UploadDoc\">\r\n");
      out.write("                       <form action=\"");
      out.print(request.getContextPath() );
      out.write("/new-file.html\" method=\"post\"  name=\"follow-up-form\" enctype=\"multipart/form-data\">\r\n");
      out.write("                        <div class=\"row mtop10\">\r\n");
      out.write("                        <div class=\"col-xs-6\">\r\n");
      out.write("                        <div class=\"clearfix form-group\">\r\n");
      out.write("                            <label>Document Type :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("                            <div class=\"clearfix relative_box\">\r\n");
      out.write("                           	<select name=\"doctype\" id=\"Doc_Type\" class=\"form-control\" onchange=\"showMessage(this.value)\">\r\n");
      out.write("                          \r\n");
      out.write("                            \r\n");
      out.write("                            <option value=\"\">Select Document Type</option>\r\n");
      out.write("                            <option value=\"General\">General</option>                              \r\n");
      out.write("                            <option value=\"Certificate\" ");
if(prno!=""&&prno.length()>0&&prno!=null&&clname!=""&&clname.length()>0&&clname!=null) {
      out.write("selected=\"selected\"");
} 
      out.write(">Certificate</option>\r\n");
      out.write("                          </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       <div class=\"col-xs-6\">\r\n");
      out.write("                        <div class=\"clearfix form-group\">\r\n");
      out.write("                            <label>Document Name :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("                            <div class=\"clearfix relative_box\">\r\n");
      out.write("                           	<input type=\"text\" name=\"docname\" autocomplete=\"off\" id=\"Doc_Name\" class=\"form-control\" placeholder=\"Document Name here !\"/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row mtop10\">\r\n");
      out.write("           				 <div class=\"col-xs-4\">\r\n");
      out.write("                        <div class=\"clearfix form-group\">\r\n");
      out.write("                            <label>Select Folder :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("                            <div class=\"clearfix relative_box\">\r\n");
      out.write("                           <select id=\"Folder\" name=\"folder\" onblur=\"requiredFieldValidation('Folder','folderErr');\" class=\"form-control\" onchange=\"getSubFolder(this.value)\">\r\n");
      out.write("                            <option value=\"\">Select Folder</option>\r\n");
      out.write("                            ");
if(folder.length>0){ for(int i=0;i<folder.length;i++){
                            	if(clname!=""&&clname.length()>0&&clname!=null&&clname.equalsIgnoreCase(folder[i][1])) {
      out.write("                           \r\n");
      out.write("                            <option value=\"");
      out.print(folder[i][0]);
      out.write('#');
      out.print(folder[i][1]);
      out.write("\" selected=\"selected\">");
      out.print(folder[i][1]);
      out.write("</option>\r\n");
      out.write("                            ");
}else{
      out.write("\r\n");
      out.write("                            <option value=\"");
      out.print(folder[i][0]);
      out.write('#');
      out.print(folder[i][1]);
      out.write('"');
      out.write('>');
      out.print(folder[i][1]);
      out.write("</option>                            	\r\n");
      out.write("                            ");
}}} 
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <div id=\"folderErr\" class=\"popup_error\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       <div class=\"col-xs-4\">\r\n");
      out.write("                        <div class=\"clearfix form-group\">\r\n");
      out.write("                            <label>Select Sub Folder :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("                            <div class=\"clearfix relative_box\">\r\n");
      out.write("                           <select id=\"Sub_Folder\" name=\"subfolder\" onblur=\"requiredFieldValidation('Folder','folderErr');\" class=\"form-control\">\r\n");
      out.write("                            <option value=\"NA\">Select Sub Folder</option>                            \r\n");
      out.write("                            </select>\r\n");
      out.write("                            <div id=\"subfolderErr\" class=\"popup_error\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       <div class=\"col-xs-4\">\r\n");
      out.write("                        <div class=\"clearfix form-group\">\r\n");
      out.write("                            <label>Document :<i style=\"color: red;font-size: 11px;\">(Max-Size 4Mb.)</i><span style=\"color: red;\">*</span></label>\r\n");
      out.write("                            <div class=\"clearfix relative_box\">\r\n");
      out.write("                            <input type=\"file\" id=\"Document\" onchange=\"fileSize(this)\" autocomplete=\"off\" name=\"document\" onblur=\"requiredFieldValidation('Document','documentErr');\" class=\"form-control\" />\r\n");
      out.write("                            <div id=\"documentErr\" class=\"popup_error\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>  \r\n");
      out.write("                           </div>\r\n");
      out.write("                           </div>                       \r\n");
      out.write("                            <div class=\"clearfix form-group text-center\">\r\n");
      out.write("                                  <button class=\"bt-link bt-radius bt-loadmore\" type=\"submit\" id=\"Upload\" onclick=\"return documentValidation();\">Upload</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                   </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"alert-show\"><div class=\"alert-bg alert-striped\" id=\"errorMsg\" style=\"width: 33%;\"></div></div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.fancybox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/nicEdit.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/globalscript.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/select2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/daterangepicker.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/mdtimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/fontawsome.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/theme.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jszip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/pdfmake.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/vfs_fonts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.html5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.print.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.colVis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready( function () {\r\n");
      out.write("	var role=\"");
      out.print(session.getAttribute("emproleid"));
      out.write("\";\r\n");
      out.write("	$(\".checked\").click(function(){\r\n");
      out.write("		 if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("			 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("	$(\"#CheckAll\").click(function(){\r\n");
      out.write("	$('.checked').prop('checked', this.checked);\r\n");
      out.write("	if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("		 	 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		    \r\n");
      out.write("	});\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write(" $(window).load(function() {\r\n");
      out.write("  $(\".processing_loader\").fadeOut();\r\n");
      out.write("}); \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function showLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeIn(); \r\n");
      out.write("} \r\n");
      out.write("function hideLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeOut();  \r\n");
      out.write("}  \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.timepicker').mdtimepicker();\r\n");
      out.write("function openClock(id){\r\n");
      out.write("$('#'+id).mdtimepicker();\r\n");
      out.write("}\r\n");
      out.write("function openCalendar(id){\r\n");
      out.write("	$(\"#\"+id).datepicker({changeMonth:true,changeYear:true,dateFormat:'yy-mm-dd'});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.has-clear input[type=\"text\"]').on('input propertychange', function() {\r\n");
      out.write("  var $this = $(this);\r\n");
      out.write("  var visible = Boolean($this.val());\r\n");
      out.write("  $this.siblings('.form-control-clear').toggleClass('hidden', !visible);\r\n");
      out.write("}).trigger('propertychange');\r\n");
      out.write("\r\n");
      out.write("$('.form-control-clear').click(function() {\r\n");
      out.write("  $(this).siblings('input[type=\"text\"]').val('')\r\n");
      out.write("    .trigger('propertychange').focus();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goBack() {\r\n");
      out.write("  window.history.back();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function showMessage(val){\r\n");
      out.write("	if(val==\"Certificate\"){\r\n");
      out.write("		document.getElementById('errorMsg').innerHTML =\"Upload Certificate in Project's Folder.\";\r\n");
      out.write("		document.getElementById('errorMsg').style.background=\"green\";\r\n");
      out.write("		document.getElementById('errorMsg').style.color=\"white\";\r\n");
      out.write("		$('.alert-show').show().delay(3000).fadeOut();\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("function fileSize(file){\r\n");
      out.write("	const fi=document.getElementById('Document');\r\n");
      out.write("	if (fi.files.length > 0) {\r\n");
      out.write("		const fsize = fi.files.item(0).size; \r\n");
      out.write("        const file = Math.round((fsize / 1024)); \r\n");
      out.write("        // The size of the file. \r\n");
      out.write("        if (file >= 4096) {  \r\n");
      out.write("            document.getElementById('errorMsg').innerHTML ='File too Big, please select a file less than 4mb';\r\n");
      out.write("            document.getElementById(\"Document\").value=\"\";\r\n");
      out.write("            document.getElementById('errorMsg').style.width=\"50%\";\r\n");
      out.write(" 		    $('.alert-show').show().delay(4000).fadeOut();\r\n");
      out.write("        }		\r\n");
      out.write("	}	\r\n");
      out.write("}\r\n");
      out.write("    </script>\r\n");
      out.write("<script type=\"text/javascript\">	\r\n");
      out.write("	$('#cancelpopup').click(function(){\r\n");
      out.write("		  $.fancybox.close();\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("var prno=\"");
      out.print(prno);
      out.write("\";\r\n");
      out.write("if(prno!=\"\"&&prno!=null){\r\n");
      out.write("	setTimeout(function(){ \r\n");
      out.write("		var folder=document.getElementById(\"Folder\").value.trim();\r\n");
      out.write("		var x=folder.split(\"#\");\r\n");
      out.write("		frefid=x[0];\r\n");
      out.write("		showLoader();\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"GetSubFolderById111\",\r\n");
      out.write("			dataType : \"HTML\",\r\n");
      out.write("			data : {				\r\n");
      out.write("				frefid:frefid,\r\n");
      out.write("				prno:prno\r\n");
      out.write("			},\r\n");
      out.write("			success : function(response){\r\n");
      out.write("				response = JSON.parse(response);			\r\n");
      out.write("				 var len = response.length;\r\n");
      out.write("				 if(len>0) {\r\n");
      out.write("					 var id = response[0]['id'];\r\n");
      out.write("					 var name = response[0]['value'];\r\n");
      out.write("					 $(\"#Sub_Folder\").append(\"<option value='\"+id+\"#\"+name+\"' selected>\"+name+\"</option>\");\r\n");
      out.write("				 }  				\r\n");
      out.write("			},\r\n");
      out.write("			complete : function(data){\r\n");
      out.write("				hideLoader();\r\n");
      out.write("			}\r\n");
      out.write("		});	\r\n");
      out.write("	}, 1000);\r\n");
      out.write("}\r\n");
      out.write("});\r\n");
      out.write("function getSubFolder(frefid){\r\n");
      out.write("	if(frefid!=\"\"){\r\n");
      out.write("		var x=frefid.split(\"#\");\r\n");
      out.write("		frefid=x[0];\r\n");
      out.write("		showLoader();\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : \"POST\",\r\n");
      out.write("		url : \"GetSubFolder111\",\r\n");
      out.write("		dataType : \"HTML\",\r\n");
      out.write("		data : {				\r\n");
      out.write("			\"frefid\":frefid,\r\n");
      out.write("		},\r\n");
      out.write("		success : function(response){\r\n");
      out.write("			response = JSON.parse(response);			\r\n");
      out.write("			 var len = response.length;\r\n");
      out.write("			    $(\"#Sub_Folder\").empty();\r\n");
      out.write("			    $(\"#Sub_Folder\").append(\"<option value='NA'>\"+\"Select Sub Folder\"+\"</option>\");\r\n");
      out.write("				for( var i =0; i<len; i++){\r\n");
      out.write("				var id = response[i]['id'];\r\n");
      out.write("				var name = response[i]['value'];\r\n");
      out.write("				$(\"#Sub_Folder\").append(\"<option value='\"+id+\"#\"+name+\"'>\"+name+\"</option>\");\r\n");
      out.write("				}\r\n");
      out.write("		},\r\n");
      out.write("		complete : function(data){\r\n");
      out.write("			hideLoader();\r\n");
      out.write("		}\r\n");
      out.write("	});}else{\r\n");
      out.write("		$(\"#Sub_Folder\").empty();\r\n");
      out.write("	    $(\"#Sub_Folder\").append(\"<option value='NA'>\"+\"Select Sub Folder\"+\"</option>\");	   \r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("	function documentValidation() {\r\n");
      out.write("\r\n");
      out.write("	if(document.getElementById('Doc_Type').value.trim()==\"\" ) {\r\n");
      out.write("		document.getElementById('errorMsg').innerHTML = 'Document Type is required..';\r\n");
      out.write("		$('.alert-show').show().delay(1000).fadeOut();\r\n");
      out.write("	return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(document.getElementById('Doc_Name').value.trim()==\"\" ) {\r\n");
      out.write("		document.getElementById('errorMsg').innerHTML = 'Document Name is required.';\r\n");
      out.write("		$('.alert-show').show().delay(1000).fadeOut();\r\n");
      out.write("	return false;\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("	if(document.getElementById('Folder').value.trim()==\"\" ) {\r\n");
      out.write("		document.getElementById('errorMsg').innerHTML = 'Select Folder/Sub-Folder To Upload File.';\r\n");
      out.write("		$('.alert-show').show().delay(1000).fadeOut();\r\n");
      out.write("	return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(document.getElementById('Document').value.trim()==\"\" ) {\r\n");
      out.write("		document.getElementById('errorMsg').innerHTML = 'Document is required.';\r\n");
      out.write("		$('.alert-show').show().delay(1000).fadeOut();\r\n");
      out.write("	return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(document.getElementById('Folder').value.trim()!=\"\"&&document.getElementById('Document').value.trim()!=\"\"){\r\n");
      out.write("		parent.jQuery.fancybox.close();\r\n");
      out.write("		document.getElementById('errorMsg').innerHTML = 'Certificate Successfully Uploaded.';			\r\n");
      out.write("		document.getElementById('errorMsg').style.background=\"green\";\r\n");
      out.write("		document.getElementById('errorMsg').style.color=\"#ffff\";\r\n");
      out.write("		$('.alert-show').show().delay(1000).fadeOut();\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
