/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mseo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import admin.task.TaskMaster_ACT;
import admin.Login.LoginAction;
import admin.enquiry.Enquiry_ACT;

public final class sub_002dfolder_002daccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/mseo/../staticresources/includes/itswsscripts.jsp", Long.valueOf(1637404914000L));
    _jspx_dependants.put("/mseo/../../madministrator/checkvalid_user.jsp", Long.valueOf(1648627112000L));
    _jspx_dependants.put("/mseo/../staticresources/includes/itswsstyles.jsp", Long.valueOf(1637404914000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("admin.Login.LoginAction");
    _jspx_imports_classes.add("admin.enquiry.Enquiry_ACT");
    _jspx_imports_classes.add("admin.task.TaskMaster_ACT");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

response.addHeader("Pragma", "no-cache");
response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
response.addHeader("Cache-Control", "pre-check=0, post-check=0");
response.setDateHeader("Expires", 0);

String uavalidtokenno1111= (String)session.getAttribute("uavalidtokenno");
String uaIsValid1= (String)session.getAttribute("loginuID");

String sessionid = (String) session.getAttribute("sessionID");
String euaValidForAccess =  LoginAction.getPermissions(uaIsValid1, sessionid);
if(uaIsValid1== null || uaIsValid1.equals("") || uavalidtokenno1111== null || uavalidtokenno1111.equals("")||euaValidForAccess==null){	

      out.write('\r');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("/login.html");
        return;
      }
      out.write('\r');
      out.write('\n');
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\r\n");
      out.write("	<title>Grant/Deny Access Sub-Folder Permission</title>\r\n");
      out.write("	");
      out.write("<META NAME=\"ROBOTS\" CONTENT=\"NOINDEX, NOFOLLOW\"></META>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/images/favicon.png\" type=\"image/ico\"/>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/font-awesome.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.fancybox.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery-ui.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap-datetimepicker.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/error.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/daterangepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/select2.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/mdtimepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/theme.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.dataTables.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/buttons.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("    ");

    String refid=request.getParameter("refid");
    
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                <div class=\"menuDv marg10\">\r\n");
      out.write("                    <div class=\"box-intro\">\r\n");
      out.write("                      <h2><span class=\"title\">Grant/Deny Access Sub-Folder Permission</span></h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <div class=\"clearfix pad_box2\">\r\n");
      out.write("                       <form onsubmit=\"return false;\"  name=\"follow-up-form\"> \r\n");
      out.write("                       <input type=\"hidden\" id=\"FolderId\" value=\"");
      out.print(refid);
      out.write("\"/>                           \r\n");
      out.write("                            <div class=\"clearfix form-group mtop10\">\r\n");
      out.write("                            <label>User Name :<span style=\"color: red;\">*</span></label>\r\n");
      out.write("                            <div class=\"clearfix relative_box\">\r\n");
      out.write("                            <input type=\"text\" id=\"User_Id\" autocomplete=\"off\" name=\"userid\"  class=\"form-control\"  placeholder=\"Enter User Name Minimum 2 Characters\"/>\r\n");
      out.write("                            <input type=\"hidden\" name=\"uid\" id=\"Uid\"/>\r\n");
      out.write("                            <div id=\"useridErr\" class=\"popup_error\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>                           \r\n");
      out.write("                            <div class=\"clearfix item-product-info form-group\">\r\n");
      out.write("                                  <button class=\"bt-link bt-radius bt-loadmore\" type=\"submit\" onclick=\"return validateUser();\">Submit</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                         \r\n");
      out.write("                            <div class=\"menuDv clearfix mb10  footer-bottom2\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                           <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                           <div class=\"clearfix \">\r\n");
      out.write("                           <div class=\"col-xs-1 box-intro-bg\">\r\n");
      out.write("                            <div class=\"box-intro-border\">\r\n");
      out.write("                            <p class=\"news-border\">SN</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"col-xs-9 box-intro-bg\">\r\n");
      out.write("                            <div class=\"box-intro-border\">\r\n");
      out.write("                            <p class=\"news-border\">User Name</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"col-xs-2 box-intro-bg \">\r\n");
      out.write("                            <div class=\"box-intro-border\">\r\n");
      out.write("                            <p class=\"\">Action</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                              ");

                            String token = (String) session.getAttribute("uavalidtokenno");
                            String[][] upermission=TaskMaster_ACT.getAllPermissions(refid,token,"sub-folder");
                            for(int i=0;i<upermission.length;i++){
                            
      out.write("\r\n");
      out.write("                          <div class=\"row\">\r\n");
      out.write("                          <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                          <div class=\"clearfix\">\r\n");
      out.write("                          <div class=\"col-xs-1 box-intro-background\">\r\n");
      out.write("                            <div class=\"link-style12\">\r\n");
      out.write("                            <p class=\"news-border\" title=\"\">");
      out.print(upermission.length-i );
      out.write("</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>  \r\n");
      out.write("                          <div class=\"col-xs-9 box-intro-background\">\r\n");
      out.write("                            <div class=\"link-style12\">\r\n");
      out.write("                            <p class=\"news-border\" title=\"");
      out.print(upermission[i][1]);
      out.write('"');
      out.write('>');
      out.print(upermission[i][1]);
      out.write("</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div> \r\n");
      out.write("                          <div class=\"col-xs-2 box-intro-background\">\r\n");
      out.write("                            <div class=\"link-style12\">\r\n");
      out.write("                            <p class=\"\" title=\"\"><a href=\"\" onclick=\"deletePermission(");
      out.print(upermission[i][0]);
      out.write(")\"><i class=\"fa fa-trash\" title=\"delete\"></i></a></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div> \r\n");
      out.write("                          </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           ");
} 
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                            \r\n");
      out.write("                     </form>\r\n");
      out.write("                   </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.fancybox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/nicEdit.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/globalscript.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/select2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/daterangepicker.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/mdtimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/fontawsome.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/theme.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jszip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/pdfmake.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/vfs_fonts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.html5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.print.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.colVis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready( function () {\r\n");
      out.write("	var role=\"");
      out.print(session.getAttribute("emproleid"));
      out.write("\";\r\n");
      out.write("	$(\".checked\").click(function(){\r\n");
      out.write("		 if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("			 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("	$(\"#CheckAll\").click(function(){\r\n");
      out.write("	$('.checked').prop('checked', this.checked);\r\n");
      out.write("	if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("		 	 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		    \r\n");
      out.write("	});\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write(" $(window).load(function() {\r\n");
      out.write("  $(\".processing_loader\").fadeOut();\r\n");
      out.write("}); \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function showLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeIn(); \r\n");
      out.write("} \r\n");
      out.write("function hideLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeOut();  \r\n");
      out.write("}  \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.timepicker').mdtimepicker();\r\n");
      out.write("function openClock(id){\r\n");
      out.write("$('#'+id).mdtimepicker();\r\n");
      out.write("}\r\n");
      out.write("function openCalendar(id){\r\n");
      out.write("	$(\"#\"+id).datepicker({changeMonth:true,changeYear:true,dateFormat:'yy-mm-dd'});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.has-clear input[type=\"text\"]').on('input propertychange', function() {\r\n");
      out.write("  var $this = $(this);\r\n");
      out.write("  var visible = Boolean($this.val());\r\n");
      out.write("  $this.siblings('.form-control-clear').toggleClass('hidden', !visible);\r\n");
      out.write("}).trigger('propertychange');\r\n");
      out.write("\r\n");
      out.write("$('.form-control-clear').click(function() {\r\n");
      out.write("  $(this).siblings('input[type=\"text\"]').val('')\r\n");
      out.write("    .trigger('propertychange').focus();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goBack() {\r\n");
      out.write("  window.history.back();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function deletePermission(id){\r\n");
      out.write("		if(confirm(\"Warning : Are You Sure Want to delete ?\")){\r\n");
      out.write("		var xhttp;\r\n");
      out.write("		xhttp = new XMLHttpRequest();\r\n");
      out.write("		xhttp.onreadystatechange = function() {\r\n");
      out.write("		if (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("		location.reload();\r\n");
      out.write("		}\r\n");
      out.write("		};\r\n");
      out.write("		xhttp.open(\"GET\", \"");
      out.print(request.getContextPath());
      out.write("/DeletePermission111?info=\"+id, true);\r\n");
      out.write("		xhttp.send();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function validateUser() {		\r\n");
      out.write("	if(document.getElementById(\"User_Id\").value.trim()==\"\" ) {\r\n");
      out.write("		useridErr.innerHTML=\"User Name required.\";\r\n");
      out.write("		useridErr.style.color=\"red\";\r\n");
      out.write("	return false;\r\n");
      out.write("	}else\r\n");
      out.write("		useridErr.innerHTML=\"\";\r\n");
      out.write("	\r\n");
      out.write("	var userId=document.getElementById(\"Uid\").value.trim();	\r\n");
      out.write("	var frefid=document.getElementById(\"FolderId\").value.trim();	\r\n");
      out.write("	var fcategory=\"sub-folder\";\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type: \"POST\",\r\n");
      out.write("		dataType: \"html\",\r\n");
      out.write("		url: \"addFolderPermission111\",\r\n");
      out.write("		data:  {\r\n");
      out.write("			userId: userId,\r\n");
      out.write("			frefid: frefid,\r\n");
      out.write("			fcategory: fcategory\r\n");
      out.write("		},\r\n");
      out.write("		success: function (data) {\r\n");
      out.write("		location.reload();\r\n");
      out.write("		},\r\n");
      out.write("		error: function (error) {\r\n");
      out.write("		alert(\"error in addPermissions() \" + error.responseText);\r\n");
      out.write("		}\r\n");
      out.write("		});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function isExist(value,err){\r\n");
      out.write("	var val=document.getElementById(value).value.trim();\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : \"POST\",\r\n");
      out.write("		url : \"ExistValue111\",\r\n");
      out.write("		dataType : \"HTML\",\r\n");
      out.write("		data : {\r\n");
      out.write("			\"val\" : val,\r\n");
      out.write("			\"field\":\"servicetype\",\r\n");
      out.write("		},\r\n");
      out.write("		success : function(data){\r\n");
      out.write("			if(data==\"pass\"){\r\n");
      out.write("			document.getElementById(err).innerHTML=\"'\"+val +\"'  already existed.\";\r\n");
      out.write("			document.getElementById(err).style.color=\"red\";\r\n");
      out.write("			document.getElementById(value).value=\"\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("	$(\"#User_Id\").autocomplete({\r\n");
      out.write("		source : function(request, response) {\r\n");
      out.write("			document.getElementById(\"useridErr\").innerHTML=\"\";\r\n");
      out.write("			if(document.getElementById('User_Id').value.trim().length>=2)\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"getalluser.html\",\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				dataType : \"JSON\",\r\n");
      out.write("				data : {\r\n");
      out.write("					name : request.term,		\r\n");
      out.write("					refid : \"");
      out.print(refid);
      out.write("\",\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					response($.map(data, function(item) {\r\n");
      out.write("						return {  \r\n");
      out.write("							label : item.uname,	\r\n");
      out.write("							value : item.name,\r\n");
      out.write("							uid : item.uid,												\r\n");
      out.write("						};\r\n");
      out.write("					}));\r\n");
      out.write("				},\r\n");
      out.write("				error : function(error) {\r\n");
      out.write("					alert('error: ' + error.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		},\r\n");
      out.write("		change: function (event, ui) {\r\n");
      out.write("            if(!ui.item){     \r\n");
      out.write("            	document.getElementById(\"useridErr\").innerHTML=\"Select From List.\";\r\n");
      out.write("            	document.getElementById(\"useridErr\").style.color=\"red\";\r\n");
      out.write("            	$(\"#User_Id\").val(\"\");\r\n");
      out.write("            	$(\"#emid\").val(\"\");            	\r\n");
      out.write("            }\r\n");
      out.write("            else{\r\n");
      out.write("            	$(\"#User_Id\").val(ui.item.value);\r\n");
      out.write("            	$(\"#Uid\").val(ui.item.uid);            	\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        error : function(error){\r\n");
      out.write("			alert('error: ' + error.responseText);\r\n");
      out.write("		},\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
