/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hcustfrontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import commons.CommonHelper;
import admin.task.TaskMaster_ACT;
import java.util.Random;
import admin.task.SalesHierarchyVirtual_CTRL;
import client_master.Clientmaster_ACT;
import hcustbackend.ClientACT;
import admin.Login.LoginAction;
import hcustbackend.ClientACT;

public final class client_005forders_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/hcustfrontend/includes/client_header_menu.jsp", Long.valueOf(1672393721511L));
    _jspx_dependants.put("/hcustfrontend/includes/client-footer-js.jsp", Long.valueOf(1670913111283L));
    _jspx_dependants.put("/hcustfrontend/includes/checkvalid_client.jsp", Long.valueOf(1644210750000L));
    _jspx_dependants.put("/hcustfrontend/includes/client-header-css.jsp", Long.valueOf(1644210750000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("hcustbackend.ClientACT");
    _jspx_imports_classes.add("client_master.Clientmaster_ACT");
    _jspx_imports_classes.add("admin.Login.LoginAction");
    _jspx_imports_classes.add("commons.CommonHelper");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("admin.task.SalesHierarchyVirtual_CTRL");
    _jspx_imports_classes.add("admin.task.TaskMaster_ACT");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>  \r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/favicon.png\" type=\"image/ico\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/fakeLoader.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/font.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/media.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/jquery.timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/error.css\">\r\n");
      out.write("<!-- for animation -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/animate.css\">\r\n");
      out.write("<!-- for top scroll -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/material-scrolltop.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/hcustfrontend/fntdcss/daterangepicker.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.dataTables.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/buttons.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.dataTables.min.css\" media=\"all\"/>");
      out.write("\r\n");
      out.write("    <title>corpSeed-orders</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"mySite\" style=\"display: block\">\r\n");
      out.write('\r');
      out.write('\n');

// response.setHeader("Cache-Control","no-cache");  
// response.setHeader("Cache-Control","no-store");  
// response.setDateHeader("Expires", -1);
response.setHeader("Cache-Control", "no-cache");
response.setHeader("Cache-Control", "no-store");
response.setDateHeader("Expires", 0);
response.setHeader("Pragma", "no-cache");

String uavalidtokenno1111= (String)session.getAttribute("uavalidtokenno");
String uaIsValid1= (String)session.getAttribute("loginuID");
if(uaIsValid1== null || uaIsValid1.equals("") || uavalidtokenno1111== null || uavalidtokenno1111.equals("")){

      out.write('\r');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("/login.html");
        return;
      }
      out.write('\r');
      out.write('\n');
}
      out.write('\r');
      out.write('\n');
      out.write(" \r\n");
      out.write("<!-- main content starts -->\r\n");

//get token no from session
String token=(String)session.getAttribute("uavalidtokenno");
String loginuaid = (String) session.getAttribute("loginuaid");
// String userRole=(String)session.getAttribute("userRole");
// if(userRole==null||userRole.length()<=0)userRole="NA";
String doAction=(String)session.getAttribute("ClientOrderDoAction");
if(doAction==null||doAction.length()<=0)doAction="All";
String searchDoAction=(String)session.getAttribute("ClientOrderSearchDoAction");
if(searchDoAction==null||searchDoAction.length()<=0)searchDoAction="NA";
String searchFromToDate=(String)session.getAttribute("searchFromToDate");
if(searchFromToDate==null||searchFromToDate.length()<=0)searchFromToDate="NA";
String sortBy=(String)session.getAttribute("searchOrderSorting");
if(sortBy==null||sortBy.length()<=0)sortBy="desc";
//System.out.println("userRole="+userRole);
// get client no from session
/* String clientrefid=ClientACT.getClientRefId(uaempid,token);  

String client[][]=ClientACT.getClientByNo(clientrefid,token);*/

/* String clientfrom=(String)session.getAttribute("clientfrom");
String clientto=(String)session.getAttribute("clientto");
String include=(String)session.getAttribute("include");
String sortby=(String)session.getAttribute("sortby");	
String sprjno=(String)session.getAttribute("sprjno");
String sprjname=(String)session.getAttribute("sprjname");

// if(sprjno==null||sprjno=="")sprjno="NA";
if(sprjname==null||sprjname=="")sprjname="NA";
if(clientfrom==null||clientfrom=="")clientfrom="NA";
if(clientto==null||clientto=="")clientto="NA";
if(include==null||include=="")include="Yes";
if(sortby==null||sortby=="")sortby="NA"; */

long pageLimit=10;
String pageLimit1=(String)session.getAttribute("orderPageLimit");
if(pageLimit1!=null&&pageLimit1.length()>0)pageLimit=Long.parseLong(pageLimit1);


long pageStart=1;
String pageStart1=(String)session.getAttribute("orderPageStart");
if(pageStart1!=null&&pageStart1.length()>0)pageStart=Long.parseLong(pageStart1);

long pageEnd=10;
String pageEnd1=(String)session.getAttribute("orderPageEnd");
if(pageEnd1!=null&&pageEnd1.length()>0)pageEnd=Long.parseLong(pageEnd1);

long count=pageEnd/pageLimit;

Random randomGenerator = new Random();
long randomInt = randomGenerator.nextInt(100000000);

      out.write("\r\n");
      out.write("<section class=\"main clearfix\">\r\n");
      out.write("  ");
      out.write('\r');
      out.write('\n');
 
String urlpage=request.getParameter("uid");
if(urlpage==null||urlpage.length()<=0)urlpage="NA";
if(!urlpage.equalsIgnoreCase("client_orders.html")){
	//removing client order action
	session.removeAttribute("ClientOrderDoAction");
	session.removeAttribute("ClientOrderSearchDoAction");
	session.removeAttribute("searchFromToDate");
	session.removeAttribute("searchOrderSorting");
	session.removeAttribute("orderPageLimit");
	session.removeAttribute("orderPageStart");
	session.removeAttribute("orderPageEnd");
}if(!urlpage.equalsIgnoreCase("client_inbox.html")){
	//removing client order action
	session.removeAttribute("ClientInboxDoAction");	
}
if(!urlpage.equalsIgnoreCase("client_documents.html")&&!urlpage.contains("viewalldocuments-")){
	//removing client doc action
	session.removeAttribute("doActionDocuments");
	session.removeAttribute("searchFolderDocuments");
	session.removeAttribute("searchFromToDocDate");
	session.removeAttribute("searchDocumentSorting");
	session.removeAttribute("clientDocumentPageLimit");
	session.removeAttribute("clientDocumentPageStart");
	session.removeAttribute("clientDocumentPageEnd");
}
if(!urlpage.contains("viewalldocuments-")){
	//removing client doc action
	session.removeAttribute("documentPageLimit");
	session.removeAttribute("documentPageStart");
	session.removeAttribute("documentPageEnd");
	session.removeAttribute("DocOfClientAgent");
}if(!urlpage.equalsIgnoreCase("all-notifications.html")){
	//removing client order action
	session.removeAttribute("notisearchFromToDate");
}if(!urlpage.equalsIgnoreCase("client_payments.html")){
	//removing client order action
	session.removeAttribute("ClientOrderSearchInvoice");
	session.removeAttribute("PaymentSearchFromToDate");
	session.removeAttribute("PaymentSearchOrderSorting");
	session.removeAttribute("paymentPageLimit");
	session.removeAttribute("paymentPageStart");
	session.removeAttribute("paymentPageEnd");
}
String userRole=(String)session.getAttribute("userRole");
if(userRole==null||userRole.length()<=0)userRole="NA";
String userName=(String)session.getAttribute("loginclname");
if(userName==null||userName.length()<=0)userName="NA";

String profileName=userName.substring(0,1);
if(userName.contains(" "))profileName+=userName.substring(userName.indexOf(" ")+1,userName.indexOf(" ")+2);
else profileName+=userName.substring(1,2); 

      out.write("\r\n");
      out.write("<header class=\"header\"> \r\n");
      out.write("    <div class=\"container-fluid\"> \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-12\"> \r\n");
      out.write("        <div class=\"logo\"> \r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_dashboard.html\" style=\"display: inline-block;\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/logo.png\" alt=\"\"></a>\r\n");
      out.write("        </div>       \r\n");
      out.write("        </div>          \r\n");
      out.write("        <div class=\"col-sm-9 col-12\"> \r\n");
      out.write("         <div class=\"top_menu text-right\">\r\n");
      out.write("          <ul>		  \r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("client_orders.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">            \r\n");
      out.write("            <a class=\"\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_orders.html\"><i class=\"fa fa-archive menu_icon\"></i><span>Your Orders</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("client_inbox.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">            \r\n");
      out.write("            <a class=\"\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_inbox.html\"><i class=\"fas fa-comment-dots menu_icon\" aria-hidden=\"true\"></i><span>Chat</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("client_documents.html")||urlpage.contains("viewalldocuments-")){ 
      out.write(" class=\"active\"");
}
      out.write(">            \r\n");
      out.write("            <a class=\"\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_documents.html\"><i class=\"fa fa-file-alt menu_icon\" aria-hidden=\"true\"></i><span>Doc Wallet</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("client_payments.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">            \r\n");
      out.write("            <a class=\"\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_payments.html\"><i class=\"fas fa-money-check menu_icon\" aria-hidden=\"true\"></i><span>Payments</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("my_profile.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("          <a class=\"setting\"  href=\"javascript:void(0)\"><i class=\"fas fa-user menu_icon\" aria-hidden=\"true\"></i><span>Profile</span></a>  \r\n");
      out.write("        <ul class=\"sub-menu\">\r\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_dashboard.html\">Dashboard</a></li>\r\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/my_profile.html\">My Profile</a></li>\r\n");
      out.write("\r\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.html\">LogOut</a></li> \r\n");
      out.write("		  </ul> \r\n");
      out.write("          </li>\r\n");
      out.write("          ");

          String clientloginuaid = (String) session.getAttribute("loginClintUaid");  
          
          String notificationtoken=(String)session.getAttribute("uavalidtokenno");          
          int notification=ClientACT.getTotalUnseenNotification(notificationtoken,clientloginuaid); 
          String notifications[][]=ClientACT.getAllClientNotification(notificationtoken,clientloginuaid);
          
      out.write("\r\n");
      out.write("          <li> \r\n");
      out.write("          \r\n");
      out.write("            <a href=\"javascript:void(0)\" class=\"notification\" onclick=\"markAllAsReadNotification('");
      out.print(notification);
      out.write("')\"><i class=\"far fa-bell \">");
if(notification>0){ 
      out.write("<span id=\"totalNotification\">");
      out.print(notification);
      out.write("</span>");
} 
      out.write("</i></a>\r\n");
      out.write("             <a href=\"");
      out.print(request.getContextPath() );
      out.write("/all-notifications.html\" class=\"notification_mobile\" onclick=\"markAllAsReadNotification('");
      out.print(notification);
      out.write("')\"><i class=\"fa fa-bell \">");
if(notification>0){ 
      out.write("<small>");
      out.print(notification);
      out.write("</small>");
} 
      out.write("</i><span  id=\"totalNotification_mobile\">Notification</span></a>\r\n");
      out.write("            <div class=\"notification_box pullDown\">                            \r\n");
      out.write("			  <ul>\r\n");
      out.write("			  ");
if(notifications!=null&&notifications.length>0){
				  for(int i=0;i<notifications.length;i++){
				  
      out.write("             \r\n");
      out.write("              <li class=\"clearfix\">\r\n");
      out.write("                <a href=\"javascript:void(0)\" onclick=\"markAsReadNotification('");
      out.print(notifications[i][2] );
      out.write("')\">                \r\n");
      out.write("                <div class=\"clearfix pro_box text-left\">\r\n");
      out.write("                    <div class=\"clearfix icon_box\">\r\n");
      out.write("                     <i class=\"");
      out.print(notifications[i][4] );
      out.write(" icon-circle\" aria-hidden=\"true\"></i>\r\n");
      out.write("                    </div> \r\n");
      out.write("                    <div class=\"clearfix pro_info\"> \r\n");
      out.write("                    <h6>");
      out.print(notifications[i][3] );
      out.write("</h6>\r\n");
      out.write("                    <div class=\"clearfix date_box\">");
      out.print(notifications[i][1] );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </div>                 \r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              ");
}}else{ 
      out.write("\r\n");
      out.write("              <div class=\"text-center text-muted\">No data found !!</div>\r\n");
      out.write("              ");
} 
      out.write("\r\n");
      out.write("			  </ul> \r\n");
      out.write("			  <div class=\"text-center\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/all-notifications.html\">View All &nbsp;<i class=\"fa fa-angle-right\"></i></a></div>             \r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("<a href=\"#\" class=\"backbtnn\"><i class=\"fa fa-arrow-left\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("<div class=\"user_prof\">\r\n");
      out.write("<div class=\"user_thumb\"> \r\n");
      out.write("<h3>");
      out.print(userName );
      out.write("</h3>\r\n");
      out.write("<figure> <span class=\"prof_name\">");
      out.print(profileName );
      out.write("</span> </figure>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"user_detail\">\r\n");
      out.write("<div class=\"clearfix\"> \r\n");
      out.write("<a href=\"#\" data-toggle=\"modal\" data-target=\"#updatepass\">Update Password</a>\r\n");
      out.write("<!--  <span>Noida, India</span>   -->\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"top_menu menu_notification\">\r\n");
      out.write(" <ul>\r\n");
      out.write("<span>Settings</span>\r\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/my_profile.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/profile.svg\" alt=\"\">My Profile</a></li>\r\n");
      out.write("\r\n");
      out.write("<li id=\"client_payments\">           \r\n");
      out.write("  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_payments.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/payment.svg\" alt=\"\">Payments</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/all-notifications.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/bell.svg\" alt=\"\">Notification</a></li>\r\n");
      out.write(" </ul></div>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.html\" class=\"logoutbtnn\"> Logout</a>\r\n");
      out.write("</div>");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("  <section class=\"main-order clearfix\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-12 p-0\">\r\n");
      out.write("       \r\n");
      out.write("          <div class=\"shadow_none box_bg box-orders\">\r\n");
      out.write("          <div class=\"clearfix document_page\"> \r\n");
      out.write("		  \r\n");
      out.write("		  <div class=\"row mbt12 sticky_top\">\r\n");
      out.write("		  \r\n");
      out.write("		  <div class=\"col-lg-6 col-md-6 col-sm-12 col-12 order\">\r\n");
      out.write("		  <ul class=\"clearfix filter_menu pointers\">\r\n");
      out.write("			<li onclick=\"doAction('All','ClientOrderDoAction')\" ");
if(doAction.equalsIgnoreCase("All")){ 
      out.write("class=\"active\"");
} 
      out.write("><a>All</a></li> \r\n");
      out.write("			<li onclick=\"doAction('In Progress','ClientOrderDoAction')\" ");
if(doAction.equalsIgnoreCase("In Progress")){ 
      out.write("class=\"active\"");
} 
      out.write("><a>In Progress</a></li>\r\n");
      out.write("			<li onclick=\"doAction('Completed','ClientOrderDoAction')\" ");
if(doAction.equalsIgnoreCase("Completed")){ 
      out.write("class=\"active\"");
} 
      out.write("><a>Completed</a></li>  \r\n");
      out.write("		  </ul>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  <div class=\"col-lg-6 col-md-6 col-sm-12 col-12\">\r\n");
      out.write("          <div class=\"form-group-orders\"> \r\n");
      out.write("              <div class=\"m_width80 inbox_input\" ");
if(!searchDoAction.equalsIgnoreCase("NA")){ 
      out.write("style=\"display: block;\"");
} 
      out.write(">\r\n");
      out.write("              <input class=\"form-control-search\" id=\"SearchOrder\" ");
if(!searchDoAction.equalsIgnoreCase("NA")){ 
      out.write("value=\"");
      out.print(searchDoAction);
      out.write('"');
} 
      out.write(" type=\"search\" onsearch=\"removeSearchOption('ClientOrderSearchDoAction')\" placeholder=\"Search\"> \r\n");
      out.write("              <i class=\"fa fa-search\" aria-hidden=\"true\"></i>  			\r\n");
      out.write("			  </div>\r\n");
      out.write("			  <i class=\"fas fa-long-arrow-alt-left\" id=\"backico\" ");
if(!searchDoAction.equalsIgnoreCase("NA")){ 
      out.write("style=\"display: block;\"");
} 
      out.write("></i>			  \r\n");
      out.write("			  <div class=\"inbox-chatlist\"> \r\n");
      out.write("			  <button type=\"button\" id=\"search\" ");
if(sortBy.equalsIgnoreCase("desc")){ 
      out.write(" onClick=\"doAction('asc','searchOrderSorting')\"");
}else{ 
      out.write("onClick=\"doAction('desc','searchOrderSorting')\"");
} 
      out.write("><i class=\"fa fa-list icon-circle\" title=\"Sort By\"></i></button> \r\n");
      out.write("              <button class=\"calendar_box\" type=\"button\" title=\"Search by date\"><i class=\"fa fa-calendar-times icon-circle\"></i>\r\n");
      out.write("			  <input type=\"text\" class=\"form-control\" ");
if(!searchFromToDate.equalsIgnoreCase("NA")){ 
      out.write("value=\"");
      out.print(searchFromToDate );
      out.write('"');
} 
      out.write(" name=\"date_range\" id=\"date_range\" readonly=\"readonly\"/>\r\n");
      out.write("			  </button>\r\n");
      out.write("			  ");
if(!searchFromToDate.equalsIgnoreCase("NA")){ 
      out.write("\r\n");
      out.write("			  <button type=\"button\" title=\"Clear date\" style=\"position: absolute;right: -41px;\" onclick=\"removeSearchOption('searchFromToDate')\"><i class=\"fas fa-times icon-circle\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("			  ");
} 
      out.write("</div>\r\n");
      out.write("			  \r\n");
      out.write("		  </div> \r\n");
      out.write("		  \r\n");
      out.write("		  	<a href=\"javascript:void(0)\" class=\"mobilesearchico\"> <i class=\"fa fa-search \" aria-hidden=\"true\"></i> </a>\r\n");
      out.write("			<div class=\"pageheading\">\r\n");
      out.write("          <h2>Order</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("			 \r\n");
      out.write("		  </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  \r\n");
      out.write("<!-- 1st box starts -->\r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-12 bg_whitee\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-12 page-max\">\r\n");
      out.write("            ");

			String projects[][]=ClientACT.getAllProjectsById(loginuaid,token,doAction,searchDoAction,searchFromToDate,sortBy,pageLimit,pageStart,userRole);     
            if(projects!=null&&projects.length>0){
            	for(int i=0;i<projects.length;i++){
//             		int milestoneQty=ClientACT.getTotalMilestones(projects[i][0],token); 
//             		int milestoneWorkPercentage=ClientACT.getMilestonesWorkPercentage(projects[i][0],token);
//             		int workPercentage=milestoneWorkPercentage/milestoneQty;
            		double totalPrice=ClientACT.getProjectsTotalPrice(projects[i][0],token);
            		double dueAmount=ClientACT.getDueAmount(projects[i][3],token);
            		String bg_color="";
            		if(projects[i][16].equalsIgnoreCase("Inactive"))bg_color="bg-danger";
			
      out.write("\r\n");
      out.write("              <div class=\"order-progress-box\">\r\n");
      out.write("                <div class=\"row order_view pointers\">\r\n");
      out.write("                  <div class=\"col-md-5 col-sm-5 col-12 p-0\">\r\n");
      out.write("                    <div class=\"order-details\">\r\n");
      out.write("                      <p><strong>Order No.:</strong> <a class=\"pointers\">");
      out.print(projects[i][2] );
      out.write("</a></p>              \r\n");
      out.write("                      <p><span>");
      out.print(projects[i][7] );
      out.write("</span></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-4 col-sm-4 col-12\">\r\n");
      out.write("                    <!-- Progress bar 1 -->\r\n");
      out.write("                    <div class=\"progress clearfix mt-3\">");
if(projects[i][17].equals("1")){ 
      out.write("\r\n");
      out.write("                      <div class=\"progress-bar\" style=\"width:");
      out.print(projects[i][13]);
      out.write('%');
      out.write('"');
      out.write('>');
      out.print(projects[i][13]);
      out.write(" %</div>");
}else{ 
      out.write("\r\n");
      out.write("                      <div class=\"progress-bar\" style=\"width:100%\">Consulting Service</div>");
} 
      out.write("\r\n");
      out.write("                    </div>					\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-3 col-sm-3 col-12\">\r\n");
      out.write("                    <div class=\"edit-orders\"> \r\n");
      out.write("                      <a class=\"locks\" onclick=\"openCertificates('");
      out.print(projects[i][0] );
      out.write("')\"><i class=\"fas fa-file-alt\" title=\"Certificates\"></i></a>\r\n");
      out.write("                      <a class=\"comments\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_inbox.html?skey=");
      out.print(projects[i][0] );
      out.write("&pno=");
      out.print(projects[i][2] );
      out.write("&pname=");
      out.print(projects[i][7] );
      out.write("&cdate=");
      out.print(projects[i][15] );
      out.write("\" title=\"Open Chat\"><i class=\"far fa-comment-alt\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("					\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mobileeditbtn\">\r\n");
      out.write("					<a href=\"javascript:void(0)\" class=\"docbtn\" onclick=\"openCertificates('");
      out.print(projects[i][0] );
      out.write("')\">Doc</a>\r\n");
      out.write("					<a class=\"chatbtn\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_inbox.html?skey=");
      out.print(projects[i][0] );
      out.write("&pno=");
      out.print(projects[i][2] );
      out.write("&pname=");
      out.print(projects[i][7] );
      out.write("&cdate=");
      out.print(projects[i][15] );
      out.write("\">Chat</a>\r\n");
      out.write("						<button class=\"exapandarrow\"><i class=\"fa fa-angle-down\"></i></button>\r\n");
      out.write("					</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("				<div class=\"clearfix\" style=\"display:none;\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("				  <div class=\"col-md-12 col-sm-12 col-12\">\r\n");
      out.write("                    <div class=\"order_details\">\r\n");
      out.write("                      <p>\r\n");
      out.write("					  <span><i class=\"fas fa-clipboard-check\"></i><span>Sales order created on ");
      out.print(projects[i][12] );
      out.write(" !!</span></span> \r\n");
      out.write("                      <span></span>\r\n");
      out.write("					  </p>\r\n");
      out.write("					  <p>\r\n");
      out.write("					  <span><i class=\"fas fa-clipboard-check\"></i><span>Payment added on ");
      out.print(projects[i][12] );
      out.write(" !!</span></span>\r\n");
      out.write("                      <span></span>\r\n");
      out.write("					  </p>\r\n");
      out.write("					  ");
if(projects[i][13].equals("100")){ 
      out.write("\r\n");
      out.write("					  <p>\r\n");
      out.write("					  <span><i class=\"fas fa-clipboard-check\"></i><span>");
      out.print(projects[i][2] );
      out.write(" Successfully completed !!</span></span>\r\n");
      out.write("                      <span></span> \r\n");
      out.write("					  </p>");
} 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("				  <div class=\"col-md-6 col-sm-6 col-12\">  \r\n");
      out.write("                    <div class=\"order-date\">\r\n");
      out.write("                      <p>");
if(projects[i][17].equals("1")){ 
      out.write("\r\n");
      out.write("					  <span><strong>Status:</strong> <a class=\"pointers status_view ");
      out.print(bg_color);
      out.write('"');
      out.write('>');
      out.print(projects[i][16] );
      out.write("</a></span>\r\n");
      out.write("					  ");
}if(dueAmount>0){ 
      out.write("\r\n");
      out.write("					  <span><strong>Payment:</strong> <a class=\"pointers payment_view\" data-toggle=\"modal\" data-target=\"#paymentModal\" onclick=\"setSalesKey('");
      out.print(projects[i][0] );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(dueAmount);
      out.write("')\"><i></i></a></span>\r\n");
      out.write("					 ");
} 
      out.write("\r\n");
      out.write("					  </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("				  <div class=\"col-md-6 col-sm-6 col-12\">\r\n");
      out.write("				  <div class=\"order_amount text-right\">\r\n");
      out.write("				    <p><strong>Total Amount:</strong><span class=\"amount\" title=\"");
      out.print(totalPrice);
      out.write("\"><strong class=\"pl-4\"><i class=\"fa fa-inr\"></i> ");
      out.print(CommonHelper.withLargeIntegers(totalPrice) );
      out.write("</strong></span></p> \r\n");
      out.write("				  </div>\r\n");
      out.write("				  </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("              </div>\r\n");
      out.write("              ");
}}else{ 
      out.write("\r\n");
      out.write("              <div class=\"clearfix text-center text-danger noDataFound\">\r\n");
      out.write("              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/nodata.png\" alt=\"\">\r\n");
      out.write("              <p>Your orders are under progress !!</p></div>\r\n");
      out.write("              ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-12 row page-range\">\r\n");
      out.write("            <div class=\"col-md-9\"></div>\r\n");
      out.write("            <div class=\"col-md-1 col-md-offset-9\">\r\n");
      out.write("				<select name=\"pageShow\" id=\"PageShow\"");
if(projects.length>=10){ 
      out.write(" onchange=\"pageLimit(this.value)\"");
} 
      out.write(">\r\n");
      out.write("				    <option value=\"10\" ");
if(pageLimit==10){ 
      out.write("selected");
} 
      out.write(">10</option>\r\n");
      out.write("				    <option value=\"20\" ");
if(pageLimit==20){ 
      out.write("selected");
} 
      out.write(">20</option>\r\n");
      out.write("				    <option value=\"40\" ");
if(pageLimit==40){ 
      out.write("selected");
} 
      out.write(">40</option>\r\n");
      out.write("				    <option value=\"80\" ");
if(pageLimit==80){ 
      out.write("selected");
} 
      out.write(">80</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("		    <div class=\"col-md-2 text-center\">\r\n");
      out.write("		    <i class=\"fas fa-chevron-left pointers\" ");
if(pageStart>1){ 
      out.write("onclick=\"backwardPage()\"");
} 
      out.write("></i><span>");
      out.print(pageStart );
      out.write('-');
      out.print(pageEnd );
      out.write("</span><i class=\"fas fa-chevron-right pointers\" ");
if(projects!=null&&projects.length>=pageLimit){ 
      out.write("onclick=\"forwardPage()\"");
} 
      out.write("></i>\r\n");
      out.write("		    </div>\r\n");
      out.write("			  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("<!-- 1ST box end -->\r\n");
      out.write("    \r\n");
      out.write("	  </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- main content ends -->\r\n");
      out.write("\r\n");
      out.write("<!-- Payment Modal -->\r\n");
      out.write("  <div class=\"myModal modal fade\" id=\"paymentModal\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\"><i class=\"fa fa-credit-card\" aria-hidden=\"true\"></i>+Add Payments</h4>  \r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"payment.html\" target=\"_blank\" method=\"post\">\r\n");
      out.write("        <div class=\"modal-body\">        \r\n");
      out.write("          <ul class=\"payment_tab nav nav-tabs\">\r\n");
      out.write("		  <li><a data-toggle=\"tab\" href=\"#pay_method3\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/paytm.png\" alt=\"\"></a></li>\r\n");
      out.write("		  </ul>\r\n");
      out.write("		  <div class=\"tab-content\">\r\n");
      out.write("		  \r\n");
      out.write("		  <div id=\"pay_method3\" class=\"tab-pane fade show active\">\r\n");
      out.write("		  <div class=\"row\">\r\n");
      out.write("            <div class=\"form-group-payment col-md-8 col-sm-7 col-12\">\r\n");
      out.write("			<label>Mobile No.</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"MOBILE_NO\" id=\"Mobile No.\" required=\"required\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group-payment col-md-4 col-sm-5 col-12\">\r\n");
      out.write("			<label>Amount</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"TXN_AMOUNT\" id=\"Amount\" required=\"required\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"hidden\" id=\"ORDER_ID\" name=\"ORDER_ID\" value=\"ORDS_");
      out.print( randomInt );
      out.write("\">\r\n");
      out.write("		  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("		  </div>  		  \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"submit\" class=\"btn btn-success\">Confirm Payment</button> \r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- End Payment Modal -->\r\n");
      out.write("\r\n");
      out.write("<footer class=\"clearfix\">\r\n");
      out.write("<div class=\"rights\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("<div class=\"copyright\">\r\n");
      out.write("<p>Copyright &copy;2021 Corpseed ITES Pvt Ltd - All rights reserved.</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<div class=\"footer_menu menu_notification\">\r\n");
String urlpage1=request.getParameter("uid");
if(urlpage1==null||urlpage1.length()<=0)urlpage1="NA"; 
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("<li id=\"client_orders\"");
if(urlpage1.equalsIgnoreCase("client_orders.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("<small></small>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_orders.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/all_orders.svg\" alt=\"\"><span>Your Orders</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("<li id=\"client_inbox\"");
if(urlpage1.equalsIgnoreCase("client_inbox.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("<small></small>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_inbox.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/chat.svg\" alt=\"\"><span>Chat</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_dashboard.html\" class=\"footer_logo\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/footer_logo1.png\" alt=\"\"></a>\r\n");
      out.write("</li>\r\n");
      out.write("<li id=\"client_documents\"");
if(urlpage1.equalsIgnoreCase("client_documents.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("<small></small>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_documents.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/document.svg\" alt=\"\"><span>Doc Wallet</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("<li id=\"my_profile\"");
if(urlpage1.equalsIgnoreCase("my_profile.html")||urlpage1.equalsIgnoreCase("client_payments.html")||urlpage1.equalsIgnoreCase("all-notifications.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("<small></small>\r\n");
      out.write("<a class=\"setting mtoggle\" href=\"javascript:void(0)\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/profile.svg\" alt=\"\"><span>Profile</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Update password Modal -->\r\n");
      out.write("  <div class=\"myModal modal fade\" id=\"updatepass\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\"><i class=\"fas fa-lock\"></i>Change Password</h4>  \r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("		 <form action=\"javascript:void(0)\">\r\n");
      out.write("		  <div class=\"row\">\r\n");
      out.write("            <div class=\"form-group-pass col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<label>Current Password</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" name=\"cpassword\" id=\"Current_password\"  placeholder=\"Enter Current Password*\" required=\"required\">\r\n");
      out.write("            </div>           \r\n");
      out.write("		  </div> \r\n");
      out.write("		   <div class=\"row\">\r\n");
      out.write("            <div class=\"form-group-pass col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<label>New Password</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" name=\"npassword\" id=\"New_Password\" placeholder=\"Enter New Password*\" required=\"required\">\r\n");
      out.write("            <span class=\"show_psw active\" onclick=\"myFunction('New_Password')\">\r\n");
      out.write("									<i class=\"fa fa-eye-slash\" style=\"font-size:15px;color:#006080\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("		  </div> \r\n");
      out.write("		   <div class=\"row\">\r\n");
      out.write("            <div class=\"form-group-pass col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<label>Confirm Password</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" name=\"cfpassword\" id=\"Confirm_Password\" placeholder=\"Re-enter New Password*\" required=\"required\">\r\n");
      out.write("            <span class=\"show_psw active\" onclick=\"myFunction('Confirm_Password')\">\r\n");
      out.write("			<i class=\"fa fa-eye-slash\" style=\"font-size:15px;color:#006080\"></i>\r\n");
      out.write("			</span>\r\n");
      out.write("            </div>           \r\n");
      out.write("		  </div> \r\n");
      out.write("		  </form>\r\n");
      out.write("          </div>\r\n");
      out.write("		 \r\n");
      out.write("        <div class=\"modal-footer justify-content-end\">\r\n");
      out.write("          <button type=\"submit\" class=\"btn btn-success\" onclick=\"return validatePassword()\" id=\"Update_Password\">Update Password</button> \r\n");
      out.write("          <button type=\"button\" class=\"btn btn-outline-secondary\" data-dismiss=\"modal\">Cancel</button> \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- End Update password Modal -->\r\n");
      out.write("<div class=\"alert-show\" style=\"display: none;\"><div class=\"alert-bg alert-striped\" id=\"errorMsg\"></div></div>\r\n");
      out.write("<div class=\"alert-show1\" style=\"display: none;\"><div class=\"alert-bg1 alert-striped\" id=\"errorMsg1\"></div></div>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/5b8cdab0e6.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/fakeLoader.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/wow.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/datepicker.js\"></script>\r\n");
      out.write("<div class=\"processing_loader\" style=\"display: none;\"><div class=\"spin_box\"></div></div>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/jquery.timepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/hcustfrontend/fntdjs/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/hcustfrontend/fntdjs/daterangepicker.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/custom.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/fontawsome.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/globalscript.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jszip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/pdfmake.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/vfs_fonts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.html5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.print.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.colVis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("if(window.history.replaceState){\r\n");
      out.write("window.history.replaceState( null, null, window.location.href );\r\n");
      out.write("}\r\n");
      out.write("new WOW().init();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(window).load(function() {\r\n");
      out.write("	  $(\".processing_loader\").fadeOut();\r\n");
      out.write("	});\r\n");
      out.write("function showLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeIn(); \r\n");
      out.write("}\r\n");
      out.write("function hideLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeOut();  \r\n");
      out.write("}  \r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$('.order_view').click(function(){\r\n");
      out.write("    $(this).next().slideToggle();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/jquery.circlechart.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function setSalesKey(data,due){\r\n");
      out.write("	$(\"#Amount\").val(due);\r\n");
      out.write("	$.ajax({\r\n");
      out.write("	    type: \"POST\",\r\n");
      out.write("	    url: \"");
      out.print(request.getContextPath());
      out.write("/SetOrderTypeSearch999\",\r\n");
      out.write("	    data:  { \r\n");
      out.write("	    	data : data,\r\n");
      out.write("	    	name : \"SalesKey\"\r\n");
      out.write("	    },\r\n");
      out.write("	    success: function (response) {  \r\n");
      out.write("        },\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("function removeSearchOption(data){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("		    type: \"POST\",\r\n");
      out.write("		    url: \"");
      out.print(request.getContextPath());
      out.write("/ClearOrderTypeSearch999\",\r\n");
      out.write("		    data:  { \r\n");
      out.write("		    	data : data\r\n");
      out.write("		    },\r\n");
      out.write("		    success: function (response) {        	  \r\n");
      out.write("	         location.reload(true);\r\n");
      out.write("	        },\r\n");
      out.write("		});	\r\n");
      out.write("}\r\n");
      out.write("function doAction(data,name){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("	    type: \"POST\",\r\n");
      out.write("	    url: \"");
      out.print(request.getContextPath());
      out.write("/SetOrderTypeSearch999\",\r\n");
      out.write("	    data:  { \r\n");
      out.write("	    	data : data,\r\n");
      out.write("	    	name : name\r\n");
      out.write("	    },\r\n");
      out.write("	    success: function (response) {        	  \r\n");
      out.write("         location.reload();\r\n");
      out.write("        },\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// function openChatBox(salesKey,projectNo,projectName,closeDate){\r\n");
      out.write("// 	$.ajax({\r\n");
      out.write("// 	    type: \"POST\",\r\n");
      out.write("\r\n");
      out.write("// 	    data:  { \r\n");
      out.write("// 	    	salesKey : salesKey,\r\n");
      out.write("// 	    	projectNo : projectNo,\r\n");
      out.write("// 	    	projectName : projectName,\r\n");
      out.write("// 	    	closeDate : closeDate,\r\n");
      out.write("// 	    	\"status\" : \"1\"\r\n");
      out.write("// 	    },\r\n");
      out.write("// 	    success: function (response) {        	  \r\n");
      out.write("\r\n");
      out.write("//         },\r\n");
      out.write("// 	});\r\n");
      out.write("// }\r\n");
      out.write("// function workInProgress(){\r\n");
      out.write("// 	document.getElementById('errorMsg').innerHTML =\"Work is in progress,After completing you may download your certificate...!\";	        		  \r\n");
      out.write("// 	  $('.alert-show').show().delay(4000).fadeOut();	\r\n");
      out.write("// }\r\n");
      out.write("function openCertificates(salesKey){	\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : \"POST\",\r\n");
      out.write("		url : \"documentUploadBy999\",\r\n");
      out.write("		dataType : \"HTML\",\r\n");
      out.write("		data : {\r\n");
      out.write("			data : \"Agent\",\r\n");
      out.write("		},\r\n");
      out.write("		success : function(response){\r\n");
      out.write("			window.location=\"");
      out.print(request.getContextPath());
      out.write("/viewalldocuments-\"+salesKey+\".html\";					\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("	$(\"#SearchOrder,#SearchOrder1\").autocomplete({\r\n");
      out.write("		source : function(request, response) {			\r\n");
      out.write("			if($('#SearchOrder').val().trim().length>=2||$('#SearchOrder1').val().trim().length>=2)\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"getprojectdetails.html\",\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				dataType : \"JSON\",\r\n");
      out.write("				data : {\r\n");
      out.write("					name : request.term,\r\n");
      out.write("					loginuaid : \"");
      out.print(loginuaid);
      out.write("\"\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					response($.map(data, function(item) {\r\n");
      out.write("						return {  \r\n");
      out.write("							label : item.name,\r\n");
      out.write("							value : item.value,	\r\n");
      out.write("							projectNo :item.projectNo,\r\n");
      out.write("						};\r\n");
      out.write("					}));\r\n");
      out.write("				},\r\n");
      out.write("				error : function(error) {\r\n");
      out.write("					alert('error: ' + error.responseText);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		},\r\n");
      out.write("		select: function (event, ui) {\r\n");
      out.write("			if(!ui.item){   \r\n");
      out.write("            	\r\n");
      out.write("            }\r\n");
      out.write("            else{\r\n");
      out.write("            	doAction(ui.item.value,'ClientOrderSearchDoAction');\r\n");
      out.write("            }\r\n");
      out.write("        },\r\n");
      out.write("        error : function(error){\r\n");
      out.write("			alert('error: ' + error.responseText);\r\n");
      out.write("		},\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("function sortBy(){\r\n");
      out.write("	var clientfrom=document.getElementById(\"ClientFrom\").value.trim();\r\n");
      out.write("	var clientto=document.getElementById(\"ClientTo\").value.trim();\r\n");
      out.write("	if(clientfrom==\"\") clientfrom=\"NA\";\r\n");
      out.write("	if(clientto==\"\")clientto=\"NA\";\r\n");
      out.write("	var include=\"No\";\r\n");
      out.write("	var searchorder=document.getElementById(\"SearchOrder\").value.trim();\r\n");
      out.write("	var sprjno=\"NA\";\r\n");
      out.write("	var sprjname=\"NA\";\r\n");
      out.write("	if(searchorder!=\"\"){\r\n");
      out.write("		var x=searchorder.split(\"#\");\r\n");
      out.write("		sprjno=x[0];\r\n");
      out.write("		sprjname=x[1];\r\n");
      out.write("	}\r\n");
      out.write("	if(document.getElementById('gridCheck').checked)include=\"Yes\";\r\n");
      out.write("	var sortby=document.getElementById(\"SortedBy\").value.trim();\r\n");
      out.write("	\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"ManageClientOrderCTRL.html\",\r\n");
      out.write("			dataType : \"HTML\",\r\n");
      out.write("			data : {\r\n");
      out.write("				clientfrom : clientfrom,\r\n");
      out.write("				clientto : clientto,\r\n");
      out.write("				include : include,\r\n");
      out.write("				sortby : sortby,\r\n");
      out.write("				sprjno : sprjno,\r\n");
      out.write("				sprjname : sprjname,\r\n");
      out.write("			},\r\n");
      out.write("			success : function(data){\r\n");
      out.write("				location.reload();					\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("}\r\n");
      out.write("function restSearch(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : \"GET\",\r\n");
      out.write("		url : \"ManageClientOrderCTRL.html\",\r\n");
      out.write("		dataType : \"HTML\",\r\n");
      out.write("		data : {\r\n");
      out.write("			reset : \"reset\",\r\n");
      out.write("		},\r\n");
      out.write("		success : function(data){\r\n");
      out.write("			location.reload();					\r\n");
      out.write("		}\r\n");
      out.write("	});	\r\n");
      out.write("}\r\n");
      out.write("function setDtaeFromTo(){	\r\n");
      out.write("	if(document.getElementById(\"ClientFrom\").value.trim()==\"\"){\r\n");
      out.write("		document.getElementById('errorMsg').innerHTML = 'Select Start Date First.';\r\n");
      out.write("		document.getElementById(\"ClientTo\").value=\"\";\r\n");
      out.write("		$('.alert-show').show().delay(2000).fadeOut();		\r\n");
      out.write("	}else{\r\n");
      out.write("		var clientfrom=document.getElementById(\"ClientFrom\").value.trim();\r\n");
      out.write("		var clientto=document.getElementById(\"ClientTo\").value.trim();		\r\n");
      out.write("		if(clientfrom==\"\") clientfrom=\"NA\";\r\n");
      out.write("		if(clientto==\"\")clientto=\"NA\";\r\n");
      out.write("		\r\n");
      out.write("		var searchorder=document.getElementById(\"SearchOrder\").value.trim();\r\n");
      out.write("		var sprjno=\"NA\";\r\n");
      out.write("		var sprjname=\"NA\";\r\n");
      out.write("		if(searchorder!=\"\"){\r\n");
      out.write("			var x=searchorder.split(\"#\");\r\n");
      out.write("			sprjno=x[0];\r\n");
      out.write("			sprjname=x[1];\r\n");
      out.write("		}\r\n");
      out.write("		var clientto=document.getElementById(\"ClientTo\").value.trim();\r\n");
      out.write("		\r\n");
      out.write("		var include=\"No\";\r\n");
      out.write("		if(document.getElementById('gridCheck').checked)include=\"Yes\";\r\n");
      out.write("		var sortby=document.getElementById(\"SortedBy\").value.trim();\r\n");
      out.write("		\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				url : \"ManageClientOrderCTRL.html\",\r\n");
      out.write("				dataType : \"HTML\",\r\n");
      out.write("				data : {\r\n");
      out.write("					clientfrom : clientfrom,\r\n");
      out.write("					clientto : clientto,\r\n");
      out.write("					include : include,\r\n");
      out.write("					sortby : sortby,\r\n");
      out.write("					sprjno : sprjno,\r\n");
      out.write("					sprjname : sprjname,\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data){\r\n");
      out.write("					location.reload();					\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('input[name=\"date_range\"]').daterangepicker({\r\n");
      out.write("	autoApply: true,\r\n");
      out.write("	locale: {\r\n");
      out.write("      format: 'DD-MM-YYYY' \r\n");
      out.write("    }  \r\n");
      out.write("});\r\n");
      out.write("$('#date_range').on('apply.daterangepicker', function(ev, picker) {\r\n");
      out.write("	var date=$(\"#date_range\").val();\r\n");
      out.write("    doAction(date,'searchFromToDate');\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$('.progress_bar').percentcircle({\r\n");
      out.write("animate : true,\r\n");
      out.write("diameter : 10,\r\n");
      out.write("guage: 15,\r\n");
      out.write("coverBg: '#fff',\r\n");
      out.write("bgColor: '#efefef',\r\n");
      out.write("fillColor: '#007bff',\r\n");
      out.write("percentSize: '20px',\r\n");
      out.write("percentWeight: 'normal'\r\n");
      out.write("});	\r\n");
      out.write("\r\n");
      out.write("function pageLimit(data){\r\n");
      out.write("	  var start=\"");
      out.print(pageStart);
      out.write("\";\r\n");
      out.write("	  var limit=\"");
      out.print(pageLimit);
      out.write("\";\r\n");
      out.write("	  var end=Number(start)+Number(data);\r\n");
      out.write("	  if(Number(start)==1)end-=1;\r\n");
      out.write("	  doAction(data,'orderPageLimit');\r\n");
      out.write("	  doAction(end,'orderPageEnd');\r\n");
      out.write("	  location.reload(true);\r\n");
      out.write("}\r\n");
      out.write("function backwardPage(){\r\n");
      out.write("		 var count=\"");
      out.print(count-1);
      out.write("\";\r\n");
      out.write("		 var limit=\"");
      out.print(pageLimit);
      out.write("\";\r\n");
      out.write("		 var start=0;\r\n");
      out.write("		 if(Number(count)>=1){			 \r\n");
      out.write("			 start=(Number(count)-1)*Number(limit);\r\n");
      out.write("			 if(start==0)start=1;\r\n");
      out.write("			 var end=Number(count)*Number(limit);			 \r\n");
      out.write("		 }else if(count==0){\r\n");
      out.write("			 start=1;\r\n");
      out.write("			 end=limit;\r\n");
      out.write("		 }\r\n");
      out.write("		 doAction(start,'orderPageStart');\r\n");
      out.write("		 doAction(end,'orderPageEnd');\r\n");
      out.write("		 location.reload(true);\r\n");
      out.write("	 }\r\n");
      out.write("function forwardPage(){  \r\n");
      out.write("	 var count=\"");
      out.print(count+1);
      out.write("\";\r\n");
      out.write("	 var limit=\"");
      out.print(pageLimit);
      out.write("\";\r\n");
      out.write("	 var start=(Number(count)-1)*Number(limit);\r\n");
      out.write("	 var end=Number(count)*Number(limit);\r\n");
      out.write("	 doAction(start,'orderPageStart');\r\n");
      out.write("	 doAction(end,'orderPageEnd');\r\n");
      out.write("	 location.reload(true);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("<!-- body ends -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
