/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hcustfrontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import commons.CommonHelper;
import java.util.Random;
import commons.AzureBlob;
import com.azure.storage.blob.BlobClientBuilder;
import admin.enquiry.Enquiry_ACT;
import admin.task.TaskMaster_ACT;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Properties;
import java.nio.file.Path;
import client_master.Clientmaster_ACT;
import hcustbackend.ClientACT;
import admin.Login.LoginAction;
import hcustbackend.ClientACT;

public final class documents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/hcustfrontend/includes/client_header_menu.jsp", Long.valueOf(1672393721511L));
    _jspx_dependants.put("/hcustfrontend/includes/client-footer-js.jsp", Long.valueOf(1670913111283L));
    _jspx_dependants.put("/hcustfrontend/includes/checkvalid_client.jsp", Long.valueOf(1644210750000L));
    _jspx_dependants.put("/hcustfrontend/includes/client-header-css.jsp", Long.valueOf(1644210750000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("hcustbackend.ClientACT");
    _jspx_imports_classes.add("java.nio.file.Files");
    _jspx_imports_classes.add("admin.Login.LoginAction");
    _jspx_imports_classes.add("commons.CommonHelper");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("client_master.Clientmaster_ACT");
    _jspx_imports_classes.add("java.nio.file.Paths");
    _jspx_imports_classes.add("commons.AzureBlob");
    _jspx_imports_classes.add("admin.enquiry.Enquiry_ACT");
    _jspx_imports_classes.add("com.azure.storage.blob.BlobClientBuilder");
    _jspx_imports_classes.add("admin.task.TaskMaster_ACT");
    _jspx_imports_classes.add("java.nio.file.Path");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>  \r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/favicon.png\" type=\"image/ico\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/fakeLoader.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/font.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/media.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/jquery.timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/error.css\">\r\n");
      out.write("<!-- for animation -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/animate.css\">\r\n");
      out.write("<!-- for top scroll -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdcss/material-scrolltop.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/hcustfrontend/fntdcss/daterangepicker.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.dataTables.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/buttons.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.dataTables.min.css\" media=\"all\"/>");
      out.write("\r\n");
      out.write("    <title>corpSeed-documents</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"mySite\" style=\"display: block\">\r\n");
      out.write('\r');
      out.write('\n');

// response.setHeader("Cache-Control","no-cache");  
// response.setHeader("Cache-Control","no-store");  
// response.setDateHeader("Expires", -1);
response.setHeader("Cache-Control", "no-cache");
response.setHeader("Cache-Control", "no-store");
response.setDateHeader("Expires", 0);
response.setHeader("Pragma", "no-cache");

String uavalidtokenno1111= (String)session.getAttribute("uavalidtokenno");
String uaIsValid1= (String)session.getAttribute("loginuID");
if(uaIsValid1== null || uaIsValid1.equals("") || uavalidtokenno1111== null || uavalidtokenno1111.equals("")){

      out.write('\r');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("/login.html");
        return;
      }
      out.write('\r');
      out.write('\n');
}
      out.write('\r');
      out.write('\n');
      out.write(" \r\n");
      out.write("<!-- main content starts -->\r\n");

String salesrefid="NA";
String x=request.getParameter("uid");
salesrefid=x.substring(17,x.length()-5);

Properties properties = new Properties();
properties.load(getServletContext().getResourceAsStream("/staticresources/properties"));			
String azure_key=properties.getProperty("azure_key");
String azure_container=properties.getProperty("azure_container");
String azure_path=properties.getProperty("azure_path");
// BlobClientBuilder client=AzureBlob.getBlobClient(azure_key, azure_container);
String token=(String)session.getAttribute("uavalidtokenno");

String productKey=TaskMaster_ACT.getSalesProductKey(salesrefid, token);
long pageLimit=10;
String pageLimit1=(String)session.getAttribute("documentPageLimit");
if(pageLimit1!=null&&pageLimit1.length()>0)pageLimit=Long.parseLong(pageLimit1);


long pageStart=1;
String pageStart1=(String)session.getAttribute("documentPageStart");
if(pageStart1!=null&&pageStart1.length()>0)pageStart=Long.parseLong(pageStart1);

long pageEnd=10;
String pageEnd1=(String)session.getAttribute("documentPageEnd");
if(pageEnd1!=null&&pageEnd1.length()>0)pageEnd=Long.parseLong(pageEnd1);

long count=pageEnd/pageLimit;
// String file[][]=ClientACT.getAllFiles(refid,token,clid);
String invoice=TaskMaster_ACT.getSalesInvoiceNumber(salesrefid, token);
// double orderAmount=TaskMaster_ACT.getOrderAmount(invoice, token);
double dueAmount=Clientmaster_ACT.getSalesDueAmount(invoice,token);
// double payPercent=((orderAmount-dueAmount)*100)/orderAmount;
boolean isExist=TaskMaster_ACT.isDisperseExist(salesrefid, token);
double orderPaidAmount[]=null;
if(isExist)
 	orderPaidAmount=TaskMaster_ACT.getSalesOrderAndPaidAmount(salesrefid,token); 
else
	orderPaidAmount=TaskMaster_ACT.getSalesOrderAndPaidAmountByInvoice(invoice,token);
double payPercent=100;
if(orderPaidAmount[1]!=0&&orderPaidAmount[0]!=0)
	payPercent=(orderPaidAmount[1]*100)/orderPaidAmount[0];

int milestone=0;
int progress=0;
int completedtask=0;

String DocOf=(String)session.getAttribute("DocOfClientAgent");
if(DocOf==null||DocOf.length()<=0)DocOf="Client";
String doActionDocuments=(String)session.getAttribute("doActionDocuments");
if(doActionDocuments==null||doActionDocuments.length()<=0)doActionDocuments="Projects";
// boolean paymentDone=Clientmaster_ACT.isPaymentDone(salesrefid, token);
// boolean workDone=TaskMaster_ACT.getProjectWorkCompleted();
Random randomGenerator = new Random();
long randomInt = randomGenerator.nextInt(100000000);

      out.write("\r\n");
      out.write("<section class=\"main clearfix\">\r\n");
      out.write("  \r\n");
      out.write("  ");
      out.write('\r');
      out.write('\n');
 
String urlpage=request.getParameter("uid");
if(urlpage==null||urlpage.length()<=0)urlpage="NA";
if(!urlpage.equalsIgnoreCase("client_orders.html")){
	//removing client order action
	session.removeAttribute("ClientOrderDoAction");
	session.removeAttribute("ClientOrderSearchDoAction");
	session.removeAttribute("searchFromToDate");
	session.removeAttribute("searchOrderSorting");
	session.removeAttribute("orderPageLimit");
	session.removeAttribute("orderPageStart");
	session.removeAttribute("orderPageEnd");
}if(!urlpage.equalsIgnoreCase("client_inbox.html")){
	//removing client order action
	session.removeAttribute("ClientInboxDoAction");	
}
if(!urlpage.equalsIgnoreCase("client_documents.html")&&!urlpage.contains("viewalldocuments-")){
	//removing client doc action
	session.removeAttribute("doActionDocuments");
	session.removeAttribute("searchFolderDocuments");
	session.removeAttribute("searchFromToDocDate");
	session.removeAttribute("searchDocumentSorting");
	session.removeAttribute("clientDocumentPageLimit");
	session.removeAttribute("clientDocumentPageStart");
	session.removeAttribute("clientDocumentPageEnd");
}
if(!urlpage.contains("viewalldocuments-")){
	//removing client doc action
	session.removeAttribute("documentPageLimit");
	session.removeAttribute("documentPageStart");
	session.removeAttribute("documentPageEnd");
	session.removeAttribute("DocOfClientAgent");
}if(!urlpage.equalsIgnoreCase("all-notifications.html")){
	//removing client order action
	session.removeAttribute("notisearchFromToDate");
}if(!urlpage.equalsIgnoreCase("client_payments.html")){
	//removing client order action
	session.removeAttribute("ClientOrderSearchInvoice");
	session.removeAttribute("PaymentSearchFromToDate");
	session.removeAttribute("PaymentSearchOrderSorting");
	session.removeAttribute("paymentPageLimit");
	session.removeAttribute("paymentPageStart");
	session.removeAttribute("paymentPageEnd");
}
String userRole=(String)session.getAttribute("userRole");
if(userRole==null||userRole.length()<=0)userRole="NA";
String userName=(String)session.getAttribute("loginclname");
if(userName==null||userName.length()<=0)userName="NA";

String profileName=userName.substring(0,1);
if(userName.contains(" "))profileName+=userName.substring(userName.indexOf(" ")+1,userName.indexOf(" ")+2);
else profileName+=userName.substring(1,2); 

      out.write("\r\n");
      out.write("<header class=\"header\"> \r\n");
      out.write("    <div class=\"container-fluid\"> \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-12\"> \r\n");
      out.write("        <div class=\"logo\"> \r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_dashboard.html\" style=\"display: inline-block;\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/logo.png\" alt=\"\"></a>\r\n");
      out.write("        </div>       \r\n");
      out.write("        </div>          \r\n");
      out.write("        <div class=\"col-sm-9 col-12\"> \r\n");
      out.write("         <div class=\"top_menu text-right\">\r\n");
      out.write("          <ul>		  \r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("client_orders.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">            \r\n");
      out.write("            <a class=\"\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_orders.html\"><i class=\"fa fa-archive menu_icon\"></i><span>Your Orders</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("client_inbox.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">            \r\n");
      out.write("            <a class=\"\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_inbox.html\"><i class=\"fas fa-comment-dots menu_icon\" aria-hidden=\"true\"></i><span>Chat</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("client_documents.html")||urlpage.contains("viewalldocuments-")){ 
      out.write(" class=\"active\"");
}
      out.write(">            \r\n");
      out.write("            <a class=\"\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_documents.html\"><i class=\"fa fa-file-alt menu_icon\" aria-hidden=\"true\"></i><span>Doc Wallet</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("client_payments.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">            \r\n");
      out.write("            <a class=\"\" href=\"");
      out.print(request.getContextPath() );
      out.write("/client_payments.html\"><i class=\"fas fa-money-check menu_icon\" aria-hidden=\"true\"></i><span>Payments</span></a>\r\n");
      out.write("          </li>\r\n");
      out.write("		  <li");
if(urlpage.equalsIgnoreCase("my_profile.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("          <a class=\"setting\"  href=\"javascript:void(0)\"><i class=\"fas fa-user menu_icon\" aria-hidden=\"true\"></i><span>Profile</span></a>  \r\n");
      out.write("        <ul class=\"sub-menu\">\r\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_dashboard.html\">Dashboard</a></li>\r\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/my_profile.html\">My Profile</a></li>\r\n");
      out.write("\r\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.html\">LogOut</a></li> \r\n");
      out.write("		  </ul> \r\n");
      out.write("          </li>\r\n");
      out.write("          ");

          String clientloginuaid = (String) session.getAttribute("loginClintUaid");  
          
          String notificationtoken=(String)session.getAttribute("uavalidtokenno");          
          int notification=ClientACT.getTotalUnseenNotification(notificationtoken,clientloginuaid); 
          String notifications[][]=ClientACT.getAllClientNotification(notificationtoken,clientloginuaid);
          
      out.write("\r\n");
      out.write("          <li> \r\n");
      out.write("          \r\n");
      out.write("            <a href=\"javascript:void(0)\" class=\"notification\" onclick=\"markAllAsReadNotification('");
      out.print(notification);
      out.write("')\"><i class=\"far fa-bell \">");
if(notification>0){ 
      out.write("<span id=\"totalNotification\">");
      out.print(notification);
      out.write("</span>");
} 
      out.write("</i></a>\r\n");
      out.write("             <a href=\"");
      out.print(request.getContextPath() );
      out.write("/all-notifications.html\" class=\"notification_mobile\" onclick=\"markAllAsReadNotification('");
      out.print(notification);
      out.write("')\"><i class=\"fa fa-bell \">");
if(notification>0){ 
      out.write("<small>");
      out.print(notification);
      out.write("</small>");
} 
      out.write("</i><span  id=\"totalNotification_mobile\">Notification</span></a>\r\n");
      out.write("            <div class=\"notification_box pullDown\">                            \r\n");
      out.write("			  <ul>\r\n");
      out.write("			  ");
if(notifications!=null&&notifications.length>0){
				  for(int i=0;i<notifications.length;i++){
				  
      out.write("             \r\n");
      out.write("              <li class=\"clearfix\">\r\n");
      out.write("                <a href=\"javascript:void(0)\" onclick=\"markAsReadNotification('");
      out.print(notifications[i][2] );
      out.write("')\">                \r\n");
      out.write("                <div class=\"clearfix pro_box text-left\">\r\n");
      out.write("                    <div class=\"clearfix icon_box\">\r\n");
      out.write("                     <i class=\"");
      out.print(notifications[i][4] );
      out.write(" icon-circle\" aria-hidden=\"true\"></i>\r\n");
      out.write("                    </div> \r\n");
      out.write("                    <div class=\"clearfix pro_info\"> \r\n");
      out.write("                    <h6>");
      out.print(notifications[i][3] );
      out.write("</h6>\r\n");
      out.write("                    <div class=\"clearfix date_box\">");
      out.print(notifications[i][1] );
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </div>                 \r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              ");
}}else{ 
      out.write("\r\n");
      out.write("              <div class=\"text-center text-muted\">No data found !!</div>\r\n");
      out.write("              ");
} 
      out.write("\r\n");
      out.write("			  </ul> \r\n");
      out.write("			  <div class=\"text-center\"><a href=\"");
      out.print(request.getContextPath() );
      out.write("/all-notifications.html\">View All &nbsp;<i class=\"fa fa-angle-right\"></i></a></div>             \r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("<a href=\"#\" class=\"backbtnn\"><i class=\"fa fa-arrow-left\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("<div class=\"user_prof\">\r\n");
      out.write("<div class=\"user_thumb\"> \r\n");
      out.write("<h3>");
      out.print(userName );
      out.write("</h3>\r\n");
      out.write("<figure> <span class=\"prof_name\">");
      out.print(profileName );
      out.write("</span> </figure>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"user_detail\">\r\n");
      out.write("<div class=\"clearfix\"> \r\n");
      out.write("<a href=\"#\" data-toggle=\"modal\" data-target=\"#updatepass\">Update Password</a>\r\n");
      out.write("<!--  <span>Noida, India</span>   -->\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"top_menu menu_notification\">\r\n");
      out.write(" <ul>\r\n");
      out.write("<span>Settings</span>\r\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/my_profile.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/profile.svg\" alt=\"\">My Profile</a></li>\r\n");
      out.write("\r\n");
      out.write("<li id=\"client_payments\">           \r\n");
      out.write("  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_payments.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/payment.svg\" alt=\"\">Payments</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/all-notifications.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/bell.svg\" alt=\"\">Notification</a></li>\r\n");
      out.write(" </ul></div>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.html\" class=\"logoutbtnn\"> Logout</a>\r\n");
      out.write("</div>");
      out.write(" \r\n");
      out.write("  <section class=\"main-order clearfix\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-12 p-0\">\r\n");
      out.write("          <div class=\"doc_box box-orders\">  \r\n");
      out.write("		  <div class=\"clearfix document_page\">\r\n");
      out.write("		  \r\n");
      out.write("		  <div class=\"row mbt12\">\r\n");
      out.write("		  <div class=\"col-lg-8 col-md-8 col-sm-12 col-12 order\">\r\n");
      out.write("		  <ul class=\"clearfix filter_menu btnshift\">\r\n");
      out.write("			<li ");
if(DocOf.equalsIgnoreCase("Client")) {
      out.write("class=\"active\"");
} 
      out.write("><a  onclick=\"documentUploadBy('Client')\">Customer uploaded</a></li>\r\n");
      out.write("			<li ");
if(DocOf.equalsIgnoreCase("Agent")) {
      out.write("class=\"active\"");
} 
      out.write("><a onclick=\"documentUploadBy('Agent')\">Agent uploaded</a></li>\r\n");
      out.write("		  </ul>  \r\n");
      out.write("		  </div>\r\n");
      out.write("		  <div class=\"col-lg-4 col-md-4 col-sm-12 col-12 mobileback\">\r\n");
      out.write("		  	<a href=\"");
      out.print(request.getContextPath());
      out.write("/client_documents.html\"\" class=\"mobilebback \" style=\"display: none;\"><i class=\"fa fa-arrow-left ico_bdr\"></i></a> \r\n");
      out.write("		  	 <div class=\"pageheading\">\r\n");
      out.write("          <h4>PRJ002</h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"clearfix backbtn\"> \r\n");
      out.write("          	");
if(doActionDocuments.equalsIgnoreCase("Personal")){ 
      out.write("<a class=\"btn-default\" data-toggle=\"modal\" data-target=\"#newFileUploadModal\">+&nbsp;Upload</a>");
} 
      out.write("\r\n");
      out.write("            <a class=\"btn-default\" href=\"");
      out.print(request.getContextPath());
      out.write("/client_documents.html\">Back</a>\r\n");
      out.write("            <a href=\"#\" class=\"doticon\">  <i class=\"fa fa-ellipsis-v \" aria-hidden=\"true\"></i></a>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("		   \r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-12 bg_whitee\">\r\n");
      out.write("	<div class=\"table-responsive\">\r\n");
      out.write("	<table class=\"ctable\">\r\n");
      out.write("    <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th class=\"td_hide\">S.No.</th>\r\n");
      out.write("            <th class=\"td_hide\">Document Type</th>\r\n");
      out.write("            <th>Document Name</th>\r\n");
      out.write("            <th class=\"td_hide\">Upload Size</th>\r\n");
      out.write("            <th class=\"td_hide\">Upload Date</th>\r\n");
      out.write("            <th class=\"td_hide\">Upload Doc. Name</th>\r\n");
      out.write("            <th>Action</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write("    ");

    boolean fileExist=false;
    String payType=Enquiry_ACT.getSalesPayType(salesrefid,token);
    String files[][]=ClientACT.getAllFiles(salesrefid,token,DocOf,pageLimit,pageStart);
    if(files!=null&&files.length>0){
 	   for(int i=0;i<files.length;i++){
 		   String fileName=files[i][3];
 			String extension="";
 			String size="";
 			Path path=null;
 			if(fileName!=null&&!fileName.equalsIgnoreCase("NA")&&fileName.length()>0&&fileName.contains(".")){
 				fileExist=CommonHelper.isFileExists(fileName, azure_key, azure_container);
 				long bytes=0;
 				if(fileExist){
 					bytes=CommonHelper.getBlobSize(fileName, azure_key, azure_container);
 				}
 				long kb=bytes/1024;
 				long mb=kb/1024;	
 				
 				if(mb>=1)size=mb+" MB";
 				else if(kb>=1) size=kb+" KB";
 				else size=bytes+" bytes";	
 				int index=files[i][3].lastIndexOf(".");
 				extension=files[i][3].substring(index);
 			}else fileExist=false;
//  			System.out.println("fileExist="+fileExist);
     
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td class=\"td_hide\">");
      out.print((i+1) );
      out.write("</td>\r\n");
      out.write("            <td class=\"td_hide\"><i class=\"fa fa-file\" aria-hidden=\"true\"></i>");
      out.print(extension );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(files[i][1] );
      out.write("</td>\r\n");
      out.write("            <td class=\"td_hide\">");
      out.print(size);
      out.write("</td>		\r\n");
      out.write("            <td class=\"td_hide\">");
      out.print(files[i][5] );
      out.write("</td>	\r\n");
      out.write("            <td class=\"td_hide\">");
if(fileName!=null&&fileName.length()>0&&!fileName.equalsIgnoreCase("NA")){
      out.print(files[i][3].substring(21) );
} 
      out.write("</td>	\r\n");
      out.write("            <td class=\"doc_act_mobile\">\r\n");
      out.write("            <form onsubmit=\"return false\" class=\"uploadFileClass");
      out.print(i );
      out.write("\">	\r\n");
      out.write("			");
if(DocOf.equalsIgnoreCase("Client")){if(fileExist){ 
      out.write("\r\n");
      out.write("			<a href=\"");
      out.print(azure_path);
      out.print(files[i][3]);
      out.write("\" download><i class=\"fas fa-file-download\" aria-hidden=\"true\" title=\"Download file\"></i>&nbsp;Download</a>");
} 
      out.write(" \r\n");
      out.write("			<input type=\"file\" name=\"uploadFileBox");
      out.print(i );
      out.write("\" onchange=\"fileSizeCompaitable('");
      out.print(files[i][0] );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(i );
      out.write("')\" id=\"UploadFileBox");
      out.print(i );
      out.write("\" style=\"display: none;\">	\r\n");
      out.write("			<a href=\"javascript:void(0)\" onclick=\"$('#UploadFileBox");
      out.print(i );
      out.write("').click()\"><i class=\"fas fa-file-upload\" aria-hidden=\"true\" title=\"Upload file\"></i>&nbsp;Upload</a> \r\n");
      out.write("			");
}else if(DocOf.equalsIgnoreCase("Agent")&&fileExist){
				String milestoneName=TaskMaster_ACT.getMileStoneName(files[i][7],token);
				double percentage=TaskMaster_ACT.getProductWorkPercentage(productKey,milestoneName,token);
				if(percentage<=payPercent){
      out.write("\r\n");
      out.write("				<a href=\"");
      out.print(azure_path);
      out.print(files[i][3]);
      out.write("\" download=\"download\"><i class=\"fas fa-file-download\" aria-hidden=\"true\" title=\"Download file\"></i>&nbsp;Download</a>\r\n");
      out.write("				");
}else{
      out.write("\r\n");
      out.write("					<a href=\"javascript:void(0)\" onclick=\"showPartialPayment('");
      out.print(invoice);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(dueAmount);
      out.write("')\"><i class=\"fas fa-file-download text-muted\" aria-hidden=\"true\" title=\"Download file\"></i>&nbsp;Download</a>\r\n");
      out.write("				");
}				
			}
      out.write("	\r\n");
      out.write("			</form> \r\n");
      out.write("            </td>\r\n");
      out.write("            \r\n");
      out.write("            ");
      out.write("			\r\n");
      out.write("        </tr>\r\n");
      out.write("     ");
}}
      out.write("\r\n");
      out.write("                           \r\n");
      out.write("    </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-12 row page-range\">\r\n");
      out.write("            <div class=\"col-md-9\"></div>\r\n");
      out.write("            <div class=\"col-md-1 col-md-offset-9\">\r\n");
      out.write("				<select name=\"pageShow\" id=\"PageShow\"");
if(files.length>=10){ 
      out.write(" onchange=\"pageLimit(this.value)\"");
} 
      out.write(">\r\n");
      out.write("				    <option value=\"10\" ");
if(pageLimit==10){ 
      out.write("selected");
} 
      out.write(">10</option>\r\n");
      out.write("				    <option value=\"20\" ");
if(pageLimit==20){ 
      out.write("selected");
} 
      out.write(">20</option>\r\n");
      out.write("				    <option value=\"40\" ");
if(pageLimit==40){ 
      out.write("selected");
} 
      out.write(">40</option>\r\n");
      out.write("				    <option value=\"80\" ");
if(pageLimit==80){ 
      out.write("selected");
} 
      out.write(">80</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("		    <div class=\"col-md-2 text-center\">\r\n");
      out.write("		    <i class=\"fas fa-chevron-left pointers\" ");
if(pageStart>1){ 
      out.write("onclick=\"backwardPage()\"");
} 
      out.write("></i><span>");
      out.print(pageStart );
      out.write('-');
      out.print(pageEnd );
      out.write("</span><i class=\"fas fa-chevron-right pointers\" ");
if(files!=null&&files.length>=pageLimit){ 
      out.write("onclick=\"forwardPage()\"");
} 
      out.write("></i>\r\n");
      out.write("		    </div>\r\n");
      out.write("			  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>  \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"myModal modal fade\" id=\"newFileUploadModal\" aria-modal=\"false\" style=\" display: none;\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\"><i class=\"fas fa-folder-plus\" aria-hidden=\"true\"></i>New file</h4>  \r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form method=\"post\" onsubmit=\"return false\" class=\"uploadPersonalFile\">\r\n");
      out.write("        <input type=\"hidden\" name=\"salesKey\" value=\"");
      out.print(salesrefid);
      out.write("\">\r\n");
      out.write("        <div class=\"modal-body\">          \r\n");
      out.write("		  <div class=\"tab-content\">		  \r\n");
      out.write("		  <div id=\"pay_method2\" class=\"fade show\">\r\n");
      out.write("		  <div class=\"row mb10\">\r\n");
      out.write("            <div class=\"form-group-payment col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<label>File type</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"file_name\" id=\"File_Name\" placeholder=\"Name\" autocomplete=\"off\">\r\n");
      out.write("            </div> \r\n");
      out.write("            <div class=\"form-group-payment col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<label>Short description</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"file_description\" id=\"File_Description\" placeholder=\"Description\" autocomplete=\"off\">\r\n");
      out.write("            </div>\r\n");
      out.write("			<div class=\"form-group-payment col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<label>File</label>\r\n");
      out.write("            <input type=\"file\" class=\"form-control\" onchange=\"validateFileSize()\" name=\"folder_file_name\" id=\"Folder_File_Name\" placeholder=\"Name\" autocomplete=\"off\">\r\n");
      out.write("            </div>            \r\n");
      out.write("		  </div> \r\n");
      out.write("          </div>\r\n");
      out.write("		  </div>  		  \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer flex-end\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Cancel</button> \r\n");
      out.write("          <button type=\"submit\" class=\"btn btn-success\" onclick=\"return validateUploadFile()\">Submit</button> \r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"modal fade\" id=\"deleteWarningModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title text-danger\" id=\"exampleModalLabel\"><i class=\"fas fa-exclamation-triangle\"></i>&nbsp;&nbsp;Are you sure want to delete this file ?</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        Remove files immediately when deleted check box is not enabled. b. When the Display delete confirmation dialog check box is selected. The warning message appears when user tries to delete a file with other methods.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("      <input type=\"hidden\" id=\"DeletePersonalFileKey\">\r\n");
      out.write("      <input type=\"hidden\" id=\"DeletePersonalFileName\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" onclick=\"removePersonalFile()\">Delete</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div> \r\n");
      out.write(" <div class=\"modal fade\" id=\"PartialPaymemntModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title text-danger\" id=\"exampleModalLabel\"><i class=\"fas fa-exclamation-triangle\"></i>&nbsp;&nbsp;Payment is due !!</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        Your payment is due because of that you are not able to download this certificate.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("      <input type=\"hidden\" id=\"paymentInvoiceNo\">\r\n");
      out.write("      <input type=\"hidden\" id=\"paymentDue\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Ok</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" onclick=\"payNow()\">Pay Now</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div> \r\n");
      out.write("<!-- Payment Modal -->\r\n");
      out.write("  <div class=\"myModal modal fade\" id=\"paymentModal\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\"><i class=\"fa fa-credit-card\" aria-hidden=\"true\"></i>+Add Payments</h4>  \r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"payment.html\" target=\"_blank\" method=\"post\">\r\n");
      out.write("        <div class=\"modal-body\">        \r\n");
      out.write("          <ul class=\"payment_tab nav nav-tabs\">\r\n");
      out.write("		  <li><a data-toggle=\"tab\" href=\"#pay_method3\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/paytm.png\" alt=\"\"></a></li>\r\n");
      out.write("		  </ul>\r\n");
      out.write("		  <div class=\"tab-content\">\r\n");
      out.write("		  \r\n");
      out.write("		  <div id=\"pay_method3\" class=\"tab-pane fade show active\">\r\n");
      out.write("		  <div class=\"row\">\r\n");
      out.write("            <div class=\"form-group-payment col-md-8 col-sm-7 col-12\">\r\n");
      out.write("			<label>Mobile No.</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"MOBILE_NO\" id=\"Mobile_No\" required=\"required\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-group-payment col-md-4 col-sm-5 col-12\">\r\n");
      out.write("			<label>Amount</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"TXN_AMOUNT\" id=\"Amount\" required=\"required\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"hidden\" id=\"ORDER_ID\" name=\"ORDER_ID\" value=\"ORDS_");
      out.print( randomInt );
      out.write("\">\r\n");
      out.write("		  </div>\r\n");
      out.write("          </div>\r\n");
      out.write("		  </div>  		  \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"submit\" class=\"btn btn-success\" onclick=\"return isValidAmount()\">Confirm Payment</button> \r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- End Payment Modal -->\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<footer class=\"clearfix\">\r\n");
      out.write("<div class=\"rights\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("<div class=\"copyright\">\r\n");
      out.write("<p>Copyright &copy;2021 Corpseed ITES Pvt Ltd - All rights reserved.</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<div class=\"footer_menu menu_notification\">\r\n");
String urlpage1=request.getParameter("uid");
if(urlpage1==null||urlpage1.length()<=0)urlpage1="NA"; 
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("<li id=\"client_orders\"");
if(urlpage1.equalsIgnoreCase("client_orders.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("<small></small>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_orders.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/all_orders.svg\" alt=\"\"><span>Your Orders</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("<li id=\"client_inbox\"");
if(urlpage1.equalsIgnoreCase("client_inbox.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("<small></small>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_inbox.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/chat.svg\" alt=\"\"><span>Chat</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_dashboard.html\" class=\"footer_logo\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/footer_logo1.png\" alt=\"\"></a>\r\n");
      out.write("</li>\r\n");
      out.write("<li id=\"client_documents\"");
if(urlpage1.equalsIgnoreCase("client_documents.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("<small></small>\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/client_documents.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/document.svg\" alt=\"\"><span>Doc Wallet</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("<li id=\"my_profile\"");
if(urlpage1.equalsIgnoreCase("my_profile.html")||urlpage1.equalsIgnoreCase("client_payments.html")||urlpage1.equalsIgnoreCase("all-notifications.html")){ 
      out.write(" class=\"active\"");
}
      out.write(">\r\n");
      out.write("<small></small>\r\n");
      out.write("<a class=\"setting mtoggle\" href=\"javascript:void(0)\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdimages/profile.svg\" alt=\"\"><span>Profile</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Update password Modal -->\r\n");
      out.write("  <div class=\"myModal modal fade\" id=\"updatepass\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\"><i class=\"fas fa-lock\"></i>Change Password</h4>  \r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("		 <form action=\"javascript:void(0)\">\r\n");
      out.write("		  <div class=\"row\">\r\n");
      out.write("            <div class=\"form-group-pass col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<label>Current Password</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" name=\"cpassword\" id=\"Current_password\"  placeholder=\"Enter Current Password*\" required=\"required\">\r\n");
      out.write("            </div>           \r\n");
      out.write("		  </div> \r\n");
      out.write("		   <div class=\"row\">\r\n");
      out.write("            <div class=\"form-group-pass col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<label>New Password</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" name=\"npassword\" id=\"New_Password\" placeholder=\"Enter New Password*\" required=\"required\">\r\n");
      out.write("            <span class=\"show_psw active\" onclick=\"myFunction('New_Password')\">\r\n");
      out.write("									<i class=\"fa fa-eye-slash\" style=\"font-size:15px;color:#006080\"></i>\r\n");
      out.write("									</span>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("		  </div> \r\n");
      out.write("		   <div class=\"row\">\r\n");
      out.write("            <div class=\"form-group-pass col-md-12 col-sm-12 col-12\">\r\n");
      out.write("			<label>Confirm Password</label>\r\n");
      out.write("            <input type=\"password\" class=\"form-control\" name=\"cfpassword\" id=\"Confirm_Password\" placeholder=\"Re-enter New Password*\" required=\"required\">\r\n");
      out.write("            <span class=\"show_psw active\" onclick=\"myFunction('Confirm_Password')\">\r\n");
      out.write("			<i class=\"fa fa-eye-slash\" style=\"font-size:15px;color:#006080\"></i>\r\n");
      out.write("			</span>\r\n");
      out.write("            </div>           \r\n");
      out.write("		  </div> \r\n");
      out.write("		  </form>\r\n");
      out.write("          </div>\r\n");
      out.write("		 \r\n");
      out.write("        <div class=\"modal-footer justify-content-end\">\r\n");
      out.write("          <button type=\"submit\" class=\"btn btn-success\" onclick=\"return validatePassword()\" id=\"Update_Password\">Update Password</button> \r\n");
      out.write("          <button type=\"button\" class=\"btn btn-outline-secondary\" data-dismiss=\"modal\">Cancel</button> \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<!-- End Update password Modal -->\r\n");
      out.write("<div class=\"alert-show\" style=\"display: none;\"><div class=\"alert-bg alert-striped\" id=\"errorMsg\"></div></div>\r\n");
      out.write("<div class=\"alert-show1\" style=\"display: none;\"><div class=\"alert-bg1 alert-striped\" id=\"errorMsg1\"></div></div>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/5b8cdab0e6.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/fakeLoader.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/wow.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/datepicker.js\"></script>\r\n");
      out.write("<div class=\"processing_loader\" style=\"display: none;\"><div class=\"spin_box\"></div></div>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/jquery.timepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/hcustfrontend/fntdjs/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/hcustfrontend/fntdjs/daterangepicker.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/custom.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/fontawsome.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/hcustfrontend/fntdjs/globalscript.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jszip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/pdfmake.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/vfs_fonts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.html5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.print.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.colVis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("if(window.history.replaceState){\r\n");
      out.write("window.history.replaceState( null, null, window.location.href );\r\n");
      out.write("}\r\n");
      out.write("new WOW().init();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(window).load(function() {\r\n");
      out.write("	  $(\".processing_loader\").fadeOut();\r\n");
      out.write("	});\r\n");
      out.write("function showLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeIn(); \r\n");
      out.write("}\r\n");
      out.write("function hideLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeOut();  \r\n");
      out.write("}  \r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write("  function validateFileSize(){\r\n");
      out.write("	  var fileId=\"Folder_File_Name\";\r\n");
      out.write("	  \r\n");
      out.write("		const fi=document.getElementById(fileId);\r\n");
      out.write("		if (fi.files.length > 0) {\r\n");
      out.write("			const fsize = fi.files.item(0).size; \r\n");
      out.write("	        const file = Math.round((fsize / 1024)); \r\n");
      out.write("	        \r\n");
      out.write("	        // The size of the file. \r\n");
      out.write("	        if (file >= 49152) {  \r\n");
      out.write("	            document.getElementById('errorMsg').innerHTML ='File too Big, Max File Size 48 MB !!';\r\n");
      out.write("	            document.getElementById(fileId).value=\"\";\r\n");
      out.write("	 		    $('.alert-show').show().delay(4000).fadeOut();\r\n");
      out.write("	        }	\r\n");
      out.write("		}	\r\n");
      out.write(" }\r\n");
      out.write("  \r\n");
      out.write("  function validateUploadFile(){\r\n");
      out.write("	   var folderName=$(\"#File_Name\").val();  \r\n");
      out.write("	   var folderDesc=$(\"#File_Description\").val();\r\n");
      out.write("	   var folderFileName=$(\"#Folder_File_Name\").val();\r\n");
      out.write("	  \r\n");
      out.write("	   if(folderName==null||folderName==\"\"){\r\n");
      out.write("		   document.getElementById('errorMsg').innerHTML = 'Please enter file type like aaddhar card  !!.';\r\n");
      out.write("		   $('.alert-show').show().delay(2000).fadeOut();\r\n");
      out.write("		   return false;\r\n");
      out.write("	   }\r\n");
      out.write("	   if(folderDesc==null||folderDesc==\"\"){\r\n");
      out.write("		   document.getElementById('errorMsg').innerHTML = 'Please write short description about file !!.';\r\n");
      out.write("		   $('.alert-show').show().delay(2000).fadeOut();\r\n");
      out.write("		   return false;\r\n");
      out.write("	   }\r\n");
      out.write("	   if(folderFileName==null||folderFileName==\"\"){\r\n");
      out.write("		   document.getElementById('errorMsg').innerHTML = 'Please select file !!.';\r\n");
      out.write("		   $('.alert-show').show().delay(2000).fadeOut();\r\n");
      out.write("		   return false;\r\n");
      out.write("	   }\r\n");
      out.write("	   \r\n");
      out.write("		var form = $(\".uploadPersonalFile\")[0];\r\n");
      out.write("	    var data = new FormData(form);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("	        type : \"POST\",\r\n");
      out.write("	        encType : \"multipart/form-data\",\r\n");
      out.write("	        url : \"");
      out.print(request.getContextPath());
      out.write("/UploadPersonalFiles111\",\r\n");
      out.write("	        cache : false,\r\n");
      out.write("	        processData : false,\r\n");
      out.write("	        contentType : false,\r\n");
      out.write("	        data : data,\r\n");
      out.write("	        success : function(data) {\r\n");
      out.write("	        	if(data==\"pass\"){\r\n");
      out.write("	        	location.reload(true);\r\n");
      out.write("	    		}else{\r\n");
      out.write("	    			document.getElementById('errorMsg').innerHTML =\"Something Went wrong ,try-again later !!\";\r\n");
      out.write("		    		$('.alert-show').show().delay(3000).fadeOut();\r\n");
      out.write("		    		return false;\r\n");
      out.write("	    		}\r\n");
      out.write("	        },\r\n");
      out.write("	        error : function(msg) {\r\n");
      out.write("	            alert(\"Couldn't upload file\");\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("			\r\n");
      out.write("	}\r\n");
      out.write("  \r\n");
      out.write("  function fileSizeCompaitable(docKey,k){\r\n");
      out.write("	  var fileId=\"UploadFileBox\"+k;\r\n");
      out.write("	  \r\n");
      out.write("		const fi=document.getElementById(fileId);\r\n");
      out.write("		if (fi.files.length > 0) {\r\n");
      out.write("			const fsize = fi.files.item(0).size; \r\n");
      out.write("	        const file = Math.round((fsize / 1024)); \r\n");
      out.write("	        // The size of the file. \r\n");
      out.write("	        if (file >= 49152) {  \r\n");
      out.write("	            document.getElementById('errorMsg').innerHTML ='File too Big, Max File Size 48 MB !!';\r\n");
      out.write("	            document.getElementById(fileId).value=\"\";\r\n");
      out.write("	 		    $('.alert-show').show().delay(4000).fadeOut();\r\n");
      out.write("	        }else{\r\n");
      out.write("	        	uploadFile(docKey,k);\r\n");
      out.write("	        }		\r\n");
      out.write("		}	\r\n");
      out.write(" }\r\n");
      out.write(" function uploadFile(docKey,k){	\r\n");
      out.write("	 var File=\"uploadFileBox\"+k;\r\n");
      out.write("	 var rowId=\"row\"+k;\r\n");
      out.write("	 var page=\"");
      out.print(x);
      out.write("\";\r\n");
      out.write("	\r\n");
      out.write("	 var uploadFileClass=\"uploadFileClass\"+k;\r\n");
      out.write("	   setTimeout(() => {	\r\n");
      out.write("		if($(\"#\"+File).val()!=\"\"){		\r\n");
      out.write("		var form = $(\".\"+uploadFileClass)[0];\r\n");
      out.write("	    var data = new FormData(form);\r\n");
      out.write("	    data.append(\"docKey\", docKey);\r\n");
      out.write("	    data.append(\"file\", File);\r\n");
      out.write("	    data.append(\"assignKey\",\"NA\");\r\n");
      out.write("	    data.append(\"workStartPrice\",\"0\");\r\n");
      out.write("		$.ajax({\r\n");
      out.write("	        type : \"POST\",\r\n");
      out.write("	        encType : \"multipart/form-data\",\r\n");
      out.write("	        url : \"");
      out.print(request.getContextPath());
      out.write("/UpdateSalesDocuments111\",\r\n");
      out.write("	        cache : false,\r\n");
      out.write("	        processData : false,\r\n");
      out.write("	        contentType : false,\r\n");
      out.write("	        data : data,\r\n");
      out.write("	        success : function(data) {\r\n");
      out.write("	        	var x=data.split(\"#\");\r\n");
      out.write("	        	if(x[0]==\"pass\"){\r\n");
      out.write("	        	document.getElementById('errorMsg1').innerHTML =\"Uploaded Successfully !!\";\r\n");
      out.write("	        	$(\"#DocWalletDivId\").load(location.href + \" #DocWalletDivId1\");\r\n");
      out.write("	    		$('.alert-show1').show().delay(3000).fadeOut();\r\n");
      out.write("	    		}else{\r\n");
      out.write("	    			document.getElementById('errorMsg').innerHTML =\"Something Went wrong ,try-again later !!\";\r\n");
      out.write("		    		$('.alert-show').show().delay(3000).fadeOut();\r\n");
      out.write("	    		}\r\n");
      out.write("	        },\r\n");
      out.write("	        error : function(msg) {\r\n");
      out.write("	            alert(\"Couldn't upload file\");\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("		}	\r\n");
      out.write("	   }, 200);\r\n");
      out.write("	}\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  function validateUpload(){	     \r\n");
      out.write("	  if(document.getElementById(\"DocumentName\").value.trim()==\"\"){\r\n");
      out.write("		  document.getElementById('errorMsg').innerHTML = 'Document Name is required.';\r\n");
      out.write("		  $('.alert-show').show().delay(2000).fadeOut();\r\n");
      out.write("		  return false;\r\n");
      out.write("	  }\r\n");
      out.write("	  if(document.getElementById(\"DocumentType\").value.trim()==\"\"){\r\n");
      out.write("		  document.getElementById('errorMsg').innerHTML = 'Document Type is required.';\r\n");
      out.write("		  $('.alert-show').show().delay(2000).fadeOut();\r\n");
      out.write("		  return false;\r\n");
      out.write("	  }\r\n");
      out.write("	  if(document.getElementById(\"FolderName\").value.trim()==\"\"){\r\n");
      out.write("		  document.getElementById('errorMsg').innerHTML = 'Select Folder.';\r\n");
      out.write("		  $('.alert-show').show().delay(2000).fadeOut();\r\n");
      out.write("		  return false;\r\n");
      out.write("	  }\r\n");
      out.write("	  if(document.getElementById(\"DocumentFile\").value.trim()==\"\"){\r\n");
      out.write("		  document.getElementById('errorMsg').innerHTML = 'Choose File.';\r\n");
      out.write("		  $('.alert-show').show().delay(2000).fadeOut();\r\n");
      out.write("		  return false;\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("  }\r\n");
      out.write(" function documentUploadBy(data){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"POST\",\r\n");
      out.write("			url : \"documentUploadBy999\",\r\n");
      out.write("			dataType : \"HTML\",\r\n");
      out.write("			data : {\r\n");
      out.write("				data : data,\r\n");
      out.write("			},\r\n");
      out.write("			success : function(response){\r\n");
      out.write("				location.reload();					\r\n");
      out.write("			}\r\n");
      out.write("		});	\r\n");
      out.write(" } \r\n");
      out.write("  function restSearch(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type : \"GET\",\r\n");
      out.write("			url : \"ManageClientDocumentCTRL.html\",\r\n");
      out.write("			dataType : \"HTML\",\r\n");
      out.write("			data : {\r\n");
      out.write("				reset : \"reset\",\r\n");
      out.write("			},\r\n");
      out.write("			success : function(data){\r\n");
      out.write("				location.reload();					\r\n");
      out.write("			}\r\n");
      out.write("		});	\r\n");
      out.write("	}\r\n");
      out.write("  \r\n");
      out.write("  function setDtaeFromTo(){	\r\n");
      out.write("		if(document.getElementById(\"ClientDocFrom\").value.trim()==\"\"){\r\n");
      out.write("			document.getElementById('errorMsg').innerHTML = 'Select Start Date First.';\r\n");
      out.write("			document.getElementById(\"ClientDocTo\").value=\"\";\r\n");
      out.write("			$('.alert-show').show().delay(2000).fadeOut();		\r\n");
      out.write("		}else{\r\n");
      out.write("			var clientfrom=document.getElementById(\"ClientDocFrom\").value.trim();\r\n");
      out.write("			var clientto=document.getElementById(\"ClientDocTo\").value.trim();		\r\n");
      out.write("			if(clientfrom==\"\") clientfrom=\"NA\";\r\n");
      out.write("			if(clientto==\"\")clientto=\"NA\";			\r\n");
      out.write("			\r\n");
      out.write("			var clientto=document.getElementById(\"ClientDocTo\").value.trim();\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type : \"POST\",\r\n");
      out.write("					url : \"ManageClientDocumentCTRL.html\",\r\n");
      out.write("					dataType : \"HTML\",\r\n");
      out.write("					data : {\r\n");
      out.write("						clientfrom : clientfrom,\r\n");
      out.write("						clientto : clientto,						\r\n");
      out.write("					},\r\n");
      out.write("					success : function(data){\r\n");
      out.write("						location.reload();					\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("  function deletePersonalFile(skey,fileName){\r\n");
      out.write("	  $(\"#deleteWarningModal\").modal('show'); \r\n");
      out.write("	  $(\"#DeletePersonalFileKey\").val(skey);\r\n");
      out.write("	  $(\"#DeletePersonalFileName\").val(fileName);\r\n");
      out.write("  }\r\n");
      out.write("  function removePersonalFile(){\r\n");
      out.write("	  var skey=$(\"#DeletePersonalFileKey\").val();\r\n");
      out.write("	  var fileName=$(\"#DeletePersonalFileName\").val();\r\n");
      out.write("		var xhttp;\r\n");
      out.write("		xhttp = new XMLHttpRequest();\r\n");
      out.write("		xhttp.onreadystatechange = function() {\r\n");
      out.write("		if (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("			$(\"#deleteWarningModal\").modal('hide'); 	\r\n");
      out.write("			location.reload();\r\n");
      out.write("		}\r\n");
      out.write("		};\r\n");
      out.write("		xhttp.open(\"GET\", \"");
      out.print(request.getContextPath());
      out.write("/RemoveFile111?skey=\"+skey+\"&fileName=\"+fileName, true);\r\n");
      out.write("		xhttp.send();\r\n");
      out.write("	}\r\n");
      out.write("  \r\n");
      out.write("  $('.datepicker').datepicker({\r\n");
      out.write("	    format: 'yyyy-mm-dd',    \r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	  function doAction(data,name){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("			    type: \"POST\",\r\n");
      out.write("			    url: \"");
      out.print(request.getContextPath());
      out.write("/SetOrderTypeSearch999\",\r\n");
      out.write("			    data:  { \r\n");
      out.write("			    	data : data,\r\n");
      out.write("			    	name : name\r\n");
      out.write("			    },\r\n");
      out.write("			    success: function (response) {        	  \r\n");
      out.write("		         location.reload(true);\r\n");
      out.write("		        },\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	function pageLimit(data){\r\n");
      out.write("		  var start=\"");
      out.print(pageStart);
      out.write("\";\r\n");
      out.write("		  var limit=\"");
      out.print(pageLimit);
      out.write("\";\r\n");
      out.write("		  var end=Number(start)+Number(data);\r\n");
      out.write("		  if(Number(start)==1)end-=1;\r\n");
      out.write("		  doAction(data,'documentPageLimit');\r\n");
      out.write("		  doAction(end,'documentPageEnd');\r\n");
      out.write("		  location.reload(true);\r\n");
      out.write("	}\r\n");
      out.write("	function backwardPage(){\r\n");
      out.write("			 var count=\"");
      out.print(count-1);
      out.write("\";\r\n");
      out.write("			 var limit=\"");
      out.print(pageLimit);
      out.write("\";\r\n");
      out.write("			 var start=0;\r\n");
      out.write("			 if(Number(count)>=1){			 \r\n");
      out.write("				 start=(Number(count)-1)*Number(limit);\r\n");
      out.write("				 if(start==0)start=1;\r\n");
      out.write("				 var end=Number(count)*Number(limit);			 \r\n");
      out.write("			 }else if(count==0){\r\n");
      out.write("				 start=1;\r\n");
      out.write("				 end=limit;\r\n");
      out.write("			 }\r\n");
      out.write("			 doAction(start,'documentPageStart');\r\n");
      out.write("			 doAction(end,'documentPageEnd');\r\n");
      out.write("			 location.reload(true);\r\n");
      out.write("		 }\r\n");
      out.write("	function forwardPage(){  \r\n");
      out.write("		 var count=\"");
      out.print(count+1);
      out.write("\";\r\n");
      out.write("		 var limit=\"");
      out.print(pageLimit);
      out.write("\";\r\n");
      out.write("		 var start=(Number(count)-1)*Number(limit);\r\n");
      out.write("		 var end=Number(count)*Number(limit);\r\n");
      out.write("		 doAction(start,'documentPageStart');\r\n");
      out.write("		 doAction(end,'documentPageEnd');\r\n");
      out.write("		 location.reload(true);\r\n");
      out.write("	}\r\n");
      out.write("	function payNow(){\r\n");
      out.write("		$(\"#paymentModal\").modal(\"show\");\r\n");
      out.write("		var data=$(\"#paymentInvoiceNo\").val();\r\n");
      out.write("		var due=$(\"#paymentDue\").val();\r\n");
      out.write("		$(\"#Amount\").val(Number(due).toFixed(2));\r\n");
      out.write("		$.ajax({\r\n");
      out.write("		    type: \"POST\",\r\n");
      out.write("		    url: \"");
      out.print(request.getContextPath());
      out.write("/SetOrderTypeSearch999\",\r\n");
      out.write("		    data:  { \r\n");
      out.write("		    	data : data,\r\n");
      out.write("		    	name : \"SalesKey\"\r\n");
      out.write("		    },\r\n");
      out.write("		    success: function (response) {  \r\n");
      out.write("	        },\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	function showPartialPayment(invoice,amount){\r\n");
      out.write("		$(\"#paymentInvoiceNo\").val(invoice);\r\n");
      out.write("		$(\"#paymentDue\").val(amount);\r\n");
      out.write("		$(\"#PartialPaymemntModal\").modal(\"show\");\r\n");
      out.write("	}\r\n");
      out.write("	function isValidAmount(){\r\n");
      out.write("		var dueAmount=\"");
      out.print(dueAmount);
      out.write("\";\r\n");
      out.write("		var amount=$(\"#Amount\").val();\r\n");
      out.write("		var mobile=$(\"#Mobile_No\").val();\r\n");
      out.write("		if(mobile==null||mobile==\"\"){\r\n");
      out.write("			document.getElementById('errorMsg').innerHTML = 'Mobile No. is required !!';\r\n");
      out.write("			$('.alert-show').show().delay(4000).fadeOut();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(Number(amount)>Number(dueAmount)){\r\n");
      out.write("			document.getElementById('errorMsg').innerHTML = 'Maximum amount should be Rs. '+dueAmount;\r\n");
      out.write("			$('.alert-show').show().delay(4000).fadeOut();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("  </script>\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
