/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.receipt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import commons.CommonHelper;
import admin.task.TaskMaster_ACT;
import admin.enquiry.Enquiry_ACT;
import client_master.Clientmaster_ACT;

public final class payment_002dconfirm_002dreceipt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/receipt/../staticresources/includes/itswsstyles.jsp", Long.valueOf(1637404914000L));
    _jspx_dependants.put("/receipt/../staticresources/includes/itswsscripts.jsp", Long.valueOf(1637404914000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("client_master.Clientmaster_ACT");
    _jspx_imports_classes.add("commons.CommonHelper");
    _jspx_imports_classes.add("admin.enquiry.Enquiry_ACT");
    _jspx_imports_classes.add("admin.task.TaskMaster_ACT");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\r\n");
      out.write("<title>Payment Summary</title>\r\n");
      out.write("\r\n");
      out.write("<META NAME=\"ROBOTS\" CONTENT=\"NOINDEX, NOFOLLOW\"></META>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/images/favicon.png\" type=\"image/ico\"/>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/font-awesome.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.fancybox.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery-ui.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap-datetimepicker.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/error.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/daterangepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/select2.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/mdtimepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/theme.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.dataTables.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/buttons.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{background: #c3c3c32b;}\r\n");
      out.write(".bg-color{background: #48bd44;color: #fff;}\r\n");
      out.write("@media print {\r\n");
      out.write("   body{margin:0;padding:0;font-size:12px;}\r\n");
      out.write("   header, footer{display:none;}\r\n");
      out.write("   p{margin-bottom:10px;font-size:12px;margin-top:0;}\r\n");
      out.write("   #invoicecontent{width: 100% !important;margin-left: 0px !important;}\r\n");
      out.write("   img{width: 35%;}\r\n");
      out.write("   #printData{display: none;}\r\n");
      out.write("}\r\n");
      out.write("@media only screen and (max-width: 767.98px) {\r\n");
      out.write("#invoicecontent{\r\n");
      out.write("width:100%!important;\r\n");
      out.write("margin-left:0!important\r\n");
      out.write("}}\r\n");
      out.write("table th:first-child {\r\n");
      out.write("    -moz-border-radius: 0px 0 0 0;\r\n");
      out.write("    -webkit-border-radius: 0px 0 0 0;\r\n");
      out.write("    border-radius: 0px 0 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table th:last-child {\r\n");
      out.write("    -moz-border-radius: 0 0px 0 0;\r\n");
      out.write("    -webkit-border-radius: 0 0px 0 0;\r\n");
      out.write("    border-radius: 0 0px 0 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String paymentKey=request.getParameter("uid").trim();
paymentKey=paymentKey.substring(8,paymentKey.length()-5);
System.out.println(paymentKey);

String payment[][]=Enquiry_ACT.fetchSalesEstimatePayment(paymentKey);

if(payment!=null&&payment.length>0){
	String clientKey=Enquiry_ACT.getEstimateClientKeyBySalesNo(payment[0][1]);
	String client[]=Enquiry_ACT.getClientsDetail(clientKey);
	
// 	if(client[0]==null||client[0].equalsIgnoreCase("NA")||client[0].length()<=0){
// 		String estimateKey=billData[0][2];
// 		String token=billData[0][7];
// 		String contactKey=Enquiry_ACT.getEstimateContactKey(estimateKey, token);		
// 		client=Enquiry_ACT.getContactDetail(contactKey,token);
// 	}
		
// }
// boolean gstStatus=Enquiry_ACT.isGstApplied(genKey);

      out.write("\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"clearfix menuDv pad_box3 pad05 mb10\" style=\"min-height: 150px;margin-top: 16px;width: 50%;margin-left: 25%;\" id=\"invoicecontent\">\r\n");
      out.write("<div class=\"clearfix invoice_div\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"clearfix\" style=\"width:100%;padding-top:0px;display: flex;\">\r\n");
      out.write("<div style=\"width:50%;\">\r\n");
      out.write("<div style=\"margin-bottom:1px;\">\r\n");
      out.write("<img src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/images/corpseed-logo.png\" alt=\"corpseed logo\" style=\"max-width:95px;\">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clearfix\">\r\n");
      out.write("<p>\r\n");
      out.write("<span style=\"font-weight:600;color:#888;\">Corpseed Ites Private Limited</span><br>\r\n");
      out.write("<span>CN U74999UP2018PTC101873</span><br>\r\n");
      out.write("<span>2nd Floor, A-154A, A Block, Sector 63</span><br/>\r\n");
      out.write("<span>Noida, Uttar Pradesh - 201301</span><br/>\r\n");
      out.write("<span>GSTIN 09AAHCC4539J1ZC</span>\r\n");
      out.write("<br>\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"width:50%;\">\r\n");
      out.write("<div style=\"margin-bottom:10px;text-align:right;\">\r\n");
      out.write("<h2 style=\"font-size:18px;margin:0 0 5px;color:#48bd44;font-weight: 500;\">ESTIMATE</h2>\r\n");
      out.write("<p style=\"font-weight:600;\" id=\"EstimateBillNo\"># ");
      out.print(payment[0][1]);
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<div class=\"clearfix\" style=\"width:100%;\">\r\n");
      out.write("<p style=\"margin:0px;\">Bill To : </p>\r\n");
      out.write("<p style=\"font-weight: 600;margin-bottom: 5px;\" id=\"BillToId\">");
if(client[0]!=null){
      out.print(client[0] );
} 
      out.write("</p>\r\n");
if(client[4]!=null&&!client[4].equalsIgnoreCase("NA")){ 
      out.write("\r\n");
      out.write("<p style=\"margin-top: -1rem;\">GSTIN ");
      out.print(client[4] );
      out.write("</p>");
} 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<div class=\"clearfix\" style=\"width:100%;display: flex;\">\r\n");
      out.write("<div style=\"width:50%;\">\r\n");
      out.write("<p style=\"margin:0px;\"></p>\r\n");
      out.write("<p style=\"margin-bottom:5px;\">Ship To : <br>\r\n");
      out.write("<span id=\"ShipToId\">");
if(client[0]!=null){
      out.print(client[0] );
} 
      out.write("</span>\r\n");
      out.write("<span id=\"ShipToAddressId\">");
if(client[1]!=null){
      out.print(client[1] );
} 
      out.write("</span></p>\r\n");
      out.write("<p>Place Of Supply: <span id=\"ShipToStateCode\">");
if(client[2]!=null){
      out.print(client[2] );
}if(client[3]!=null&&!client[3].equalsIgnoreCase("NA")){
      out.write(' ');
      out.write('(');
      out.print(client[3] );
      out.write(')');
} 
      out.write("</span></p>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"width:50%;text-align:right;\">\r\n");
      out.write("<p><span style=\"font-weight:600;color:#888;\">Date :</span> <span style=\"padding-left:20px;\">");
      out.print(payment[0][0]);
      out.write("</span></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<div class=\"table-responsive\">\r\n");
      out.write("<table  border=\"1\" style=\"width:100%;border:1px solid #7c7272\">\r\n");
      out.write("<tr style=\"background: #48bd44!important;color: #fff!important;\">\r\n");
      out.write("<th rowspan=\"2\" style=\"padding: 3px;\">#</th>\r\n");
      out.write("<th rowspan=\"2\" style=\"padding: 3px;\">Item & Description</th>\r\n");
      out.write("<th rowspan=\"2\" style=\"padding: 3px;\">Rate</th>\r\n");
      out.write("<th colspan=\"3\" style=\"padding: 3px;text-align:center;\">Tax</th>\r\n");
      out.write("<th rowspan=\"2\" style=\"padding: 3px;\">Tax Amt.</th>\r\n");
      out.write("<th rowspan=\"2\" style=\"padding: 3px;\">Amount</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr style=\"background: #48bd44!important;color: #fff!important;\">\r\n");
      out.write("<td style=\"padding: 3px;\">SGST %</td>\r\n");
      out.write("<td style=\"padding: 3px;\">CGST %</td>\r\n");
      out.write("<td style=\"padding: 3px;\">IGST %</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td style=\"padding: 3px;font-weight:600\">1</td>\r\n");
      out.write("<td style=\"padding: 3px;font-weight:600\" colspan=\"7\">");
      out.print(payment[0][5] );
      out.write("</td></tr>\r\n");

double rate=0;
double gstSum=0; 
String paymentDetails[][]=Enquiry_ACT.getPaymentList(paymentKey,payment[0][6]);
if(paymentDetails!=null&&paymentDetails.length>0){
	for(int j=0;j<paymentDetails.length;j++){
		double gst=(Double.parseDouble(paymentDetails[j][4])*(Double.parseDouble(paymentDetails[j][6])+Double.parseDouble(paymentDetails[j][5])+Double.parseDouble(paymentDetails[j][7])))/100;
		rate+=Double.parseDouble(paymentDetails[j][4]);
		gstSum+=gst;

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td style=\"padding: 3px;\">");
      out.print(paymentDetails[j][3] );
      out.write("</td>\r\n");
      out.write("<td style=\"padding: 3px;\">");
      out.print(CommonHelper.withLargeIntegers(Math.round(Double.parseDouble(paymentDetails[j][4]))) );
      out.write("</td>\r\n");
      out.write("<td style=\"padding: 3px;\">");
      out.print(paymentDetails[j][6] );
      out.write("%</td>\r\n");
      out.write("<td style=\"padding: 3px;\">");
      out.print(paymentDetails[j][5] );
      out.write("%</td>\r\n");
      out.write("<td style=\"padding: 3px;\">");
      out.print(paymentDetails[j][7] );
      out.write("%</td>\r\n");
      out.write("<td style=\"padding: 3px;\">");
      out.print(CommonHelper.withLargeIntegers(Math.round(gst)) );
      out.write("</td>\r\n");
      out.write("<td style=\"padding: 3px;\">");
      out.print(CommonHelper.withLargeIntegers(Math.round((Double.parseDouble(paymentDetails[j][4])+gst))));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
}} 
      out.write("\r\n");
      out.write("<tr style=\"font-weight: 600\">\r\n");
      out.write("<td colspan=\"2\" style=\"padding: 5px;\">Total</td><td colspan=\"4\" style=\"padding: 3px;\">");
      out.print(CommonHelper.withLargeIntegers(Math.round(rate)) );
      out.write("</td>\r\n");
      out.write("<td style=\"padding: 3px;\">");
      out.print(CommonHelper.withLargeIntegers(Math.round(gstSum)) );
      out.write("</td>\r\n");
      out.write("<td style=\"padding: 3px;\">");
      out.print(CommonHelper.withLargeIntegers(Math.round(Double.parseDouble(payment[0][4]))));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<p style=\"margin:0;padding-top: 10px;text-align:right;\">Total In Words: <span style=\"font-weight:600;padding-left:10px;color:#666;\" id=\"SalesRupeesInWord\">INR Twenty One Thousand Two Hundred Forty   only.</span></p>\r\n");
      out.write("<div class=\"clearfix\" style=\"width:100%;margin-top:5px;margin-bottom:5px;\">  \r\n");
      out.write("<p style=\"margin-bottom:5px;color:#555;\"><span style=\"font-weight: 600;\">Notes :</span> <span></span></p>\r\n");
      out.write("<p style=\"font-size: 11px;color:#888;\">This Estimates &amp; price quotation is valid for 7 calendar days from the date of issue.</p>\r\n");
if(payment[0][7]!=null&&!payment[0][7].equalsIgnoreCase("NA")){
      out.write("\r\n");
      out.write("<p style=\"font-size: 11px;color:#888;\">");
      out.print(payment[0][7] );
      out.write("</p>\r\n");
} 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clearfix\" style=\"width:100%;\">\r\n");
      out.write("<p style=\"color:#888;\">\r\n");
      out.write("<span style=\"display:block;font-weight:600;font-size: 11px;\">Payment Options:</span>\r\n");
      out.write("<span style=\"display:block;\">\r\n");
      out.write("<span style=\"font-weight:600;\">IMPS/RTGS/NEFT:</span> Account Number: 10052624515 || IFSC Code: IDFB0021331 || Beneficiary Name: Corpseed ITES Private Limited || Bank Name: IDFC FIRST Bank, Noida, Sector 63 Branch</span>\r\n");
      out.write("<span style=\"display:block;\"><span style=\"font-weight:600;\">Direct Pay:</span> https://www.corpseed.com/payment || <span style=\"font-weight:600;\">Pay via UPI:</span> CORPSEEDV.09@cmsidfc</span>\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clearfix\" style=\"width:100%;margin-top:5px;border-top:1px solid #ddd;padding-top:5px;margin-bottom:10px;\">\r\n");
      out.write("<p style=\"color:#999;font-size: 11px;\">Note: Government fee and corpseed professional fee may differ depending on any additional changes advised the client in the application  or any changes in the government policies</p>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clearfix\" id=\"printData\" style=\"font-size: 20px;text-align: center;\"><button onclick=\"window.print()\"><i class=\"fa fa-print\">&nbsp;Print</i></button></div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.fancybox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/nicEdit.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/globalscript.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/select2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/daterangepicker.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/mdtimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/fontawsome.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/theme.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jszip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/pdfmake.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/vfs_fonts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.html5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.print.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.colVis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready( function () {\r\n");
      out.write("	var role=\"");
      out.print(session.getAttribute("emproleid"));
      out.write("\";\r\n");
      out.write("	$(\".checked\").click(function(){\r\n");
      out.write("		 if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("			 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("	$(\"#CheckAll\").click(function(){\r\n");
      out.write("	$('.checked').prop('checked', this.checked);\r\n");
      out.write("	if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("		 	 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		    \r\n");
      out.write("	});\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write(" $(window).load(function() {\r\n");
      out.write("  $(\".processing_loader\").fadeOut();\r\n");
      out.write("}); \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function showLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeIn(); \r\n");
      out.write("} \r\n");
      out.write("function hideLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeOut();  \r\n");
      out.write("}  \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.timepicker').mdtimepicker();\r\n");
      out.write("function openClock(id){\r\n");
      out.write("$('#'+id).mdtimepicker();\r\n");
      out.write("}\r\n");
      out.write("function openCalendar(id){\r\n");
      out.write("	$(\"#\"+id).datepicker({changeMonth:true,changeYear:true,dateFormat:'yy-mm-dd'});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.has-clear input[type=\"text\"]').on('input propertychange', function() {\r\n");
      out.write("  var $this = $(this);\r\n");
      out.write("  var visible = Boolean($this.val());\r\n");
      out.write("  $this.siblings('.form-control-clear').toggleClass('hidden', !visible);\r\n");
      out.write("}).trigger('propertychange');\r\n");
      out.write("\r\n");
      out.write("$('.form-control-clear').click(function() {\r\n");
      out.write("  $(this).siblings('input[type=\"text\"]').val('')\r\n");
      out.write("    .trigger('propertychange').focus();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goBack() {\r\n");
      out.write("  window.history.back();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("	var totalAmount=\"");
      out.print(Math.round(Double.parseDouble(payment[0][4])));
      out.write("\";\r\n");
      out.write("	numberToWords(\"SalesRupeesInWord\",Number(totalAmount));\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function numberToWords(RupeesId,number) {  \r\n");
      out.write("    var digit = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine'];  \r\n");
      out.write("    var elevenSeries = ['ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen'];  \r\n");
      out.write("    var countingByTens = ['twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety'];  \r\n");
      out.write("    var shortScale = ['', 'thousand', 'million', 'billion', 'trillion'];  \r\n");
      out.write("\r\n");
      out.write("    number = number.toString();\r\n");
      out.write("    number = number.replace(/[\\, ]/g, '');\r\n");
      out.write("    if (number != parseFloat(number)) return 'not a number';\r\n");
      out.write("    var x = number.indexOf('.');\r\n");
      out.write("    if (x == -1) x = number.length; if (x > 15) return 'too big';\r\n");
      out.write("    var n = number.split(''); \r\n");
      out.write("    var str = ''; \r\n");
      out.write("    var sk = 0;\r\n");
      out.write("    for (var i = 0; i < x; i++) { \r\n");
      out.write("    	if ((x - i) % 3 == 2) { \r\n");
      out.write("    		if (n[i] == '1') { \r\n");
      out.write("    			str += elevenSeries[Number(n[i + 1])] + ' '; \r\n");
      out.write("    			i++; sk = 1; \r\n");
      out.write("    			} else if (n[i] != 0) { \r\n");
      out.write("    				str += countingByTens[n[i] - 2] + ' ';\r\n");
      out.write("    				sk = 1;\r\n");
      out.write("    				} } else if (n[i] != 0) { \r\n");
      out.write("    					str += digit[n[i]] + ' ';\r\n");
      out.write("    					if ((x - i) % 3 == 0) str += 'hundred ';\r\n");
      out.write("    					sk = 1; \r\n");
      out.write("    					} if ((x - i) % 3 == 1) { \r\n");
      out.write("    						if (sk) str += shortScale[(x - i - 1) / 3] + ' ';\r\n");
      out.write("    						sk = 0; \r\n");
      out.write("    						} \r\n");
      out.write("    					} if (x != number.length) {\r\n");
      out.write("    							var y = number.length;\r\n");
      out.write("    							var str1='point ';\r\n");
      out.write("    							var z=0;\r\n");
      out.write("    							for (var i = x + 1; i < y; i++) {\r\n");
      out.write("    								z=Number(z)+Number(n[i]);\r\n");
      out.write("    								str1 += digit[n[i]] + ' '; \r\n");
      out.write("    							}\r\n");
      out.write("    							if(z>0){\r\n");
      out.write("    								str+=str1;\r\n");
      out.write("    							}\r\n");
      out.write("    							} \r\n");
      out.write("    						str = str.replace(/\\number+/g, ' ');    						 \r\n");
      out.write(" document.getElementById(RupeesId).innerHTML=\"INR \"+str.replace(/\\w\\S*/g, function(txt){return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();})+\" only.\";\r\n");
      out.write("}\r\n");
      out.write("function numberWithCommas(x) {\r\n");
      out.write("    return x.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
