/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.madministrator;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/madministrator/../staticresources/includes/itswsstyles.jsp", Long.valueOf(1637404914000L));
    _jspx_dependants.put("/madministrator/../staticresources/includes/itswsscripts.jsp", Long.valueOf(1637404914000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html lang=\"en-US\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n");
      out.write("	<title>Registered User Login Panel</title>\n");
      out.write("	");
      out.write("<META NAME=\"ROBOTS\" CONTENT=\"NOINDEX, NOFOLLOW\"></META>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/images/favicon.png\" type=\"image/ico\"/>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/font-awesome.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.fancybox.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery-ui.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap-datetimepicker.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/error.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/daterangepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/select2.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/mdtimepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/theme.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.dataTables.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/buttons.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("	\n");
      out.write("</head>\n");
      out.write("<script type = \"text/javascript\" >\n");
      out.write("window.history.forward(); \n");
      out.write("function noBack() { \n");
      out.write("    window.history.forward(); \n");
      out.write("} \n");
      out.write("</script>\n");
      out.write("<body onload=\"trafficcontrol();\">\n");
      out.write("\n");
      out.write("<div class=\"wrap\">\n");

HttpSession SES = request.getSession(true);
String getmsg=(String)SES.getAttribute("loginerrormsg"); 

      out.write("\n");
      out.write("\n");
      out.write("<div id=\"content\">\n");
      out.write("		<div class=\"main-content\">\n");
      out.write("			<div class=\"container\">\n");
      out.write("			<div class=\"col-md-4 col-md-offset-4\">\n");
      out.write("				<form class=\"crm-login\" action=\"");
      out.print(request.getContextPath() );
      out.write("/login.html\" method=\"post\" id=\"ITLoginCheck\" name=\"ITLoginCheck\">\n");
      out.write("				<input type=\"hidden\" name=\"actiontype\">\n");
      out.write("                <input type=\"hidden\" name=\"empbrowser\" id=\"empbrowser\">\n");
      out.write("				<div class=\"text-center\">\n");
      out.write("				 <img class=\"mb1\" src=\"");
      out.print(request.getContextPath() );
      out.write("/staticresources/images/logo.png\" alt=\"Logo\" width=\"140\">\n");
      out.write("                 <h1 class=\"h3 mb2\">Lets Get Started</h1>\n");
      out.write("                 <div>\n");
      out.write("                 ");
if(getmsg!=null){
      out.write("\n");
      out.write("                 <p class=\"text-danger\">");
      out.print(getmsg);
      out.write("</p>\n");
      out.write("                 ");
}
 SES.removeAttribute("loginerrormsg");
      out.write(" </div>\n");
      out.write("                 <div>\n");
      out.write("                 ");

                 String passwordReset=(String)session.getAttribute("passwordresetsuccess");
                 if(passwordReset!=null){
      out.write("\n");
      out.write("                 <p class=\"text-success\">");
      out.print(passwordReset);
      out.write("</p>\n");
      out.write("                 ");
}
 SES.removeAttribute("passwordresetsuccess");
      out.write(" </div>\n");
      out.write("                 </div>\n");
      out.write("				  <div class=\"mb2\">\n");
      out.write("				    <input type=\"text\" class=\"form-control\" name=\"userId\" id=\"User ID\" placeholder=\"Username *\" required=\"required\">				    \n");
      out.write("				  </div>\n");
      out.write("				  <div class=\"mb2\">\n");
      out.write("				    <input type=\"password\" class=\"form-control\" name=\"userPassword\" id=\"User Password\" placeholder=\"Password *\" required=\"required\">\n");
      out.write("				  </div>\n");
      out.write("				  <div class=\"mb2 form-check\">\n");
      out.write("				    <input type=\"checkbox\" class=\"form-check-input\" id=\"exampleCheck1\">\n");
      out.write("				    <label class=\"form-check-label\" for=\"exampleCheck1\">Remember me</label>\n");
      out.write("				  </div>\n");
      out.write("				   <input type=\"hidden\" id=\"LoginPage\" name=\"loginpage\" value=\"NA\"/>\n");
      out.write("				  <button type=\"submit\" class=\"btn btn-block btn-primary\" onclick=\"document.getElementById('LoginPage').value='YAA'\">SIGN IN</button>\n");
      out.write("				  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/forget-password.html\" class=\"mt1\" style=\"float: right;\">Forget password ?</a>\n");
      out.write("                  <p class=\"mt4 mb2 text-muted text-center\">\n");
      out.write("                      &copy; <span id=\"year\"></span>\n");
      out.write("                  </p>\n");
      out.write("                  <input type=\"hidden\" id=\"ForwardUrl\" name=\"forwardUrl\">\n");
      out.write("				</form>\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("</div>\n");
      out.write("</div>	\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.fancybox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/nicEdit.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/globalscript.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/select2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/daterangepicker.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/mdtimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/fontawsome.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/theme.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jszip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/pdfmake.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/vfs_fonts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.html5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.print.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.colVis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready( function () {\r\n");
      out.write("	var role=\"");
      out.print(session.getAttribute("emproleid"));
      out.write("\";\r\n");
      out.write("	$(\".checked\").click(function(){\r\n");
      out.write("		 if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("			 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("	$(\"#CheckAll\").click(function(){\r\n");
      out.write("	$('.checked').prop('checked', this.checked);\r\n");
      out.write("	if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("		 	 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		    \r\n");
      out.write("	});\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write(" $(window).load(function() {\r\n");
      out.write("  $(\".processing_loader\").fadeOut();\r\n");
      out.write("}); \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function showLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeIn(); \r\n");
      out.write("} \r\n");
      out.write("function hideLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeOut();  \r\n");
      out.write("}  \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.timepicker').mdtimepicker();\r\n");
      out.write("function openClock(id){\r\n");
      out.write("$('#'+id).mdtimepicker();\r\n");
      out.write("}\r\n");
      out.write("function openCalendar(id){\r\n");
      out.write("	$(\"#\"+id).datepicker({changeMonth:true,changeYear:true,dateFormat:'yy-mm-dd'});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.has-clear input[type=\"text\"]').on('input propertychange', function() {\r\n");
      out.write("  var $this = $(this);\r\n");
      out.write("  var visible = Boolean($this.val());\r\n");
      out.write("  $this.siblings('.form-control-clear').toggleClass('hidden', !visible);\r\n");
      out.write("}).trigger('propertychange');\r\n");
      out.write("\r\n");
      out.write("$('.form-control-clear').click(function() {\r\n");
      out.write("  $(this).siblings('input[type=\"text\"]').val('')\r\n");
      out.write("    .trigger('propertychange').focus();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goBack() {\r\n");
      out.write("  window.history.back();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("function trafficcontrol() {\n");
      out.write("	var host = location.host;\n");
      out.write("	var referrer = document.referrer;\n");
      out.write("	var useragent = navigator.userAgent;\n");
      out.write("	$.ajax({\n");
      out.write("		type : \"POST\",\n");
      out.write("		url : \"trafficcontrol\",\n");
      out.write("		data : {\n");
      out.write("			\"host\" : host,\n");
      out.write("			\"referrer\" : referrer,\n");
      out.write("			\"useragent\" : useragent\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("}\n");
      out.write("$(document).ready(function(){\n");
      out.write("	document.getElementById(\"year\").innerHTML = new Date().getFullYear();\n");
      out.write("	document.getElementById(\"empbrowser\").value=navigator.appCodeName;\n");
      out.write("	$(\"#ForwardUrl\").val(window.location.href);\n");
      out.write("})\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
