/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.madministrator;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import admin.enquiry.Enquiry_ACT;
import java.util.Properties;
import client_master.Clientmaster_ACT;
import admin.task.TaskMaster_ACT;
import admin.master.Usermaster_ACT;
import hcustbackend.ClientACT;
import admin.Login.LoginAction;

public final class track_002dinvoice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/madministrator/../staticresources/includes/itswsstyles.jsp", Long.valueOf(1637404914000L));
    _jspx_dependants.put("/madministrator/../staticresources/includes/itswsfooter.jsp", Long.valueOf(1637404914000L));
    _jspx_dependants.put("/madministrator/../staticresources/includes/itswsscripts.jsp", Long.valueOf(1637404914000L));
    _jspx_dependants.put("/madministrator/../staticresources/includes/../../madministrator/checkvalid_user.jsp", Long.valueOf(1648627112000L));
    _jspx_dependants.put("/madministrator/../staticresources/includes/itswsheader.jsp", Long.valueOf(1693314479004L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("admin.master.Usermaster_ACT");
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("hcustbackend.ClientACT");
    _jspx_imports_classes.add("client_master.Clientmaster_ACT");
    _jspx_imports_classes.add("admin.Login.LoginAction");
    _jspx_imports_classes.add("admin.enquiry.Enquiry_ACT");
    _jspx_imports_classes.add("admin.task.TaskMaster_ACT");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 1120256, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/> \r\n");
      out.write("	<title>Track Sale</title>\r\n");
      out.write("	");
      out.write("<META NAME=\"ROBOTS\" CONTENT=\"NOINDEX, NOFOLLOW\"></META>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/images/favicon.png\" type=\"image/ico\"/>\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/font-awesome.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.fancybox.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery-ui.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/bootstrap-datetimepicker.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/error.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/daterangepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/select2.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/mdtimepicker.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/theme.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/jquery.dataTables.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/buttons.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/css/responsive.dataTables.min.css\" media=\"all\"/>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

response.addHeader("Pragma", "no-cache");
response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
response.addHeader("Cache-Control", "pre-check=0, post-check=0");
response.setDateHeader("Expires", 0);

String uavalidtokenno1111= (String)session.getAttribute("uavalidtokenno");
String uaIsValid1= (String)session.getAttribute("loginuID");

String sessionid = (String) session.getAttribute("sessionID");
String euaValidForAccess =  LoginAction.getPermissions(uaIsValid1, sessionid);
if(uaIsValid1== null || uaIsValid1.equals("") || uavalidtokenno1111== null || uavalidtokenno1111.equals("")||euaValidForAccess==null){	

      out.write('\r');
      out.write('\n');
      if (true) {
        _jspx_page_context.forward("/login.html");
        return;
      }
      out.write('\r');
      out.write('\n');
}
      out.write('\r');
      out.write('\n');

boolean CLA00=false;
boolean ADM00=false;
boolean ACU01=false;
boolean ACU02=false;
boolean ACU03=false;
boolean ACU04=false;
boolean ACU05=false;
boolean AMU02=false;
boolean ATT03=false;
boolean ATT02=false;
boolean SAL04=false;
boolean SAL00=false;
boolean SAL01=false;
boolean SAL02=false;
boolean SAL03=false;
boolean SAL05=false;
boolean SAL06=false;
boolean DEX00=false;
boolean DEX01=false;
boolean DEX02=false;
boolean DEX03=false;
boolean DEX05=false;
boolean CL00=false;
boolean CR01=false;
boolean CR02=false;
boolean CR03=false;
boolean CR04=false;
boolean CR05=false;
boolean CPR03=false;
boolean CB06=false;
boolean MB07=false;
boolean MB08=false;
boolean MB09=false;
boolean UBL0=false;
boolean TM00=false;
boolean MT00=false;
boolean MT01=false;
boolean TN02=false;
boolean MS03=false;
boolean MS04=false;
boolean MS05=false;
boolean MS06=false;
boolean MA00=false;
boolean MP01=false;
boolean MP02=false;
boolean EQ00=false;
boolean EQ01=false;
boolean EQ02=false;
boolean EM01=false;
boolean EM02=false;
boolean EM03=false;
boolean EM04=false;
boolean SR01=false;
boolean SR02=false;
boolean RC00=false;
boolean MC00=false;
boolean MC01=false;
boolean MC02=false;
boolean MC03=false;
boolean MC04=false;
boolean RE00=false;
boolean ME00=false;
boolean ME01=false;
boolean ME02=false;
boolean ME03=false;
boolean ME04=false;
boolean AC00=false;
boolean MS09=false;
boolean LTH00=false;
boolean EM05=false;
boolean EM06=false;
boolean MSL00=false;
boolean MSL01=false;
boolean MSL02=false;
boolean MSL03=false;
boolean MSL04=false;
boolean MTH00=false;
boolean MTH01=false;
boolean MTH02=false;
boolean MTH03=false;
boolean MTH04=false;
boolean MMH00=false;
boolean MMH01=false;
boolean MMH02=false;
boolean MMH03=false;
boolean MMH04=false;
boolean MAS00=false;
boolean MAS01=false;
boolean MST00=false;
boolean MST01=false;
boolean MST02=false;
boolean SUC00=false;
boolean SUC01=false;
boolean SUC02=false;
boolean MCV00=false;
boolean MCV01=false;
boolean MCV02=false;
boolean ACC00=false;
boolean ACC01=false;
boolean ACC02=false;
boolean ACC03=false;
boolean MB00=false;
boolean MB01=false;
boolean MB02=false;
boolean MIN00=false;
boolean MIN01=false;
boolean MIN02=false;
boolean MIN03=false;
boolean GH00=false;
boolean GH01=false;
boolean MP03=false;
boolean MP04=false;
boolean MPP00=false;
boolean MPP01=false;
boolean MTT00=false;
boolean MTT01=false;
boolean MTT02=false;
boolean MTT03=false;
boolean MTT04=false;
boolean MTT05=false;
boolean MMP00=false;
boolean MMP01=false;
boolean MMP02=false;
boolean MMP03=false;
boolean MMP04=false;
boolean MP05=false;
boolean AMC00=false;
boolean EST00=false;
boolean EST01=false;
boolean MD00=false;
boolean MDC0=false;
boolean MCC0=false;
boolean MG00=false;
boolean MTR0=false;
boolean MTX0=false;
boolean MTM0=false;
boolean MCO0=false;
boolean MX00=false;
boolean CH00=false;
boolean GI00=false;
boolean MCP0=false;
boolean RD00=false;
boolean DH00=false; 
boolean EH00=false;
boolean MCR0=false;
boolean MTR1=false;
boolean INV0=false;
boolean DC00=false;
boolean DOC00=false;
boolean DTR00=false;
   
if(euaValidForAccess!=null){    
String[] getempaccessesL=euaValidForAccess.split("#");
for(int ur=0;ur<getempaccessesL.length;ur++) {
if(getempaccessesL[ur].equals("ADM00")){ADM00=true;}
else if(getempaccessesL[ur].equals("CLA00")){CLA00=true;}
else if(getempaccessesL[ur].equals("MG00")){MG00=true;}
else if(getempaccessesL[ur].equals("MTR0")){MTR0=true;}
else if(getempaccessesL[ur].equals("MTX0")){MTX0=true;}
else if(getempaccessesL[ur].equals("MTM0")){MTM0=true;}
else if(getempaccessesL[ur].equals("MCO0")){MCO0=true;}
else if(getempaccessesL[ur].equals("MDC0")){MDC0=true;}
else if(getempaccessesL[ur].equals("MCC0")){MCC0=true;}
else if(getempaccessesL[ur].equals("MD00")){MD00=true;}
else if(getempaccessesL[ur].equals("EST00")){EST00=true;}
else if(getempaccessesL[ur].equals("EST01")){EST01=true;}
else if(getempaccessesL[ur].equals("ACU01")){ACU01=true;}
else if(getempaccessesL[ur].equals("ACU02")){ACU02=true;}
else if(getempaccessesL[ur].equals("ACU03")){ACU03=true;}
else if(getempaccessesL[ur].equals("ACU04")){ACU04=true;}
else if(getempaccessesL[ur].equals("ACU05")){ACU05=true;}
else if(getempaccessesL[ur].equals("AMU02")){AMU02=true;}
else if(getempaccessesL[ur].equals("ATT02")){ATT02=true;}
else if(getempaccessesL[ur].equals("ATT03")){ATT03=true;}
else if(getempaccessesL[ur].equals("SAL04")){SAL04=true;}
else if(getempaccessesL[ur].equals("SAL00")){SAL00=true;}
else if(getempaccessesL[ur].equals("SAL01")){SAL01=true;}
else if(getempaccessesL[ur].equals("SAL02")){SAL02=true;}
else if(getempaccessesL[ur].equals("SAL03")){SAL03=true;}
else if(getempaccessesL[ur].equals("SAL05")){SAL05=true;}
else if(getempaccessesL[ur].equals("SAL06")){SAL06=true;}
else if(getempaccessesL[ur].equals("DEX00")) {DEX00=true;}
else if(getempaccessesL[ur].equals("DEX01")) {DEX01=true;}
else if(getempaccessesL[ur].equals("DEX02")) {DEX02=true;}
else if(getempaccessesL[ur].equals("DEX03")) {DEX03=true;}
else if(getempaccessesL[ur].equals("DEX05")) {DEX05=true;}
else if(getempaccessesL[ur].equals("CL00")){CL00=true;}
else if(getempaccessesL[ur].equals("CR01")){CR01=true;}
else if(getempaccessesL[ur].equals("CR02")){CR02=true;}
else if(getempaccessesL[ur].equals("CR03")){CR03=true;}
else if(getempaccessesL[ur].equals("CR04")){CR04=true;}
else if(getempaccessesL[ur].equals("CR05")){CR05=true;}
else if(getempaccessesL[ur].equals("CPR03")){CPR03=true;}
else if(getempaccessesL[ur].equals("CB06")){CB06=true;}
else if(getempaccessesL[ur].equals("MB07")){MB07=true;}
else if(getempaccessesL[ur].equals("MB08")){MB08=true;}
else if(getempaccessesL[ur].equals("UBL0")){UBL0=true;}
else if(getempaccessesL[ur].equals("MB09")){MB09=true;}
else if(getempaccessesL[ur].equals("TM00")){TM00=true;}
else if(getempaccessesL[ur].equals("MT00")){MT00=true;}
else if(getempaccessesL[ur].equals("MT01")){MT01=true;}
else if(getempaccessesL[ur].equals("TN02")){TN02=true;}
else if(getempaccessesL[ur].equals("MS03")){MS03=true;}
else if(getempaccessesL[ur].equals("MS04")){MS04=true;}
else if(getempaccessesL[ur].equals("MS05")){MS05=true;}
else if(getempaccessesL[ur].equals("MS06")){MS06=true;}
else if(getempaccessesL[ur].equals("MA00")){MA00=true;}
else if(getempaccessesL[ur].equals("MP01")){MP01=true;}
else if(getempaccessesL[ur].equals("MP02")){MP02=true;}
else if(getempaccessesL[ur].equals("EQ00")){EQ00=true;}
else if(getempaccessesL[ur].equals("EQ01")){EQ01=true;}
else if(getempaccessesL[ur].equals("EQ02")){EQ02=true;}
else if(getempaccessesL[ur].equals("EM01")){EM01=true;}
else if(getempaccessesL[ur].equals("EM02")){EM02=true;}
else if(getempaccessesL[ur].equals("EM03")){EM03=true;}
else if(getempaccessesL[ur].equals("EM04")){EM04=true;}
else if(getempaccessesL[ur].equals("SR01")){SR01=true;}
else if(getempaccessesL[ur].equals("SR02")){SR02=true;}
else if(getempaccessesL[ur].equals("RC00")){RC00=true;}
else if(getempaccessesL[ur].equals("MC00")){MC00=true;}
else if(getempaccessesL[ur].equals("MC01")){MC01=true;}
else if(getempaccessesL[ur].equals("MC02")){MC02=true;}
else if(getempaccessesL[ur].equals("MC03")){MC03=true;}
else if(getempaccessesL[ur].equals("MC04")){MC04=true;}
else if(getempaccessesL[ur].equals("RE00")){RE00=true;}
else if(getempaccessesL[ur].equals("ME00")){ME00=true;}
else if(getempaccessesL[ur].equals("ME01")){ME01=true;}
else if(getempaccessesL[ur].equals("ME02")){ME02=true;}
else if(getempaccessesL[ur].equals("ME03")){ME03=true;}
else if(getempaccessesL[ur].equals("ME04")){ME04=true;}
else if(getempaccessesL[ur].equals("AC00")){AC00=true;}
else if(getempaccessesL[ur].equals("MS09")){MS09=true;}
else if(getempaccessesL[ur].equals("LTH00")){LTH00=true;}
else if(getempaccessesL[ur].equals("EM05")){EM05=true;}
else if(getempaccessesL[ur].equals("EM06")){EM06=true;}
else if(getempaccessesL[ur].equals("MSL00")){MSL00=true;}
else if(getempaccessesL[ur].equals("MSL01")){MSL01=true;}
else if(getempaccessesL[ur].equals("MSL02")){MSL02=true;}
else if(getempaccessesL[ur].equals("MSL03")){MSL03=true;}
else if(getempaccessesL[ur].equals("MSL04")){MSL04=true;}
else if(getempaccessesL[ur].equals("MTH00")){MTH00=true;}
else if(getempaccessesL[ur].equals("MTH01")){MTH01=true;}
else if(getempaccessesL[ur].equals("MTH02")){MTH02=true;}
else if(getempaccessesL[ur].equals("MTH03")){MTH03=true;}
else if(getempaccessesL[ur].equals("MTH04")){MTH04=true;}
else if(getempaccessesL[ur].equals("MMH00")){MMH00=true;}
else if(getempaccessesL[ur].equals("MMH01")){MMH01=true;}
else if(getempaccessesL[ur].equals("MMH02")){MMH02=true;}
else if(getempaccessesL[ur].equals("MMH03")){MMH03=true;}
else if(getempaccessesL[ur].equals("MMH04")){MMH04=true;}
else if(getempaccessesL[ur].equals("MAS00")){MAS00=true;}
else if(getempaccessesL[ur].equals("MAS01")){MAS01=true;}
else if(getempaccessesL[ur].equals("MST00")){MST00=true;}
else if(getempaccessesL[ur].equals("MST01")){MST01=true;}
else if(getempaccessesL[ur].equals("MST02")){MST02=true;}
else if(getempaccessesL[ur].equals("SUC00")){SUC00=true;}
else if(getempaccessesL[ur].equals("SUC01")){SUC01=true;}
else if(getempaccessesL[ur].equals("SUC02")){SUC02=true;}
else if(getempaccessesL[ur].equals("MCV00")){MCV00=true;}
else if(getempaccessesL[ur].equals("MCV01")){MCV01=true;}
else if(getempaccessesL[ur].equals("MCV02")){MCV02=true;}
else if(getempaccessesL[ur].equals("ACC00")){ACC00=true;}
else if(getempaccessesL[ur].equals("ACC01")){ACC01=true;}
else if(getempaccessesL[ur].equals("ACC02")){ACC02=true;}
else if(getempaccessesL[ur].equals("ACC03")){ACC03=true;}
else if(getempaccessesL[ur].equals("MB00")){MB00=true;}
else if(getempaccessesL[ur].equals("MB01")){MB01=true;}
else if(getempaccessesL[ur].equals("MB02")){MB02=true;}
else if(getempaccessesL[ur].equals("MIN00")){MIN00=true;}
else if(getempaccessesL[ur].equals("MIN01")){MIN01=true;}
else if(getempaccessesL[ur].equals("MIN02")){MIN02=true;}
else if(getempaccessesL[ur].equals("MIN03")){MIN03=true;}
else if(getempaccessesL[ur].equals("GH00")){GH00=true;}
else if(getempaccessesL[ur].equals("GH01")){GH01=true;}
else if(getempaccessesL[ur].equals("MP03")){MP03=true;}
else if(getempaccessesL[ur].equals("MP04")){MP04=true;}
else if(getempaccessesL[ur].equals("MPP00")){MPP00=true;}
else if(getempaccessesL[ur].equals("MPP01")){MPP01=true;}
else if(getempaccessesL[ur].equals("MTT00")){MTT00=true;}
else if(getempaccessesL[ur].equals("MTT01")){MTT01=true;}
else if(getempaccessesL[ur].equals("MTT02")){MTT02=true;}
else if(getempaccessesL[ur].equals("MTT03")){MTT03=true;}
else if(getempaccessesL[ur].equals("MTT04")){MTT04=true;}
else if(getempaccessesL[ur].equals("MTT05")){MTT05=true;}
else if(getempaccessesL[ur].equals("MMP00")){MMP00=true;}
else if(getempaccessesL[ur].equals("MMP01")){MMP01=true;}
else if(getempaccessesL[ur].equals("MMP02")){MMP02=true;}
else if(getempaccessesL[ur].equals("MMP03")){MMP03=true;}
else if(getempaccessesL[ur].equals("MMP04")){MMP04=true;}
else if(getempaccessesL[ur].equals("MP05")){MP05=true;}
else if(getempaccessesL[ur].equals("AMC00")){AMC00=true;}
else if(getempaccessesL[ur].equals("MX00")){MX00=true;}
else if(getempaccessesL[ur].equals("CH00")){CH00=true;}
else if(getempaccessesL[ur].equals("GI00")){GI00=true;}
else if(getempaccessesL[ur].equals("MCP0")){MCP0=true;}
else if(getempaccessesL[ur].equals("RD00")){RD00=true;}
else if(getempaccessesL[ur].equals("DH00")){DH00=true;}
else if(getempaccessesL[ur].equals("EH00")){EH00=true;}
else if(getempaccessesL[ur].equals("MCR0")){MCR0=true;}
else if(getempaccessesL[ur].equals("MTR1")){MTR1=true;}
else if(getempaccessesL[ur].equals("INV0")){INV0=true;}
else if(getempaccessesL[ur].equals("DC00")){DC00=true;}
else if(getempaccessesL[ur].equals("DOC00")){DOC00=true;}
else if(getempaccessesL[ur].equals("DTR00")){DTR00=true;}
}    
}

      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-2 col-sm-2 col-xs-12\">\r\n");
      out.write("<div class=\"logo1\">\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/dashboard.html\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/staticresources/images/corpseed-logo.png\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-10 col-sm-10 col-xs-12\">\r\n");
      out.write("<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"header-nav\">\r\n");
      out.write("<nav class=\"main-nav main-nav3\">\r\n");
      out.write("<ul class=\"main-menu\">\r\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/dashboard.html\">Dashboard</a></li>\r\n");
if(ADM00){ 
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write("<a href=\"javascript:void(0);\" data-toggle=\"dropdown\" aria-hidden=\"false\" aria-expanded=\"false\">HR<span class=\"lnr lnr-chevron-down\"></span></a>\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
if(AMU02){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/managewebuser.html\">Manage HRM Login</a></li>");
}
      out.write('\r');
      out.write('\n');
if(ME00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-employee.html\">Manage Employee</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(CLA00){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/clientadmin.html\">Manage Client's Admin</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MC00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-company.html\">Manage Company</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(ATT03){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/Manage-Attendance.html\">Manage Attendance</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(LTH00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/logintraffic.html\">Login & Traffic History</a></li>");
}
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
} 
      out.write('\r');
      out.write('\n');
if(EQ00){
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write("<a href=\"javascript:void(0);\" data-toggle=\"dropdown\" aria-hidden=\"false\" aria-expanded=\"false\">Sales<span class=\"lnr lnr-chevron-down\"></span></a>\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
if(EST00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-estimate.html\">Manage Estimate</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(EQ02){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-sales.html\">Manage Sales</a></li>");
} 
      out.write("\r\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/compliance-check.html\">Compliance Check</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
}if(DC00){
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write("<a href=\"javascript:void(0);\" data-toggle=\"dropdown\" aria-hidden=\"false\" aria-expanded=\"false\">Document<span class=\"lnr lnr-chevron-down\"></span></a>\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
if(DOC00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/document-collection.html\">Document Collection</a></li>");
} 
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
}if(CL00){ 
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write("<a href=\"javascript:void(0);\" data-toggle=\"dropdown\" aria-hidden=\"false\" aria-expanded=\"false\">Client<span class=\"lnr lnr-chevron-down\"></span></a>\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
if(CPR03){
      out.write(" <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-client.html\">Manage Client</a></li>");
}
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
} 
      out.write('\r');
      out.write('\n');
if(MT00){ 
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write("<a href=\"javascript:void(0);\" data-toggle=\"dropdown\" aria-hidden=\"false\" aria-expanded=\"false\">My Task<span class=\"lnr lnr-chevron-down\"></span></a>\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
if(MT01){
      out.write("  <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/mytask.html\">My Task Details</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MD00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/managedelivery.html\">Manage Delivery</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MDC0){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/mydocument.html\">Manage Document</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MCC0){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/calendar.html\">Calendar</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MCR0){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/certificates-renewal.html\">Certificate renewal</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MTR1){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/report.html\">Manage Report</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(TN02){
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write("<!-- <a>SEO</a> -->\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
      out.write('\r');
      out.write('\n');
if(MS04){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-seo.html\">Manage SEO OnPage</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MS09){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/seo-url-collection.html\">SEO URL Collection</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MS06){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-content.html\">Manage Content</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(SR01){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/update-report.html\">Update Report</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(SR02){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/seo-report.html\">SEO Report</a></li>");
} 
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
}if(ACC00){ 
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write("<a href=\"javascript:void(0);\" data-toggle=\"dropdown\" aria-hidden=\"false\" aria-expanded=\"false\">Account<span class=\"lnr lnr-chevron-down\"></span></a>\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
if(AC00){
      out.write(" <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manageaccount.html\">Client Accounts</a></li>");
}
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
if(MB07){
      out.write(" <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-billing.html\">Projects Billing</a></li>");
}
      out.write('\r');
      out.write('\n');
if(UBL0){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/unbilled.html\">Unbilled</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MB09){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/openpayrollhistory.html\">Payroll</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(GH00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/managetransactions.html\">Manage Transactions</a></li>");
} 
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
if(MX00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manageexpenses.html\">Manage Expense</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(CH00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/managecredit.html\">Credit history</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(GI00){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manageinvoice.html\">Manage Invoice</a></li>");
} 
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
}if(TM00){ 
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write("<a href=\"javascript:void(0);\" data-toggle=\"dropdown\" aria-hidden=\"false\" aria-expanded=\"false\">Activity Master<span class=\"lnr lnr-chevron-down\"></span></a>\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
      out.write('\r');
      out.write('\n');
if(MPP00){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-product.html\">Manage Product</a></li>");
}
      out.write('\r');
      out.write('\n');
if(MTT00){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manage-template.html\">Manage Template</a></li>");
}
      out.write('\r');
      out.write('\n');
if(MG00){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manageguide.html\">Manage Guide</a></li>");
}
      out.write('\r');
      out.write('\n');
if(MTR0){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/managetrigger.html\">Manage Trigger</a></li>");
}
      out.write('\r');
      out.write('\n');
if(MTX0){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/managetax.html\">Manage Tax</a></li>");
}
      out.write('\r');
      out.write('\n');
if(MTM0){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manageteam.html\">Manage Teams</a></li>");
}
      out.write('\r');
      out.write('\n');
if(MCO0){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/managecontacts.html\">Manage Contacts</a></li>");
}
      out.write('\r');
      out.write('\n');
if(MCP0){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/managecoupon.html\">Manage Coupon</a></li>");
} 
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
}if(RD00){
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write("<a href=\"javascript:void(0);\" data-toggle=\"dropdown\" aria-hidden=\"false\" aria-expanded=\"false\">Records<span class=\"lnr lnr-chevron-down\"></span></a>\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
if(DH00){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/download-history.html\">Download History</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(EH00){ 
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/export-history.html\">Export History</a></li>");
} 
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
}if(MA00){
      out.write("\r\n");
      out.write("<li class=\"menu-item-has-childrent\">\r\n");
      out.write(" <a href=\"javascript:void(0);\" class=\"webhide\" data-toggle=\"dropdown\" aria-hidden=\"false\" aria-expanded=\"false\">Profile<span class=\"lnr lnr-chevron-down\"></span></a>\r\n");
      out.write("<div class=\"welcomeBox\"><i class=\"fas fa-user\"></i>&nbsp;Hi, ");
      out.print(session.getAttribute("uaname") );
      out.write("<span class=\"lnr lnr-chevron-down\"></span></div>\r\n");
      out.write("<ul class=\"sub-menu\">\r\n");
if(MMP00){
      out.write("<li><a href=\"javascript:void(0);\" onclick=\"profilechapass('");
      out.print(uaIsValid1);
      out.write("','profile');\"><i class=\"fa fa-user\"></i>My Profile</a></li>");
} 
      out.write("\r\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/track-invoice.html\"><i class=\"fa fa-search\"></i>Track Invoice</a></li>\r\n");
if(MMP02){
      out.write("<li><a href=\"javascript:void(0);\" onclick=\"profilechapass('");
      out.print(uaIsValid1);
      out.write("','chapass');\"><i class=\"fa fa-lock\"></i>Change Password</a></li>");
} 
      out.write('\r');
      out.write('\n');
if(MMP03){
      out.write("<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/logout.html\"><i class=\"fa fa-sign-out\"></i>Logout</a></li>");
} 
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function profilechapass(id,page){$.ajax({type:\"POST\",url:\"");
      out.print(request.getContextPath());
      out.write("/vieweditpage\",data:{\"uid\":id},success:function(response){if(page==\"profile\")window.location=\"");
      out.print(request.getContextPath());
      out.write("/profile.html\";else if(page==\"chapass\")window.location=\"");
      out.print(request.getContextPath());
      out.write("/changepassword.html\";else if(page==\"work\")window.location=\"");
      out.print(request.getContextPath());
      out.write("/workscheduler.html\";},});}\r\n");
      out.write("</script>\r\n");
      out.write("</li>\r\n");
}
String notificationloginuaid = (String) session.getAttribute("loginuaid");
String notificationtoken=(String)session.getAttribute("uavalidtokenno");
long totalNotification=ClientACT.getTotalUnseenNotificationAdmin(notificationtoken,notificationloginuaid); 
// System.out.println(notificationloginuaid+"/"+notificationtoken+"/"+totalNotification);
String notifications[][]=ClientACT.getAllNotification(notificationtoken,notificationloginuaid);

      out.write("\r\n");
      out.write("<li class=\"notification\">\r\n");
      out.write("<a class=\"toggle_btn\" onclick=\"markAllAsReadNotification('");
      out.print(totalNotification );
      out.write("')\"><i class=\"fa fa-bell\"></i><span class=\"badge\" id=\"totalNotification\">");
if(totalNotification>0){
      out.print(totalNotification );
} 
      out.write("</span></a>\r\n");
      out.write("<div class=\"notification_box pullDown\">\r\n");
      out.write("<!--   <div class=\"text-right notification_txt\"><a href=\"javascript:void(0)\" onclick=\"markAllAsReadNotification()\">Mark all as read</a></div> -->\r\n");
      out.write("  <div class=\"clearfix notification_inner_box\">\r\n");
      out.write(" ");
if(notifications!=null&&notifications.length>0){
	 for(int i=0;i<notifications.length;i++){
	 
      out.write("\r\n");
      out.write("      <div class=\"clearfix notification_inner\">              	\r\n");
      out.write("        <a href=\"javascript:void(0)\" onclick=\"markAsReadNotification('");
      out.print(notifications[i][2] );
      out.write("')\">\r\n");
      out.write("        <div class=\"clearfix pro_box\">\r\n");
      out.write("            <div class=\"clearfix icon_box\">\r\n");
      out.write("             <i class=\"");
      out.print(notifications[i][4] );
      out.write(" icon-circle\" aria-hidden=\"true\"></i>\r\n");
      out.write("            </div> \r\n");
      out.write("            <div class=\"clearfix pro_info\"> \r\n");
      out.write("            <h6>");
      out.print(notifications[i][3] );
      out.write("</h6>\r\n");
      out.write("            <div class=\"clearfix date_box1\">");
      out.print(notifications[i][1] );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      ");
}}else{ 
      out.write("\r\n");
      out.write("      <div class=\"text-center text-muted\">No data found !!</div>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("  </div> \r\n");
      out.write("  <div class=\"text-center notification_txt mtop10\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/notifications.html\">View All &nbsp;<i class=\"fa fa-angle-right\"></i></a></div> \r\n");
      out.write("</div> \r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"mobilenoti\" style=\"display:none\">\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/notifications.html\" onclick=\"markAllAsReadNotification('");
      out.print(totalNotification );
      out.write("')\"><span id=\"totalNotification\">Notification");
if(totalNotification>0){
      out.write("<small>");
      out.print(totalNotification );
      out.write("</small>");
} 
      out.write("</span></a>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<div class=\"mobile-menu\">\r\n");
      out.write("<a href=\"#\" class=\"show-menu\"><span class=\"lnr lnr-indent-decrease\"></span></a>\r\n");
      out.write("<a href=\"#\" class=\"hide-menu\"><span class=\"lnr lnr-indent-increase\"></span></a>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

String urlpage = request.getParameter("uid");
if(urlpage==null||urlpage==""){
	urlpage=request.getParameter("page_no");
	if(urlpage==null||urlpage=="")urlpage="NA";
}
// System.out.println("pge=="+urlpage);
if(!urlpage.equalsIgnoreCase("managewebuser.html")&&!urlpage.equalsIgnoreCase("edituser.html")){
	session.removeAttribute("muname");
	session.removeAttribute("mumobile");
	session.removeAttribute("mutype");
}
if(!urlpage.equalsIgnoreCase("clientadmin.html")){
	session.removeAttribute("claname");
	session.removeAttribute("clamobile");
}
if(!urlpage.equalsIgnoreCase("manage-company.html")&&!urlpage.equalsIgnoreCase("editcompany.html")){
	session.removeAttribute("mcname");
	session.removeAttribute("mcfrom");
	session.removeAttribute("mcto");
}
if(!urlpage.equalsIgnoreCase("calendar.html")){
	session.removeAttribute("date_range_value");
}
if(!urlpage.equalsIgnoreCase("manage-employee.html")&&!urlpage.equalsIgnoreCase("editemployee.html")){
	session.removeAttribute("mename");
	session.removeAttribute("memobile");
	session.removeAttribute("meemail");
}
if(!urlpage.equalsIgnoreCase("Manage-Attendance.html")){
	session.removeAttribute("maEmpID");
	session.removeAttribute("maMonthDate");
	session.removeAttribute("mafrom");
	session.removeAttribute("mato");
}

if(!urlpage.equalsIgnoreCase("manage-billing.html")){
	session.removeAttribute("billingDateRangeAction");
	session.removeAttribute("billingClientName");
	session.removeAttribute("billingInvoiceNo");
	session.removeAttribute("billingDoAction");	
	session.removeAttribute("billingContactName");
}
if(!urlpage.equalsIgnoreCase("unbilled.html")){
	session.removeAttribute("unbillDateRangeAction");
	session.removeAttribute("unbill_no");
	session.removeAttribute("companyName");
	session.removeAttribute("unbillContactName");
	session.removeAttribute("archiveFilter");	
}
if(!urlpage.equalsIgnoreCase("all-invoice.html")){
	session.removeAttribute("invoiceDateRangeAction");
	session.removeAttribute("invoice_no");
	session.removeAttribute("invoicecompanyName");
	session.removeAttribute("invoicedContactName");
	session.removeAttribute("b2bb2c");
}
if(!urlpage.equalsIgnoreCase("manage-sales.html")){	        
	session.removeAttribute("salesInvoiceAction");
	session.removeAttribute("salesPhoneAction");
	session.removeAttribute("salesPhoneKeyAction");
	session.removeAttribute("salesProductAction");
	session.removeAttribute("salesClientAction");
	session.removeAttribute("salesContactAction");
	session.removeAttribute("salesSoldByAction");
	session.removeAttribute("salesSoldByUidAction");
	session.removeAttribute("salesDateRangeAction");
	session.removeAttribute("salesFilter");
}

if(!urlpage.equalsIgnoreCase("manage-template.html")){
	session.removeAttribute("templateDateRangeAction");
	session.removeAttribute("templateNameAction");
	session.removeAttribute("templateDoAction");
}
if(!urlpage.equalsIgnoreCase("manage-product.html")){
	session.removeAttribute("productDateRangeAction");
	session.removeAttribute("productIdAction");
	session.removeAttribute("productNameAction");
}
if(!urlpage.equalsIgnoreCase("manageteam.html")){
	session.removeAttribute("teamDateRangeAction");
	session.removeAttribute("teamNameDoAction");
	session.removeAttribute("teamDoAction");
}
if(!urlpage.equalsIgnoreCase("manage-client.html")&&!urlpage.equalsIgnoreCase("editclient.html")){
	session.removeAttribute("mclientname");
	session.removeAttribute("mclientmobile");
	session.removeAttribute("mclientlocation");
	session.removeAttribute("mclientfrom");
	session.removeAttribute("mclientto");
}

if(!urlpage.equalsIgnoreCase("manageaccount.html")&&!urlpage.equalsIgnoreCase("accountstatement.html")){
	session.removeAttribute("accountDateRangeAction");
	session.removeAttribute("accountSearchByClientName");
	session.removeAttribute("accountSearchByClientId");
}
if(!urlpage.equalsIgnoreCase("mytask.html")&&!urlpage.contains("edittask-")){
	session.removeAttribute("myTaskDateRange");
	session.removeAttribute("myTaskDoAction");
	session.removeAttribute("myTaskClientAction");
	session.removeAttribute("myTaskClientKeyAction");
	session.removeAttribute("myTaskContactAction");
	session.removeAttribute("myTaskServiceAction");
	session.removeAttribute("searchByActivity");
}
if(!urlpage.contains("edittask-")){
	session.removeAttribute("searchByActivity");
}
if(!urlpage.contains("assignmytask-")){
	session.removeAttribute("searchByActivity1");
}
if(!urlpage.equalsIgnoreCase("managedelivery.html")&&!urlpage.contains("assignmytask-")){
	session.removeAttribute("deliveryDateRangeAction");
	session.removeAttribute("deliveryDoAction");
	session.removeAttribute("deliveryInvoiceAction");
	session.removeAttribute("deliveryClientAction");
	session.removeAttribute("deliveryContactAction");
	session.removeAttribute("searchByActivity1");
}

if(!urlpage.equalsIgnoreCase("document-collection.html")){
	session.removeAttribute("collectionDateRangeAction");
	session.removeAttribute("collectionDoAction");
	session.removeAttribute("collectionInvoiceAction");
	session.removeAttribute("collectionClientAction");
	session.removeAttribute("collectionContactAction");
}

if(!urlpage.equalsIgnoreCase("manage-estimate.html")){
	session.removeAttribute("estimateContactAction");
	session.removeAttribute("estDoAction");
	session.removeAttribute("ClientNameDoAction");
	session.removeAttribute("estimateNoDoAction");
	session.removeAttribute("dateRangeDoAction");
}
if(!urlpage.equalsIgnoreCase("mydocument.html")&&!urlpage.contains("subdocuments-")&&!urlpage.contains("personalfiles-")){
	session.removeAttribute("mdclientname");
	session.removeAttribute("mdclientid");
	session.removeAttribute("mdfoldername");
	session.removeAttribute("mdprojectno");
	/* new */
	session.removeAttribute("doDocumentAction");
	session.removeAttribute("SearchByClientName");
	session.removeAttribute("SearchByClientId");
}
if(!urlpage.contains("personalfiles-")){
	session.removeAttribute("personalDoActionFiles");
	session.removeAttribute("pdocsortby_ord");
	session.removeAttribute("pdocsorting_order");
}
if(!urlpage.contains("documentfiles-")){
	session.removeAttribute("doActionFiles");
	session.removeAttribute("dcsortby_ord");
	session.removeAttribute("dcesorting_order");
}
if(!urlpage.equalsIgnoreCase("manageexpenses.html")){
	session.removeAttribute("expenseDateRangeAction");
	session.removeAttribute("expsortby_ord");
	session.removeAttribute("expClientName");
	session.removeAttribute("expContactMobile");
	session.removeAttribute("expsorting_order"); 
}
if(!urlpage.equalsIgnoreCase("download-history.html")){
	session.removeAttribute("history_page");
	session.removeAttribute("hisDateRangeDoAction");
}
if(!urlpage.equalsIgnoreCase("export-history.html")){
	session.removeAttribute("ex_history_page");
	session.removeAttribute("ex_hisDateRangeDoAction");
}
if(!urlpage.equalsIgnoreCase("manageguide.html")){
	session.removeAttribute("guideDateRangeAction");
	session.removeAttribute("guideProductAction");
	session.removeAttribute("guideProductKeyAction");
	session.removeAttribute("guideMilestoneAction");
}
if(!urlpage.equalsIgnoreCase("managetransactions.html")){
	session.removeAttribute("transactionDateRangeAction");
	session.removeAttribute("transactionClientNameAction");
	session.removeAttribute("transactionInvoiceAction");
	session.removeAttribute("transactionDoAction");
}
if(!urlpage.equalsIgnoreCase("managecredit.html")){
	session.removeAttribute("creditDateRangeAction");
}
if(!urlpage.equalsIgnoreCase("managetrigger.html")){
	session.removeAttribute("TriggerNameDoAction");
	session.removeAttribute("TriggerNoDoAction");
	session.removeAttribute("TriggerdateRangeDoAction");
}
if(!urlpage.equalsIgnoreCase("managecontacts.html")){
	session.removeAttribute("contactDateRangeAction");
	session.removeAttribute("contactCompanyNameAction");	
}
if(!urlpage.equalsIgnoreCase("certificates-renewal.html")){
	session.removeAttribute("certRenewalTaskDateRange");
}
if(!urlpage.equalsIgnoreCase("notifications.html")){
	session.removeAttribute("notificationPageLimit");
	session.removeAttribute("notificationPageStart");
	session.removeAttribute("notificationPageEnd");
	session.removeAttribute("notificationTaskDateRange");
}
if(!urlpage.equalsIgnoreCase("report.html")){
	session.removeAttribute("reportprojectNo");
	session.removeAttribute("reportAssigneeUid");
	session.removeAttribute("reportAssigneeName");
}

      out.write('\r');
      out.write('\n');
      out.write('	');
		
	String estimate=request.getParameter("estimate");
	String invoice=request.getParameter("invoice");
	String mobile=request.getParameter("mobile");
	
	if(estimate==null||estimate.length()<=0)estimate="NA";
	if(invoice==null||invoice.length()<=0)invoice="NA";
	if(mobile==null||mobile.length()<=0)mobile="NA";
	String token=(String)session.getAttribute("uavalidtokenno");
	
	String[][] estimates=null;
	if(!estimate.equalsIgnoreCase("NA"))
		estimates=Enquiry_ACT.findEstimateSaleBySaleNo(estimate,mobile, token);
	else if(!invoice.equalsIgnoreCase("NA")){
		estimate=TaskMaster_ACT.findEstimateByInvoice(invoice,token);
		if(estimate!=null&&!estimate.equalsIgnoreCase("NA"))
			estimates=Enquiry_ACT.findEstimateSaleBySaleNo(estimate,mobile, token);
	}
	
	
      out.write("\r\n");
      out.write("	<div id=\"content\">		\r\n");
      out.write("		<div class=\"main-content\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("			\r\n");
      out.write("<div class=\"row mb30 mt-10\">\r\n");
      out.write("<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/track-invoice.html\" method=\"get\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-sm-3 mb-10\">\r\n");
      out.write("<input type=\"search\" name=\"estimate\" class=\"form-control\" placeholder=\"Estimate No..\" autocomplete=\"off\"\r\n");
if(!estimate.equalsIgnoreCase("NA")){ 
      out.write("value=\"");
      out.print(estimate);
      out.write('"');
} 
      out.write(">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-3 mb-10\">\r\n");
      out.write("<input type=\"search\" name=\"invoice\" class=\"form-control\" placeholder=\"Invoice No..\" autocomplete=\"off\"\r\n");
if(!invoice.equalsIgnoreCase("NA")){ 
      out.write("value=\"");
      out.print(invoice);
      out.write('"');
} 
      out.write(">\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-3 mb-10\">\r\n");
      out.write("<input type=\"search\" name=\"mobile\" class=\"form-control\" onkeypress=\"return isNumber(event)\" placeholder=\"Mobile No..\" autocomplete=\"off\"\r\n");
if(!mobile.equalsIgnoreCase("NA")){ 
      out.write("value=\"");
      out.print(mobile);
      out.write('"');
} 
      out.write(" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-sm-3\">\r\n");
      out.write("<button type=\"submit\" class=\"btn btn-primary btn-block\" style=\"height: 40px;\"><i class=\"fa fa-search\"></i>&nbsp;&nbsp;Search</button>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("                	<div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                	<div class=\"table-responsive\">\r\n");
      out.write("                        <table class=\"ctable\">\r\n");
      out.write("						    <thead>\r\n");
      out.write("						    <tr class=\"tg\" style=\"position:absolute;width:100%;display:inline-table\">\r\n");
      out.write("						    <th class=\"tg-cly1\">  \r\n");
      out.write("						        <div class=\"line\"></div>\r\n");
      out.write("						    </th>\r\n");
      out.write("						    <th class=\"tg-cly1\">\r\n");
      out.write("						      <div class=\"line\" ></div>\r\n");
      out.write("						    </th>\r\n");
      out.write("						    <th class=\"tg-cly1\">\r\n");
      out.write("						      <div class=\"line\" ></div>\r\n");
      out.write("						    </th>\r\n");
      out.write("						    <th class=\"tg-cly1\">\r\n");
      out.write("						      <div class=\"line\" ></div>\r\n");
      out.write("						    </th>\r\n");
      out.write("						    <th class=\"tg-cly1\">\r\n");
      out.write("						      <div class=\"line\" ></div>\r\n");
      out.write("						    </th>\r\n");
      out.write("						    <th class=\"tg-cly1\">\r\n");
      out.write("						      <div class=\"line\" ></div>\r\n");
      out.write("						    </th>\r\n");
      out.write("  							</tr>\r\n");
      out.write("						        <tr>\r\n");
      out.write("						            <th>Service</th>\r\n");
      out.write("						            <th>Remarks</th>\r\n");
      out.write("						        </tr>\r\n");
      out.write("						    </thead>\r\n");
      out.write("						    <tbody>\r\n");
      out.write("						    ");

						    if(estimates!=null&&estimates.length>0){
						    	for(int i=0;i<estimates.length;i++){						    		
						    	//esrefid,escompany,esprodqty,esprodname,esprodname,esregdate
						    
      out.write("\r\n");
      out.write("						    <tr>\r\n");
      out.write("						    <td>");
      out.print(estimates[i][3] );
      out.write("&nbsp;(");
      out.print(estimates[i][2] );
      out.write(")</td>\r\n");
      out.write("						    <td>Estimate Created on <b>");
      out.print(estimates[i][5] );
      out.write("</b></td>\r\n");
      out.write("						    </tr>\r\n");
      out.write("						   	");
if(estimates[i][6].equalsIgnoreCase("Cancelled")){ 
      out.write("\r\n");
      out.write("						   	<tr>\r\n");
      out.write("						    <td>");
      out.print(estimates[i][3] );
      out.write("&nbsp;(");
      out.print(estimates[i][2] );
      out.write(")</td>\r\n");
      out.write("						    <td>Estimate <b class=\"text-danger\">Cancelled</b> on <b>");
      out.print(estimates[i][5] );
      out.write("</b></td>\r\n");
      out.write("						    </tr>						   	\r\n");
      out.write("						    ");
}}
						    String paymentType=Enquiry_ACT.findEstimateSalesPayType(estimate, token);
						    String[][] sales=TaskMaster_ACT.findAllSalesListByEstimate(estimate, token);
						    if(sales!=null&&sales.length>0){
						    	for(int i=0;i<sales.length;i++){		
						    		String docClass="text-primary";
						    		String docStatus="Active";
						    		if(Integer.parseInt(sales[i][12])==2){
						    			docClass="text-danger";docStatus="Inactive";
						    		}
						    		else if(Integer.parseInt(sales[i][12])==3){
						    			docClass="text-expired";docStatus="Expired";
						    		}
						    		else if(Integer.parseInt(sales[i][12])==4){
						    			docClass="text-success";docStatus="Completed";
						    		}
						    		
						    		// msinvoiceno,msproductname,mssolddate,msworkpercent,msworkstatus,"
						 			//		msassignedtoname,msdeliveredon,msprojectstatus,msdeliverydate,"
						 			//		msdeliverytime,mscancelstatus,document_assign_uaid,document_status\,
						 			//delivery_assign_date,msworkpercent
						    
      out.write("\r\n");
      out.write("						    <tr>\r\n");
      out.write("						    <td>");
      out.print(sales[i][1] );
      out.write("</td>\r\n");
      out.write("						    <td>Estimate Converted to Sales on <b>");
      out.print(sales[i][2] );
      out.write("</b> by payment term <b>");
      out.print(paymentType );
      out.write("</b></td>\r\n");
      out.write("						    </tr>		\r\n");
      out.write("						    <tr>\r\n");
      out.write("						    <td>");
      out.print(sales[i][1] );
      out.write("</td> \r\n");
      out.write("						    <td>Assigned to <b>Document Department</b> on <b>");
      out.print(sales[i][2] );
      out.write("</b> and document status is <b class=\"");
      out.print(docClass);
      out.write('"');
      out.write('>');
      out.print(docStatus );
      out.write("</b></td>\r\n");
      out.write("						    </tr>						    	\r\n");
      out.write("						    \r\n");
      out.write("						    ");
if(!sales[i][5].equalsIgnoreCase("Unassigned")){
						    	String projectColor="text-danger";
						    	String projectStatus="Inactive";
						      	if(sales[i][7].equalsIgnoreCase("2")){
						      		projectColor="text-success";projectStatus="Completed";
						      	}
						      	else if(sales[i][7].equalsIgnoreCase("3")){
						      		projectColor="text-primary";projectStatus="In-Progress";
						      	}						    	
						    	
      out.write("\r\n");
      out.write("						    <tr>\r\n");
      out.write("						    <td>");
      out.print(sales[i][1] );
      out.write("</td> \r\n");
      out.write("						    <td>Assigned to Operation Team '<b>");
      out.print(sales[i][5] );
      out.write("</b>' on <b>");
      out.print(sales[i][13] );
      out.write("</b></td>\r\n");
      out.write("						    </tr>					    \r\n");
      out.write("						    \r\n");
      out.write("						    <tr>\r\n");
      out.write("						    <td>");
      out.print(sales[i][1] );
      out.write("</td> \r\n");
      out.write("						    <td>Sale work is <b class=\"");
      out.print(projectColor);
      out.write('"');
      out.write('>');
      out.print(projectStatus );
      out.write("</b> and work <b class=\"");
      out.print(projectColor);
      out.write('"');
      out.write('>');
      out.print(sales[i][14] );
      out.write(" %</b> Completed.</td>\r\n");
      out.write("						    </tr>\r\n");
      out.write("						    \r\n");
      out.write("						    ");
if(sales[i][10].equals("1")){ 
      out.write("\r\n");
      out.write("						    <tr>\r\n");
      out.write("						    <td>");
      out.print(sales[i][1] );
      out.write("</td> \r\n");
      out.write("						    <td>Sales <b class=\"text-danger\">Cancelled</b> on <b>");
      out.print(estimates[i][5] );
      out.write("</b></td>\r\n");
      out.write("						    </tr>						    						    \r\n");
      out.write("						    ");
}}}}}else{
      out.write("\r\n");
      out.write("						    <tr>\r\n");
      out.write("						    <td colspan=\"3\">\r\n");
      out.write("						    <h4 class=\"text-danger text-center\">No Data Found</h4>\r\n");
      out.write("						    </td>\r\n");
      out.write("						    </tr>\r\n");
      out.write("						    ");
} 
      out.write("												                                 \r\n");
      out.write("						    </tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						</div>											\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<p id=\"end\" style=\"display:none;\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div id=\"footer\"><div class=\"footer\"><div class=\"container\"><div class=\"footer-bottom\"><div class=\"row\"><div class=\"col-md-12 col-sm-12 col-xs-12\"><div class=\"copyright\">Copyright &copy; 2021 Corpseed ITES Pvt Ltd All Rights Reserved.</div></div></div></div></div></div></div>\r\n");
      out.write("<div class=\"alert-show\"><div class=\"alert-bg alert-striped\" id=\"errorMsg\" style=\"font-size: 17px;width: 100%;height: 100%;\"></div></div>\r\n");
      out.write("<div class=\"alert-show1\"><div class=\"alert-bg1 alert-striped\" id=\"errorMsg1\" style=\"font-size: 17px;width: 100%;height: 100%;\"></div></div>\r\n");
      out.write(" <div class=\"processing_loader\" style=\"display:none\"><div class=\"spin_box\"></div></div> ");
      out.write("\r\n");
      out.write("</div>	\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.fancybox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/nicEdit.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/globalscript.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/select2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/daterangepicker.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/mdtimepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/fontawsome.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/theme.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/jszip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/pdfmake.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/vfs_fonts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.html5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.print.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/buttons.colVis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.select.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/staticresources/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready( function () {\r\n");
      out.write("	var role=\"");
      out.print(session.getAttribute("emproleid"));
      out.write("\";\r\n");
      out.write("	$(\".checked\").click(function(){\r\n");
      out.write("		 if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("			 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("	$(\"#CheckAll\").click(function(){\r\n");
      out.write("	$('.checked').prop('checked', this.checked);\r\n");
      out.write("	if ($(\".checked\").is(\":checked\")){\r\n");
      out.write("		 	 $(\".hashico\").hide()\r\n");
      out.write("			 $(\"#CheckAll\").show();\r\n");
      out.write("			 $(\"#SearchOptions\").hide();\r\n");
      out.write("			 $(\"#SearchOptions1\").show();\r\n");
      out.write("	}else{\r\n");
      out.write("		 $(\".hashico\").show()\r\n");
      out.write("		 $(\"#CheckAll\").hide();\r\n");
      out.write("		 $(\"#SearchOptions\").show();\r\n");
      out.write("		 $(\"#SearchOptions1\").hide();\r\n");
      out.write("	}\r\n");
      out.write("		    \r\n");
      out.write("	});\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write(" $(window).load(function() {\r\n");
      out.write("  $(\".processing_loader\").fadeOut();\r\n");
      out.write("}); \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function showLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeIn(); \r\n");
      out.write("} \r\n");
      out.write("function hideLoader(){\r\n");
      out.write("   $(\".processing_loader\").fadeOut();  \r\n");
      out.write("}  \r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.timepicker').mdtimepicker();\r\n");
      out.write("function openClock(id){\r\n");
      out.write("$('#'+id).mdtimepicker();\r\n");
      out.write("}\r\n");
      out.write("function openCalendar(id){\r\n");
      out.write("	$(\"#\"+id).datepicker({changeMonth:true,changeYear:true,dateFormat:'yy-mm-dd'});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('.has-clear input[type=\"text\"]').on('input propertychange', function() {\r\n");
      out.write("  var $this = $(this);\r\n");
      out.write("  var visible = Boolean($this.val());\r\n");
      out.write("  $this.siblings('.form-control-clear').toggleClass('hidden', !visible);\r\n");
      out.write("}).trigger('propertychange');\r\n");
      out.write("\r\n");
      out.write("$('.form-control-clear').click(function() {\r\n");
      out.write("  $(this).siblings('input[type=\"text\"]').val('')\r\n");
      out.write("    .trigger('propertychange').focus();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function goBack() {\r\n");
      out.write("  window.history.back();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
