/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-09-22 13:56:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.staticresources.autocomplete;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import admin.enquiry.Enquiry_ACT;
import net.sf.json.JSONObject;
import net.sf.json.JSONArray;
import java.sql.*;
import java.util.*;
import commons.DbCon;

public final class getnewproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("commons.DbCon");
    _jspx_imports_classes.add("net.sf.json.JSONArray");
    _jspx_imports_classes.add("admin.enquiry.Enquiry_ACT");
    _jspx_imports_classes.add("net.sf.json.JSONObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=iso-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


JSONArray jsonArr = new JSONArray();
JSONObject json=new JSONObject();
String name = (String)request.getParameter("name");
String field = (String)request.getParameter("field");
String token= (String)session.getAttribute("uavalidtokenno");
String addedby=(String)session.getAttribute("loginuID");
ResultSet rs=null;
PreparedStatement ps=null;
try(Connection con=DbCon.getCon("","","")){
if(field.equalsIgnoreCase("salesinvoice")){
	String sql="SELECT msinvoiceno,mscontactrefid FROM managesalesctrl where msinvoiceno like '%"+name+"%' and mstoken='"+token+"' group by msinvoiceno limit 10";
// 		System.out.println(sql);
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("name",rs.getString(1));
		json.put("value",rs.getString(1));
		String cname="NA";
		String cmobile="NA";
		String contact[][]=Enquiry_ACT.getClientDetails(rs.getString(2), token);
		if(contact!=null&&contact.length>0){
	cname=contact[0][0];
	cmobile=contact[0][1];
		}
		json.put("cname",cname);
		json.put("cmobile",cmobile);
	    jsonArr.add(json);
	}
}else if(field.equalsIgnoreCase("salehsntax")){
	String sql="SELECT mtrefid,mthsncode,mtsgstpercent,mtcgstpercent,mtigstpercent FROM managetaxctrl where mthsncode like '%"+name+"%' and mttoken='"+token+"' limit 10";
// 		System.out.println(sql);
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("name",rs.getString(2)+" -> "+rs.getString(4)+"% CGST -> "+rs.getString(3)+"% SGST -> "+rs.getString(5)+" % IGST");
		json.put("value",rs.getString(2)); 
		json.put("refid",rs.getString(1));
	    json.put("hsn",rs.getString(2));    
	    json.put("sgst",rs.getString(3));   
	    json.put("cgst",rs.getString(4));   
	    json.put("igst",rs.getString(5));   
	    	       
	    jsonArr.add(json);
	}
}else if(field.equalsIgnoreCase("GetProductDetails")){
	String sql="SELECT pname,pdescription,ptype FROM product_master where prefid = '"+name+"' and ptokenno='"+token+"'";
// 		System.out.println(sql);
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("name",rs.getString(1));
	    json.put("type",rs.getString(3));    
	    json.put("remarks",rs.getString(2));   
	    	       
	    jsonArr.add(json);
	}
}else if(field.equalsIgnoreCase("producttypename")){
	String sql="SELECT stypename,sid FROM service_type where stypename like '%"+name+"%' and stokenno='"+token+"' and sstatus='1'  LIMIT 0 , 10";
// 		System.out.println(sql);
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("name",rs.getString(1));
	    json.put("value",rs.getString(1));    
	    json.put("sid",rs.getString(2));   
	    	       
	    jsonArr.add(json);
	}
}else if(field.equalsIgnoreCase("productname")){
	String sql="SELECT pid,pname,ptype,pdescription,prefid,pcentral,pstate,pglobal FROM product_master where pname like '%"+name+"%' and ptokenno='"+token+"' and pstatus='1'  LIMIT 0 , 10";
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("pid",rs.getString(1));
		json.put("name",rs.getString(2));
	    json.put("value",rs.getString(2));    
	    json.put("ptype",rs.getString(3));    
	    json.put("pdesc",rs.getString(4));  
	    json.put("prefid",rs.getString(5)); 
	    json.put("central",rs.getString(6));
	    json.put("state",rs.getString(7));
	    json.put("global",rs.getString(8));
	    	       
	    jsonArr.add(json);
	}
}else if(field.equalsIgnoreCase("productData")){
	String sql="SELECT pid,pname,ptype,pdescription,prefid,tat_value,tat_type FROM product_master where prefid='"+name+"' and ptokenno='"+token+"' and pstatus='1'";
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("pid",rs.getString(1));
		json.put("name",rs.getString(2));
	    json.put("value",rs.getString(2));    
	    json.put("ptype",rs.getString(3));    
	    json.put("pdesc",rs.getString(4));  
	    json.put("prefid",rs.getString(5));   
	    json.put("tatValue",rs.getString(6)); 
	    json.put("tatType",rs.getString(7)); 
	    	       
	    jsonArr.add(json);
	}
}else if(field.equalsIgnoreCase("productprice")){
	String sql="SELECT ppid,pp_service_type,pp_price,pp_hsncode,pp_igstpercent,pp_total_price FROM product_price where pp_prodrefid = '"+name+"' and pp_tokenno='"+token+"' order by ppid";
// 	System.out.println(sql);
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("id",rs.getString(1));
		json.put("service",rs.getString(2));
	    json.put("price",rs.getString(3));    
	    json.put("hsn",rs.getString(4));    
	    json.put("igst",rs.getString(5));  
	    json.put("total",rs.getString(6));    
	    	       
	    jsonArr.add(json);
	}
}else if(field.equalsIgnoreCase("Select2Gst")){
	String sql="SELECT vtselect2id,vtselect2tax FROM virtualtaxidctrl where vtprodrefid = '"+name+"' and vttoken='"+token+"' and vtaddedby='"+addedby+"'";
// 	System.out.println(sql);
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("id",rs.getString(1));
		json.put("tax",rs.getString(2));
	    	       
	    jsonArr.add(json);
	}
}else if(field.equalsIgnoreCase("productmilestone")){
	String sql="SELECT pmid,pm_milestonename,pm_timelinevalue,pm_timelineunit,pmsteps,pm_assign,pm_pricepercent FROM product_milestone where pm_prodrefid = '"+name+"' and pm_tokeno='"+token+"' order by pmid";
// 	System.out.println(sql);
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("id",rs.getString(1));
		json.put("name",rs.getString(2));
	    json.put("timelinevalue",rs.getString(3));    
	    json.put("timelineunit",rs.getString(4));    
	    json.put("step",rs.getString(5));  
	    json.put("assign",rs.getString(6));    
	    json.put("pricePercent",rs.getString(7));    
	    	       
	    jsonArr.add(json);
	}
}else if(field.equalsIgnoreCase("productdocument")){
	String sql="SELECT pdid,pd_docname,pd_description,pd_uploadby,pd_visibility FROM product_documents where pd_prodrefid = '"+name+"' and pd_token='"+token+"' order by pdid";
// 	System.out.println(sql);
	ps=con.prepareStatement(sql);
	rs =ps.executeQuery();
	while(rs.next())
	{
		json.put("id",rs.getString(1));
		json.put("name",rs.getString(2));
	    json.put("description",rs.getString(3));    
	    json.put("uploadby",rs.getString(4)); 
	    json.put("visibility",rs.getString(5)); 
	    	       
	    jsonArr.add(json);
	}
}
out.println(jsonArr);
}catch(Exception e){
	e.printStackTrace();
}finally{
	if(ps!=null){ps.close();}
	if(rs!=null){rs.close();}
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
